cv32/tests/core/README.md

No significant changes, just testing the PR process at @MikeOpenHWGroup's request.

Corrected the url for Metrics in cv32/tests/core/README.md

---

cv32/tb/core/tb_top_verilator.cpp
cv32/tests/core/Makefile
cv32/tests/core/README.md

This PR adds support for Verilator.

Ohw mike 20191214

---

MergeTest.md
dummy.md

Deleted the dummy file and modified the MergeTest file.

My new feature

---

MergeTest.md

Signed-off-by: David Poulin <dpoulin@datumtc.ca>

test commit. modified mergetest.md

---

MergeTest.md

Signed-off-by: Wajid M <wajid.minhass@silabs.com>

Merge: Take 3

---

cv32/tb/uvmt_cv32/Makefile

Export DV_UVM variable

---

cv32/tests/core/Makefile

Signed-off-by: Michael Thompson <mike@openhwgroup.org>

Fix xrun-compile-only

---

cv32/sim/core/Makefile
cv32/sim/core/README.md
cv32/tb/core/tb_top.sv

Make the cv32/sim director "the" place to run simulations.

PR from ohw_mike_20200207

---

cv32/tests/core/Makefile
cv32/tests/core/firmware/start.S

I just modified two files cv32/tests/core/Makefile and cv32/tests/core/firmware/start.S
if you want to run all test with questa, you can write : make questa-all
if you want to run a specific test, for instance add test, you can write : make questa-unit-test add
It is the same thing for compliance riscv, to run I_LBU_01 : make questa-unit-test  I_LBU_01
It works on my side.

Patch for issue #52

---

.gitignore
GitCheats.txt
README.md
core-v-cores/README.md
cv32/sim/core/Makefile
cv32/tb/core/riscv_wrapper.sv
lib/README.md
lib/sim_libs/cluster_clock_gating.sv

Integrates a hack to use a simulation model of cluster_clock_gating.  This is an interim measure until https://github.com/openhwgroup/cv32e40p/issues/208 is resolved.

ohw mike 20200211

---

cv32/tests/uvmt_cv32/base-tests/uvmt_cv32_base_test.sv
cv32/tests/uvmt_cv32/base-tests/uvmt_cv32_test_cfg.sv

Signed-off-by: David Poulin <dpoulin@datumtc.ca>

Fix for issue 32:  changes to test_cfg and test_base for CV32 tests

---

cv32/tests/uvmt_cv32/bin/README.md
cv32/tests/uvmt_cv32/bin/test_template/README.md
cv32/tests/uvmt_cv32/bin/test_template/new_test.sh
cv32/tests/uvmt_cv32/bin/test_template/test_template.sv

Added test case template and generator script for uvmt_cv32

Push for issue 34

---

cv32/sim/core/Makefile
cv32/sim/core/README.md

Developed on branch ohw_mike_20200214

Unit testing for both Questa and dsim

---

cv32/sim/core/Makefile
cv32/sim/questa/software.tcl
cv32/sim/questa/vsim.tcl
cv32/sim/questa/waves.tcl
cv32/sim/uvmt_cv32/Makefile

Signed-off-by: sjthales <sebastien.jacq@thalesgroup.com>

adding questa support to core makefile, adding tcl scripts for questa

---

cv32/sim/uvmt_cv32/Makefile

Signed-off-by: sjthales <sebastien.jacq@thalesgroup.com>

updating UVM Makefile

---

cv32/tb/uvmt_cv32/uvmt_cv32_dut_wrap.sv
cv32/tests/uvmt_cv32/base-tests/uvmt_cv32_base_test.sv
cv32/tests/uvmt_cv32/base-tests/uvmt_cv32_test_cfg.sv
lib/uvm_libs/uvml_logs/uvml_logs_pkg.sv
lib/uvm_libs/uvml_logs/uvml_logs_rs_json.sv

Hi David.   This is an easy pull request.  The changes are:
- compile in all the stuff we commented out on Wednesday due to the whole UVM-1.2 mess (the Makefile now tells Cadence to use 1.2).
- use your report_server, not the overly verbose default one.
- minor tweaks to messaging (makes the logfile look cleaner).

Ohw mike 20200313

---

cv32/sim/Common.mk
cv32/tb/uvmt_cv32/uvmt_cv32_dut_wrap.sv

Update to point to latest RTL

---

cv32/sim/core/README.md

Proposal for new hello world makefile target for cv32/sim/core/README.md for verilator.
Signed-off-by: Smattacus <Smattacus@gmail.com>

Updated verilator hello world makefile target.

---

cv32/tb/core/mm_ram.sv
cv32/tb/core/riscv_wrapper.sv
cv32/tb/uvmt_cv32/uvmt_cv32_dut_wrap.sv

Add the ability to control the assertion of debug_req from mm_ram to the core.

Add debug req

---

cv32/bsp/Makefile
cv32/sim/Common.mk
cv32/tb/uvmt_cv32/imperas_iss.flist
cv32/tb/uvmt_cv32/uvmt_cv32_pkg.sv
vendor_lib/imperas/riscv_CV32E40P_OVPsim/sv/riscv_CV32E40P.sv

One modification to fix a VCS compilation error.
The other ones are not directly linked to VCS but are useful to have cleaner repository.

VCS support: additional preliminary modifications

---

cv32/sim/Common.mk
cv32/sim/README.md
cv32/sim/core/Makefile
cv32/sim/core/README.md
cv32/sim/uvmt_cv32/README.md
cv32/sim/uvmt_cv32/vcs.mk

Signed-off-by: Massimiliano Giacometti <massimiliano.giacometti@hensoldt-cyber.com>
- VCS support for core tests
- adaptations in VCS flow for UVM tests

vcs support for core + fixes for uvm

---

cv32/tb/uvmt_cv32/uvmt_cv32_step_compare.sv

Simplified always block calling compare, removed fork/join_any and #60ns delay

Simplified always block calling compare

---

cv32/sim/uvmt_cv32/xrun.mk
cv32/tests/core/debug_test/debug_test.c

Also add ability to run xcelium in single step mode using XRUN_SINGLE_STEP variable
Address issue: https://github.com/openhwgroup/cv32e40p/issues/388
Signed-off-by: Paul Zavalney <paul.zavalney@silabs.com>

Update debug_test for new trigger access change. 

---

cv32/tb/uvmt_cv32/uvmt_cv32_step_compare.sv

Addresses https://github.com/openhwgroup/core-v-verif/issues/149#issuecomment-656473140

removed ; from macros, removed a few commented out statements

---

cv32/tb/uvmt_cv32/uvmt_rv32isa_covg.svh

Please pull these updates for the compressed Instruction coverage. The coverage has not yet been completely validated, but there is sufficient confidence in the code to commit.

32 c coverage

---

cv32/sim/Common.mk
cv32/tests/core/debug_test/debugger_exception.S

Adds the missing debugger_exception.S and also updates the Common.mk for proper linking.

Fix debug test  exception

---

cv32/tb/core/mm_ram.sv

Enables fast random number generation for directed tests

add a virtual register for fast random number generation

---

.metrics.json
cv32/sim/tools/dsim/ccov_scopes.txt
cv32/sim/uvmt_cv32/dsim.mk

Coverage Coverage by default

---

cv32/bsp/Makefile
cv32/sim/Common.mk
cv32/sim/core/Makefile
cv32/sim/uvmt_cv32/dsim.mk
cv32/sim/uvmt_cv32/vcs.mk
cv32/sim/uvmt_cv32/vsim.mk
cv32/sim/uvmt_cv32/xrun.mk

do not automatically clean bsp when building a test

add source dependencies into the bsp makefile

---

cv32/tb/core/cv32e40p_tb_wrapper.sv

Hey!
I added `RAM_ADDR_WIDTH` for input port `instr_addr_i`.

Added parametrized width of instr_addr_i

---

vendor_lib/imperas/design/ram.sv

Hey!
In this pull request I remove unnecessary `/*sparse*/`

remove unnecessary /*sparse*/

---

bin/cv_regress
cv32/sim/uvmt_cv32/xrun.mk

Simple point fix of cv_regress.

fix bugs when user does not set makeargs

---

.metrics.json
cv32/sim/Common.mk

Latest RTL as of 2020-09-13

---

ci/ci_check

run corev-dv ci_check tests under vsim

---

cv32/bsp/syscalls.c
cv32/sim/Common.mk
cv32/sim/core/Makefile
cv32/sim/uvmt_cv32/Makefile
cv32/tests/uvmt_cv32/test-programs/syscalls.c

I'm not sure if there's even anything left in these makefiles of the code that this copyright notice originally covered, but while it's still there, let's keep it up to date...

update a few copyright notices

---

cv32/tb/uvmt_cv32/uvmt_cv32_tb.sv

New method for synchronizing haltreq into RM

---

cv32/env/uvme_cv32/cov/uvme_debug_covg.sv
cv32/tb/uvmt_cv32/uvmt_cv32_tb_ifs.sv

adding a clocking block and rework the virtual interface on the debug… coverage to avoid Questa failure

debug covergroup fixes

---

bin/cv_regress
bin/templates/metrics.json.j2
cv32/regress/cv32_full.yaml
cv32/sim/uvmt_cv32/dsim.mk

remove index loop in lieu of metrics iterations attribute
add check for valid test name to cv_regress
use random seeds
add RNDSEED=<seed> for metrics to commands

multiple cv_regress fixes for .metrics.json

---

.metrics.json

Add cv32_interrupt regression

---

cv32/tests/programs/custom/perf_counters_instructions/perf_counters_instructions.c
cv32/tests/programs/custom/perf_counters_instructions/test.yaml

Bit # | Event Name |  
-- | -- | --
0 | CYCLES | Number of cycles
1 | INSTR | Number of instructions retired
2 | LD_STALL | Number of load use hazards
3 | JMP_STALL | Number of jump register hazards
5 | LD | Number of data interface read transactions as a result of load instructions
-- | -- | --
6 | ST | Number of data interface write transactions as a result of store instructions
7 | JUMP | Number of jumps (unconditional)
8 | BRANCH | Number of branches (conditional)
9 | BRANCH_TAKEN | Number of branches taken (conditional)
10 | COMP_INSTR | Number of compressed instructions retired

Added a basic test for Performance Counters

---

cv32/tests/programs/custom/perf_counters_instructions/perf_counters_instructions.c
cv32/tests/programs/custom/perf_counters_instructions/test.yaml

Bit # | Event Name |  
-- | -- | --
0 | CYCLES | Number of cycles
1 | INSTR | Number of instructions retired
2 | LD_STALL | Number of load use hazards
3 | JMP_STALL | Number of jump register hazards
5 | LD | Number of data interface read transactions as a result of load instructions
-- | -- | --
6 | ST | Number of data interface write transactions as a result of store instructions
7 | JUMP | Number of jumps (unconditional)
8 | BRANCH | Number of branches (conditional)
9 | BRANCH_TAKEN | Number of branches taken (conditional)
10 | COMP_INSTR | Number of compressed instructions retired

Added a basic test for Performance Counters - Event 3

---

ci/ci_check
cv32/sim/core/Makefile
cv32/sim/core/README.md
cv32/sim/uvmt_cv32/Makefile
cv32/sim/uvmt_cv32/README.md
cv32/sim/uvmt_cv32/riviera.mk
cv32/tb/uvmt_cv32/uvmt_cv32_tb_ifs.sv
lib/uvm_libs/uvml_logs/uvml_logs_constants.sv
lib/uvm_libs/uvml_sb/uvml_sb_simplex.sv

Hey!
This is a patch which added support for Riviera-PRO simulator

Riviera-PRO support

---

cv32/sim/core/Makefile
cv32/tb/core/mm_ram.sv

Hey!
In this pull request i added missing files in Makefile, also I added uvm to compilation for Riviera-PRO and `uvm_macros.svh` in `mm_ram.sv`

added uvm macros, correct Makefile

---

vendor_lib/imperas/riscv_CV32E40P_OVPsim/README.md

Additionlal section to remove confusion about how a licnese should be obtained

add missing information to obtain a license to use reference model

---

bin/templates/regress_vsif.j2
bin/vmgr/corev_uvm.flt

Create custom UVM filter file for the cv32 custom UVM report server

---

cv32/sim/uvmt_cv32/vcs.mk
cv32/sim/uvmt_cv32/vsim.mk
cv32/sim/uvmt_cv32/xrun.mk

fix the clean_all targets to remove core tests and add clean_compliance

---

cv32/env/uvme_cv32/uvme_cv32_cfg.sv
cv32/regress/cv32_debug.yaml
cv32/sim/uvmt_cv32/dsim.mk
cv32/sim/uvmt_cv32/vsim.mk
cv32/tb/core/mm_ram.sv
cv32/tb/uvmt_cv32/uvmt_cv32_step_compare.sv
cv32/tests/programs/custom/debug_test/test.yaml
lib/uvm_agents/uvma_obi/cov/uvma_obi_cov_model.sv
lib/uvm_agents/uvma_obi/seq/uvma_obi_seq_item.sv
lib/uvm_agents/uvma_obi/uvma_obi_cfg.sv
lib/uvm_agents/uvma_obi/uvma_obi_mon.sv
lib/uvm_agents/uvma_obi/uvma_obi_mon_trn.sv

enable indexed test builds (regression) of custom tests in Metrics and Questa
add a coverage model for OBI delays

make random RAM stalls default

---

cv32/sim/Common.mk
cv32/tb/core/cv32e40p_tb_wrapper.sv
cv32/tb/uvmt_cv32/uvmt_cv32_dut_wrap.sv
cv32/tests/uvmt_cv32/compliance-tests/uvmt_cv32_firmware_test.sv

Update to match the new APU port map.

Update Core TB and UVM env to match updated APU port map

---

cv32/env/uvme_cv32/cov/uvme_debug_covg.sv
cv32/tb/uvmt_cv32/uvmt_cv32_tb.sv
cv32/tb/uvmt_cv32/uvmt_cv32_tb_ifs.sv
cv32/tb/uvmt_cv32/uvmt_cv32e40p_debug_assert.sv
cv32/tests/programs/custom/debug_test/debug_test.c
cv32/tests/programs/custom/debug_test/debugger.S
cv32/tests/programs/custom/debug_test/handlers.S

Some bugfixes in cg/assertions and addition of some missing ones.
Added directed cases to debug_test to close some coverage holes.

Debug coverage and assertions update

---

cv32/tb/uvmt_cv32/uvmt_cv32_tb.sv
lib/uvm_agents/uvma_obi/uvma_obi_assert.sv
lib/uvm_agents/uvma_obi/uvma_obi_pkg.sv

Place for adding OBI covers and asserts
Binds included to attach to core OBIs

add shells for obi asserts and cover props

---

cv32/tests/programs/custom/interrupt_test/interrupt_test.c
cv32/tests/programs/custom/interrupt_test/interrupt_test.h

for coverage closure add mcause CSR writes

---

cv32/regress/cv32_full.yaml
cv32/regress/cv32_full_covg_no_pulp.yaml
cv32/tests/programs/custom/hpmcounter_hazard_test/test.yaml

As discussed in [pr 333](https://github.com/openhwgroup/core-v-verif/pull/333).

Integrate updated hpmcounter tests

---

ci/ci_check

modified hello-world.c so it would not compile.  ci_check catches that this test did not run and reports failure.

Added check that expected # of UVM tests actually ran

---

cv32/sim/Common.mk
vendor_lib/google/corev-dv/corev_asm_program_gen.sv

...plus reinstating the hack on corev-dv.

Point to latest RTL (6c858bc)

---

cv32/tb/uvmt_cv32/uvmt_cv32_tb.sv
cv32/tests/programs/corev-dv/corev_rand_interrupt_exception/corev-dv.yaml
cv32/tests/programs/corev-dv/corev_rand_interrupt_nested/corev-dv.yaml

fix core_sleep interrupt modeling

shorten some tests

---

cv32/regress/cv32_interrupt.yaml
cv32/tb/uvmt_cv32/uvmt_cv32_tb.sv
cv32/tb/uvmt_cv32/uvmt_cv32_tb_ifs.sv
cv32/tests/programs/corev-dv/corev_rand_interrupt_debug/corev-dv.yaml
vendor_lib/google/corev-dv/corev_asm_program_gen.sv

also turn down some test times on the interrupt random tests

fixes corner cases in TB with irq wakeup and debug_req wakeup from wfi

---

ci/ci_check
cv32/sim/uvmt_cv32/vcs.mk

Signed-off-by: Massimiliano Giacometti <massimiliano.giacometti@hensoldt-cyber.de>

fix in vcs.mk for riscv-dv

---

cv32/tb/uvmt_cv32/uvmt_cv32_tb.sv
lib/uvm_agents/uvma_obi/uvma_obi_assert.sv

add OBI assertions

---

cv32/tests/programs/custom/debug_test_trigger/test.yaml

disable stalls for directed trigger debug test

---

cv32/sim/Common.mk

Very simple - just an update to point to the latest RTL.   Don't need both of you review it - whoever gets to it first wins.

Point to RTL hash d922d0f

---

cv32/env/uvme_cv32/cov/uvme_rv32isa_covg.sv
cv32/env/uvme_cv32/uvme_cv32_tdefs.sv
cv32/tb/uvmt_cv32/uvmt_cv32_iss_wrap.sv
cv32/tb/uvmt_cv32/uvmt_cv32_tb_ifs.sv
cv32/tests/programs/corev-dv/corev_rand_illegal_instr_test/corev-dv.yaml
cv32/tests/programs/corev-dv/corev_rand_instr_test/corev-dv.yaml

was also computing imm as pc-relative but this was not correct

fix jalr_cg, was missing the zero bin

---

cv32/env/uvme_cv32/cov/uvme_rv32isa_covg.sv
cv32/tests/programs/corev-dv/corev_rand_instr_test/corev-dv.yaml

add functional coverage for compressed shift hint instructions with zero immediates

---

cv32/sim/Common.mk

add ability to define CFLAGS on test.yaml command line

---

cv32/regress/cv32_full_covg_no_pulp.yaml
cv32/tests/programs/custom/branch_zero/branch_zero.c
cv32/tests/programs/custom/branch_zero/test.yaml

add branch_zero test to close branch coverage with zero offsets

---

cv32/sim/uvmt_cv32/riviera.mk

Hey!
Small changes in Riviera-PRO Makefile

update Makefile for Riviera-PRO

---

cv32/env/uvme_cv32/cov/uvme_rv32isa_covg.sv
cv32/tests/programs/corev-dv/corev_rand_instr_test/corev-dv.yaml
vendor_lib/google/corev-dv/corev_misc_instr_lib.sv

inject directed xori -1 instructions in corev-dv

fix bug with xori not pseudo-op converstion for covg

---

cv32/tests/programs/corev-dv/corev_rand_interrupt_wfi_mem_stress/corev-dv.yaml
vendor_lib/google/corev-dv/corev_instr_test_pkg.sv
vendor_lib/google/corev-dv/corev_load_store_instr_lib.sv
vendor_lib/google/corev-dv/instr_lib/corev_compressed_load_store_stress_instr_stream.sv
vendor_lib/google/corev-dv/instr_lib/corev_compressed_load_store_wfi_stress_instr_stream.sv
vendor_lib/google/corev-dv/instr_lib/corev_ecall_instr_stream.sv
vendor_lib/google/corev-dv/instr_lib/corev_interrupt_csr_instr_stream.sv
vendor_lib/google/corev-dv/instr_lib/corev_interrupt_csr_wfi_instr_stream.sv
vendor_lib/google/corev-dv/instr_lib/corev_jal_wfi_instr.sv
vendor_lib/google/corev-dv/instr_lib/corev_jalr_wfi_instr.sv
vendor_lib/google/corev-dv/instr_lib/corev_nop_instr.sv
vendor_lib/google/corev-dv/instr_lib/corev_xori_not_instr.sv

add wfis directly to compressed lw sw stream to enhance coverage

---

cv32/sim/uvmt_cv32/riviera.mk

Hey!
I added `CFG_COMPILE_FLAGS` to `vlog`.

minor fix in makefile

---

cv32/tb/uvmt_cv32/uvmt_cv32e40p_debug_assert.sv

All assertions in uvmt_cv32e40p_debug_assert.sv now pass formal verification.

Updated assertions to pass formal verification

---

cv32/tb/uvmt_cv32/uvmt_cv32_tb.sv
cv32/tests/programs/custom/cv32e40p_readonly_csr_access_test/cv32e40p_readonly_csr_access_test.S
cv32/tests/programs/custom/isa_fcov_holes/isa_fcov_holes.S

Hi @strichmo, it turns out that Greg is on vacation so I took the load/store coverage holes.  Please do not merge this yet as I am running a regression to see if it actually _does_fill the holes.  I may need to push in a few updates in the morning.

Load store rs1 eq 0

---

cv32/sim/uvmt_cv32/README.md

remove old Cadence version warning

add Mentor version info

---

vendor_lib/google/corev-dv/corev_interrupt_csr_instr_lib.sv
vendor_lib/google/corev-dv/instr_lib/corev_interrupt_csr_instr_stream.sv

Hey!
I remove rand weights of dist

Remove rand weights of dist

---

cv32/sim/uvmt_cv32/riviera.mk

For issue #410, also I changed UVM to precompiled

Added compliance target in Riviera-PRO Makefile

---

cv32/regress/cv32_full_covg_no_pulp.yaml
cv32/sim/uvmt_cv32/README.md

typo: umvt --> uvmt

---

cv32/env/uvme_cv32/cov/uvme_rv32isa_covg.sv

fix atohex to atoi

---

cv32/env/uvme_cv32/cov/uvme_rv32isa_covg.sv
cv32/sim/uvmt_cv32/dsim.mk
cv32/tests/programs/custom/generic_exception_test/generic_exception_test.S

Relatively minor updates resulting from reviews of DV plans.

Edits per reviews against DV plans

---

docs/index.html

Final Reports --> Waivers

---

cv32/env/uvme_cv32/cov/uvme_rv32isa_covg.sv

fix a message verbosity

---

vendor_lib/imperas/RVVI.txt

Signed-off-by: eroom1966 <moore@imperas.com>

small change

---

cv32e40p/sim/core/Makefile

Clean up and update makefile for Riviera-PRO

---

cv32e40p/sim/tools/xrun/indago.tcl

Avoids errors and warning in Xcelium sims with Indago probing

fix paths for Indago waveform probing

---

MergeTest.md

Merge test

---

MergeTest.md

Signed-off-by: Robin Pedersen <Robin.Pedersen@silabs.com>

append mergetest

---

MergeTest.md

promise of cookies

---

MergeTest.md

Edit MergeTest.md

---

MergeTest.md

Testing that my PR approval will generate a Metrics CI email

testing merge and email from Metrics

---

.metrics.json

fixes Metrics ci_check issue introduced by CV_RESULTS PR

add DSIM_RESULTS to align compile and run directories for corev-dv

---

.metrics.json
bin/cv_regress
bin/templates/metrics.json.j2
bin/templates/regress_sh.j2
bin/templates/regress_vsif.j2

support cfg throughout cv_regress infrastructure
fix metrics.db file for sim cfg

fix RUN_INDEX for Metrics coverage

---

.metrics.json
cv32e40p/sim/TOOLCHAIN.md
cv32e40p/sim/core/README.md
cv32e40p/sim/tools/gtk/cv32e40p_core_IO.fst.gtkw
cv32e40p/sim/tools/gtk/cv32e40p_core_IO.gtkw

Hi @strichmo, this is a an easy one.  I was doing a show-and-tell yesterday and noticed a couple of out-of-date items in a couple of README (and hardcoded paths in gtkws).

README cleanup

---

cv32e40p/env/corev-dv/target/cv32e40p/riscv_core_setting.sv

Hey!
In this pull request I added `elseif _VCP` in file `riscv_core_setting.sv`.

Added _VCP in riscv_core_setting

---

mk/Common.mk

fix check for CV_CORE_PATH undefined

---

lib/uvm_agents/uvma_isacov/cov/uvma_isacov_cov_model.sv

fix memory leak by allowing transaction FIFO to continuously fill

---

cv32e40p/tests/embench/README.md
cv32e40x/tests/embench/README.md

Updated readme section on porting with .gitignore details

---

cv32e40x/sim/tools/xrun/indago_mem.tcl
cv32e40x/sim/tools/xrun/probe_mem.tcl
mk/uvmt/xrun.mk

Added WAVES_MEM option to allow tracing memories and large vectors in xrun simulations.

Added WAVES_MEM option for xrun sims

---

mk/uvmt/dvt.mk

@MikeOpenHWGroup could you please review this PR for me? This just removes an additional step when trying to work with DVT.

Clone RTL before opening DVT

---

bin/cv_regress
bin/templates/regress_vsif.j2

add parallel switch to cv_regress under VSIF for regression tuning

---

mk/Common.mk
mk/uvmt/dvt.mk

@MikeOpenHWGroup this offers the ability to pass additional arguments to DVT CLI through $(DVT_CLI_ARGS) and I also split the main rule in some smaller ones, which could be used independently to integrate other tools like Verissimo. Thanks!

Add ability to pass additional args

---

cv32e40x/tests/programs/custom/hello-world/hello-world.c

Fixed wrong error message in hello-world test

---

.metrics.json
cv32e40x/env/uvme/uvme_cv32e40x_cfg.sv
lib/uvm_agents/uvma_isacov/cov/uvma_isacov_cov_model.sv

Rolled in a couple of obvious fixes to isacov found in debug

use new dsim image to fix sva struct bug

---

cv32e40x/tb/uvmt/uvmt_cv32e40x_tb.sv

debug_test passes again with this fix.

Fixed wrong counting of issued instructions after RTL change.

---

cv32e40p/tests/programs/custom/hello-world/hello-world.c

Fixed hello world error message i cv32e40p

---

cv32e40x/env/uvme/uvme_cv32e40x_cfg.sv
cv32e40x/env/uvme/uvme_cv32e40x_core_sb.sv
cv32e40x/regress/cv32e40x_full.yaml
cv32e40x/tb/uvmt/uvmt_cv32e40x_tb.sv
cv32e40x/tb/uvmt/uvmt_cv32e40x_tb_ifs.sv
cv32e40x/tests/uvmt/base-tests/uvmt_cv32e40x_base_test.sv
lib/uvm_agents/uvma_rvfi/seq/uvma_rvfi_instr_seq_item.sv
lib/uvm_agents/uvma_rvfi/uvma_rvfi_cfg.sv
lib/uvm_agents/uvma_rvfi/uvma_rvfi_instr_mon.sv
lib/uvm_agents/uvma_rvfi/uvma_rvfi_mon_trn_logger.sv
lib/uvm_agents/uvma_rvvi_ovpsim/seq/uvma_rvvi_ovpsim_control_seq.sv
lib/uvm_agents/uvma_rvvi_ovpsim/seq/uvma_rvvi_ovpsim_control_seq_item.sv
lib/uvm_agents/uvma_rvvi_ovpsim/uvma_rvvi_ovpsim_drv.sv

add rvfi decode of halt, intr and nmi

RVFI updates for intr, nmi and debug halt

---

cv32e40x/sim/Common.mk

move rtl to latest in rvfi_integration

---

cv32e40x/docs/VerifPlans/README.md
docs/VerifPlans/VerificationPlanning101.md

update cv32e40x vplan documentation status

Vplan review procedure documentation

---

cv32e40x/sim/tools/xrun/indago.tcl

will not automatically start running simulation when starting

fix running xcelium and Indago in GUI mode with waves

---

.metrics.json
cv32e40p/regress/cv32e40p_rel_check.yaml

update dsim and restore interrupt wfi tests in rel_check

---

cv32e40x/env/uvme/uvme_cv32e40x_cfg.sv
cv32e40x/env/uvme/uvme_cv32e40x_core_sb.sv
cv32e40x/tb/uvmt/uvmt_cv32e40x_macros.sv
cv32e40x/tb/uvmt/uvmt_cv32e40x_tb.sv
cv32e40x/tests/uvmt/base-tests/uvmt_cv32e40x_base_test.sv
lib/uvm_agents/uvma_rvfi/seq/uvma_rvfi_csr_seq_item.sv
lib/uvm_agents/uvma_rvfi/seq/uvma_rvfi_instr_seq_item.sv
lib/uvm_agents/uvma_rvfi/uvma_rvfi_agent.sv
lib/uvm_agents/uvma_rvfi/uvma_rvfi_cfg.sv
lib/uvm_agents/uvma_rvfi/uvma_rvfi_cntxt.sv
lib/uvm_agents/uvma_rvfi/uvma_rvfi_csr_if.sv
lib/uvm_agents/uvma_rvfi/uvma_rvfi_instr_if.sv
lib/uvm_agents/uvma_rvfi/uvma_rvfi_instr_mon.sv
lib/uvm_agents/uvma_rvfi/uvma_rvfi_mon_trn_logger.sv
lib/uvm_agents/uvma_rvfi/uvma_rvfi_pkg.sv
lib/uvm_agents/uvma_rvvi/seq/uvma_rvvi_state_seq_item.sv
lib/uvm_agents/uvma_rvvi_ovpsim/seq/uvma_rvvi_ovpsim_control_seq.sv
lib/uvm_agents/uvma_rvvi_ovpsim/uvma_rvvi_ovpsim_drv.sv
lib/uvm_agents/uvma_rvvi_ovpsim/uvma_rvvi_ovpsim_state_mon.sv

initial integration of CSRs

---

cv32e40x/env/uvme/uvme_cv32e40x_core_sb.sv

restore mstatus in csr check

---

cv32e40x/sim/Common.mk

point to latest RVFI

---

cv32e40x/env/uvme/uvme_cv32e40x_core_sb.sv
lib/uvm_agents/uvma_rvvi/seq/uvma_rvvi_state_seq_item.sv
lib/uvm_agents/uvma_rvvi/uvma_rvvi_mon_trn_logger.sv

fix rvvi order compensation for interrupts as this is fixed in OVPSIM now

---

cv32e40x/sim/Common.mk
lib/uvm_agents/uvma_rvfi/uvma_rvfi_instr_if.sv

rvfi rvvi initial e40x

---

cv32e40x/tb/uvmt/uvmt_cv32e40x_dut_wrap.sv
cv32e40x/tests/uvmt/base-tests/uvmt_cv32e40x_base_test.sv

temp workaround for dsim randomization failure

---

cv32e40x/sim/Common.mk
cv32e40x/tb/uvmt/uvmt_cv32e40x_tb.sv

removed tracer dependecy in tb

---

cv32e40x/env/uvme/uvme_cv32e40x_core_sb.sv
cv32e40x/sim/Common.mk

temporarily disabled performance counter checking in scoreboard

---

cv32e40x/sim/Common.mk

progressed core hash

---

lib/uvm_agents/uvma_rvvi_ovpsim/uvma_rvvi_ovpsim_drv.sv
lib/uvm_agents/uvma_rvvi_ovpsim/uvma_rvvi_ovpsim_state_mon.sv

fix haltreq valid signaling with RVVI ovpsim state monitor

---

cv32e40p/sim/tools/xrun/indago.tcl
cv32e40x/env/uvme/uvme_cv32e40x_core_sb.sv
cv32e40x/tb/uvmt/uvmt_cv32e40x_tb.sv
cv32e40x/tests/programs/custom/debug_test/debug_test.c
lib/uvm_agents/uvma_rvfi/seq/uvma_rvfi_csr_seq_item.sv
lib/uvm_agents/uvma_rvfi/seq/uvma_rvfi_instr_seq_item.sv
lib/uvm_agents/uvma_rvfi/uvma_rvfi_instr_if.sv
lib/uvm_agents/uvma_rvfi/uvma_rvfi_instr_mon.sv
lib/uvm_agents/uvma_rvvi_ovpsim/seq/uvma_rvvi_ovpsim_control_seq.sv

use dcsr cause to determine external entry in RVFI

fix ebreak causing debug entry

---

.metrics.json
vendor_lib/imperas/imperas_DV_COREV/sv/imperas_CV32.sv

use the newest DSIM

---

.metrics.json

Latest dsim image

---

cv32e40x/env/uvme/uvme_cv32e40x_core_sb.sv
lib/uvm_agents/uvma_core_cntrl/uvma_core_cntrl_tdefs.sv
lib/uvm_agents/uvma_rvfi/seq/uvma_rvfi_instr_seq_item.sv
lib/uvm_agents/uvma_rvfi/uvma_rvfi_instr_mon.sv
lib/uvm_agents/uvma_rvvi_ovpsim/seq/uvma_rvvi_ovpsim_control_seq.sv
lib/uvm_agents/uvma_rvvi_ovpsim/seq/uvma_rvvi_ovpsim_control_seq_item.sv
lib/uvm_agents/uvma_rvvi_ovpsim/uvma_rvvi_ovpsim_drv.sv
lib/uvm_agents/uvma_rvvi_ovpsim/uvma_rvvi_ovpsim_state_mon.sv

various rvfi rvvi order fixes

---

cv32e40x/tests/programs/custom/debug_test_trigger/trigger_code.S

Updated debug_test_trigger to get correct timings to pass.

---

lib/uvm_agents/uvma_isacov/uvma_isacov_mon.sv

skip if the rvfi is already trapping the instruction

fix csr warning in isacov

---

bin/cv_regress
bin/templates/metrics.json.j2
bin/templates/regress_sh.j2
bin/templates/regress_vsif.j2
cv32e40x/regress/cv32e40x_ci_check.yaml
cv32e40x/regress/cv32e40x_rel_check.yaml
cv32e40x/sim/Common.mk
lib/uvm_agents/uvma_clknrst/seq/uvma_clknrst_restart_clk_seq.sv
lib/uvm_agents/uvma_clknrst/seq/uvma_clknrst_stop_clk_seq.sv
lib/uvm_agents/uvma_rvvi_ovpsim/uvma_rvvi_ovpsim_drv.sv

Comment out unstable tests from rel_check
Force 0-stalls in ci_check and rel_check
Performance fixes to remove excess randomization with clknrst

final updates for wb_controller_e40x branch

---

cv32e40x/regress/cv32e40x_ci_check.yaml
cv32e40x/regress/cv32e40x_rel_check.yaml

remove more long tests from DSIM

---

cv32e40x/regress/cv32e40x_ci_check.yaml
cv32e40x/regress/cv32e40x_rel_check.yaml
cv32e40x/sim/Common.mk

Point to latest cv32e40x to get sva fix for vsim and dsim

---

.github/workflows/triggered-metrics-regress.yml
cv32e40s/sim/Common.mk
cv32e40x/sim/Common.mk

This should pass ci_check and rel_check for all E cores in DSIM

update RTL pointers for E40X and E40S and add E40S GitHub CI actions

---

lib/corev-dv/cv32a6_csr_template.yml
lib/corev-dv/cv64a6_csr_template.yml

Added cv32a6_csr_template.yml & cv64a6_csr_template.yml
Thanks
Ranjan

added cv32a6_csr_template.yml & cv64a6_csr_template.yml

---

docs/VerifPlans/ISA/RV32/Simulation/README.md

Update status of RV32 ISA vplans

---

cv32e40x/tests/programs/custom/debug_test_trigger/debugger.S
cv32e40x/tests/programs/custom/debug_test_trigger/trigger_code.S

add another subtest to debug_test_trigger to return to the same trigger address

add a subtest that will trigger on an address and return to the same dpc

---

cv32e40p/tb/core/tb_riscv/riscv_random_interrupt_generator.sv

Hi @strichmo.  You may recall that a new OpenHW member [AMIQ EDA](https://www.dvteclipse.com/) has a SystemVerilog/UVM lint tool called **Verissimo** that they are applying to core-v-verif.   The purpose of this pull-request is to address a couple of trivial lint errors reported by Verissimo and to see if the tool automatically picks up the fix.
The changes in this PR do not impact any of the UVM environments.

Fix dead-code

---

cv32e40x/tests/cfg/pma.yaml
lib/uvm_agents/uvma_core_cntrl/uvma_core_cntrl_pma_region.sv

better pma region printing in core cntrl object

---

cv32e40x/tests/programs/custom/pma/pma.c

This PR updates the pma directed tests so that the trap handler returns consistently correct.
Previously:
Several parts of the test has been commented away, waiting for the RTL to get the new features implemented. Now we want to start re-enabling these parts but an issue was found in the test's trap handler.
When inducing pma exceptions, the trap handler didn't return correctly for all cases.
(Hadn't been tested because there was nothing to test it on.)
(The typical PC+4/2 can't be used when jumping to arbitrary locations.)
Solution:
Use function calls ("provoke()") as a way to determine where the test continues execution.
Additionally, explicitly manage the stack pointer and save/restore GPRs.
The test passes when using a 40x from one of Øystein's branches and without iss, but it should …

Pma directed, fix trap handler

---

vendor_lib/imperas/design/ram.sv
vendor_lib/imperas/imperas_DV_COREV/sv/imperas_CV32.sv

sync design files with master for better merging of model updates

---

lib/uvm_libs/uvml_hrtbt/uvml_hrtbt_constants.sv
lib/uvm_libs/uvml_hrtbt/uvml_hrtbt_macros.sv
lib/uvm_libs/uvml_hrtbt/uvml_hrtbt_mon.sv
lib/uvm_libs/uvml_hrtbt/uvml_hrtbt_pkg.flist.xsim
lib/uvm_libs/uvml_hrtbt/uvml_hrtbt_pkg.sv
lib/uvm_libs/uvml_hrtbt/uvml_hrtbt_tdefs.sv

Added performance improvements and documented the codebase.

Adding fixes to heartbeat monitor

---

lib/uvm_agents/uvma_fencei/uvma_fencei_agent.sv

fix a typo in fencei agent

---

cv32e40x/tests/uvmt/base-tests/uvmt_cv32e40x_base_test.sv
cv32e40x/tests/uvmt/base-tests/uvmt_cv32e40x_test_cfg.sv

set default heartbeat monitor enable to 1

add a test configuration switch for enabling the heartbeat monitor 

---

cv32e40x/sim/Common.mk

update e40x RTL hash

---

GitCheats.md

Test MetricCI with dummy check-in

---

bin/ci_check

ci_check: handle aborted tests and fix bug in known failure checks

---

cv32e40x/env/uvme/uvme_cv32e40x_cfg.sv
cv32e40x/env/uvme/uvme_cv32e40x_env.sv
cv32e40x/sim/Common.mk
lib/uvm_agents/uvma_rvfi/uvma_rvfi_instr_mon.sv
lib/uvm_agents/uvma_rvvi/uvma_rvvi_cfg.sv
lib/uvm_agents/uvma_rvvi/uvma_rvvi_sqr.sv
lib/uvm_agents/uvma_rvvi_ovpsim/seq/uvma_rvvi_ovpsim_obi_seq.sv
lib/uvm_agents/uvma_rvvi_ovpsim/uvma_rvvi_ovpsim_drv.sv

The directed test data_bus_error should enable testing NMI handler entry once implemented in OVPSIM

initial RVVI NMI interrupt signaling

---

bin/ci_check
cv32e40p/sim/core/Makefile
cv32e40p/sim/core/README.md
mk/Common.mk

Hi @strichmo, this addresses issue #896 for Verilator and DSIM.  I _think_ it also addresses Xcelium, but my connection to the servers I use that support Xcelium are not available this morning.

Fix up core testbench for Verilator and DSIM

---

cv32e40x/sim/Common.mk
cv32e40x/tb/uvmt/uvmt_cv32e40x_tb.sv

Changed debug assert connections to reflect signal name changes in RTL.
Updated core hash.

Cross module reference update after RTL changes

---

vendor_lib/verissimo/README.md

@MikeOpenHWGroup I'm sorry, I forgot to stage this last thing!

Update Verissimo readme paragraph

---

cv32e40x/sim/Common.mk
cv32e40x/tb/uvmt/uvmt_cv32e40x_tb.sv

Update probe after RTL change. CI clean.

---

cv32e40x/sim/Common.mk
cv32e40x/tb/uvmt/uvmt_cv32e40x_dut_wrap.sv
cv32e40x/tb/uvmt/uvmt_cv32e40x_tb.sv

Update TB after irq_ack and irq_id were made internal to the core.

---

cv32e40p/tb/core/mm_ram.sv
cv32e40p/tb/core/tb_riscv/riscv_gnt_stall.sv
cv32e40p/tb/core/tb_riscv/riscv_random_interrupt_generator.sv
cv32e40p/tb/core/tb_riscv/riscv_rvalid_stall.sv
lib/uvm_agents/uvma_obi_memory/src/comps/uvma_obi_memory_drv.sv

Verissimo lint warnings

---

mk/Common.mk
mk/uvmt/uvmt.mk

fix some clean targets for BSP and embench

---

cv32e40x/bsp/corev_uvmt.h
cv32e40x/tests/programs/custom/data_bus_error/data_bus_error.c
cv32e40x/tests/programs/custom/instr_bus_error/instr_bus_error.c
mk/Common.mk
mk/uvmt/uvmt.mk

Add test to directed test where an OBI error occurs in a prefetched instruction that is not executed.

instruction error directed test enhancement

---

cv32e40p/env/uvme/cov/uvme_debug_covg.sv
cv32e40p/env/uvme/cov/uvme_interrupt_covg.sv
cv32e40p/env/uvme/cov/uvme_rv32isa_covg.sv
cv32e40p/env/uvme/uvme_cv32e40p_env.sv
cv32e40p/tb/core/mm_ram.sv
cv32e40p/tb/core/tb_riscv/riscv_gnt_stall.sv
cv32e40p/tb/core/tb_riscv/riscv_rvalid_stall.sv
cv32e40p/tb/uvmt/uvmt_cv32e40p_step_compare.sv
cv32e40p/tests/uvmt/base-tests/uvmt_cv32e40p_base_test.sv
cv32e40p/tests/uvmt/compliance-tests/uvmt_cv32e40p_firmware_test.sv
lib/uvm_agents/uvma_clknrst/seq/uvma_clknrst_restart_clk_seq.sv
lib/uvm_agents/uvma_clknrst/seq/uvma_clknrst_stop_clk_seq.sv
lib/uvm_agents/uvma_interrupt/cov/uvma_interrupt_cov_model.sv
lib/uvm_agents/uvma_interrupt/uvma_interrupt_agent.sv
lib/uvm_agents/uvma_interrupt/uvma_interrupt_drv.sv
lib/uvm_agents/uvma_interrupt/uvma_interrupt_mon.sv
lib/uvm_agents/uvma_interrupt/uvma_interrupt_sqr.sv
lib/uvm_agents/uvma_obi_memory/src/seq/uvma_obi_memory_slv_seq.sv
lib/uvm_agents/uvma_obi_memory/src/seq/uvma_obi_memory_vp_virtual_printer_seq.sv
lib/uvm_agents/uvma_obi_memory/src/uvma_obi_memory_1p2_assert.sv
lib/uvm_agents/uvma_obi_memory/src/uvma_obi_memory_assert.sv
lib/uvm_libs/uvml_mem/uvml_mem.sv
vendor_lib/verissimo/waivers.xml

Fixed many lint errors from the Verissimo report on master branch.
This includes these issues that are owned by me:
https://github.com/openhwgroup/core-v-verif/issues/928
https://github.com/openhwgroup/core-v-verif/issues/927

Various lint fixes

---

mk/uvmt/dsim.mk
mk/uvmt/xrun.mk

set top module for comp_corev-dv in dsim and xrun

---

cv32e40p/sim/core/.gitignore
cv32e40p/sim/core/Makefile
mk/Common.mk

First step towards a full restoration of the core testbench.

Restore CV32E40P core testbench for Verilator

---

cv32e40x/env/uvme/uvme_cv32e40x_cfg.sv
cv32e40x/tests/uvmt/base-tests/uvmt_cv32e40x_base_test.sv
cv32e40x/tests/uvmt/base-tests/uvmt_cv32e40x_test_cfg.sv

Default timeout left unchanged.
Also fixes a fixme in the base test.

set test timeout from plusarg 

---

cv32e40x/env/uvme/uvme_cv32e40x_cfg.sv
lib/uvm_agents/uvma_rvfi/seq/uvma_rvfi_instr_seq_item.sv
lib/uvm_agents/uvma_rvfi/uvma_rvfi_cfg.sv
lib/uvm_agents/uvma_rvfi/uvma_rvfi_cntxt.sv
lib/uvm_agents/uvma_rvfi/uvma_rvfi_instr_mon.sv
lib/uvm_agents/uvma_rvfi/uvma_rvfi_mon_trn_logger.sv
lib/uvm_agents/uvma_rvvi/uvma_rvvi_cfg.sv
lib/uvm_agents/uvma_rvvi/uvma_rvvi_cntxt.sv
lib/uvm_agents/uvma_rvvi_ovpsim/seq/uvma_rvvi_ovpsim_control_seq.sv
lib/uvm_agents/uvma_rvvi_ovpsim/seq/uvma_rvvi_ovpsim_control_seq_item.sv
lib/uvm_agents/uvma_rvvi_ovpsim/uvma_rvvi_ovpsim_cntxt.sv
lib/uvm_agents/uvma_rvvi_ovpsim/uvma_rvvi_ovpsim_drv.sv
lib/uvm_agents/uvma_rvvi_ovpsim/uvma_rvvi_ovpsim_state_mon.sv

cleanup all signaling of the NMI faults to use RVFI CSR mcause signals in lieu of address matches

fix issue 1046

---

lib/uvm_agents/uvma_rvvi_ovpsim/uvma_rvvi_ovpsim_drv.sv

This commit addresses a regression error that is observed with the fence.i tests, where the ISS memory backdoor corrupts ISS memory due to erroneous handling of misaligned data addresses.

Fixed rvvi memory backdoor for misaligned accesses to volatile memory

---

cv32e40x/env/uvme/uvme_cv32e40x_cntxt.sv
cv32e40x/regress/cv32e40x_full.yaml
cv32e40x/tb/uvmt/uvmt_cv32e40x.flist
cv32e40x/tests/programs/custom/b_ext_test/b_ext_test.c
cv32e40x/tests/programs/custom/b_ext_test/test.yaml
lib/uvm_agents/uvma_obi_memory/src/seq/uvma_obi_memory_slv_base_seq.sv
lib/uvm_agents/uvma_rvfi/uvma_rvfi_instr_mon.sv

Cleaning out some fixmes that are completed.
Updated the b ext test to remove ifdef clang as top-of-tree gnu assemlber now supports zb*

cleanup of old fixmes

---

cv32e40x/tests/programs/custom/b_ext_test/test.yaml

Hotfix: Enable Zbs in b_ext_test compiler settings

---

cv32e40p/env/corev-dv/README.md
lib/corev-dv/README.md

Updated README to include corev-dv extension descriptions

---

cv32e40p/sim/core/README.md

Signed-off-by: Pascal Cotret <pascal.cotret@gmail.com>

fix path for cv32e40p custom simulations in the readme

---

cv32e40x/sim/ExternalRepos.mk
cv32e40x/tb/uvmt/uvmt_cv32e40x_debug_assert.sv
cv32e40x/tb/uvmt/uvmt_cv32e40x_fencei_assert.sv
cv32e40x/tb/uvmt/uvmt_cv32e40x_tb.sv
cv32e40x/tb/uvmt/uvmt_cv32e40x_tb_ifs.sv

Signed-off-by: Arjan Bink <Arjan.Bink@silabs.com>

assertion fixes

---

cv32e40x/tb/uvmt/uvmt_cv32e40x_fencei_assert.sv
cv32e40x/tb/uvmt/uvmt_cv32e40x_tb.sv

Added assertion for checking fencei flush vs write buffer full

---

cv32e40x/regress/cv32e40x_rel_check.yaml

comment out known 40x_rel_check fails to unblock merge procedure

---

cv32e40x/env/uvme/uvme_cv32e40x_cfg.sv
cv32e40x/sim/ExternalRepos.mk
cv32e40x/tb/uvmt/uvmt_cv32e40x_constants.sv
cv32e40x/tb/uvmt/uvmt_cv32e40x_dut_wrap.sv

Update B_EXT after RTL change and cv32e40x hash

---

cv32e40s/env/uvme/cov/uvme_debug_covg.sv
cv32e40s/sim/Common.mk
cv32e40s/tb/uvmt/uvmt_cv32e40s_debug_assert.sv
cv32e40s/tb/uvmt/uvmt_cv32e40s_fencei_assert.sv
cv32e40s/tb/uvmt/uvmt_cv32e40s_tb.sv
cv32e40s/tb/uvmt/uvmt_cv32e40s_tb_ifs.sv

Implements #1111 and #1102 for CV32E40X onto CV32E40S

Fix to match RTL signals

---

cva6/env/uvme/uvme_cva6_env.sv
cva6/env/uvme/uvme_cva6_pkg.sv
cva6/env/uvme/uvme_cva6_vsqr.sv
cva6/sim/Makefile
cva6/tb/uvmt/cva6_tb_wrapper.sv
cva6/tb/uvmt/uvmt_cva6.flist
cva6/tb/uvmt/uvmt_cva6_dut_wrap.sv
cva6/tb/uvmt/uvmt_cva6_tb.sv
cva6/tests/custom/cv_xif/copro_macros.h
cva6/tests/custom/cv_xif/cvxif.S
cva6/tests/testlist_cvxif.yaml
lib/uvm_agents/uvma_cvxif/README.md
lib/uvm_agents/uvma_cvxif/src/comps/uvma_cvxif_agent.sv
lib/uvm_agents/uvma_cvxif/src/comps/uvma_cvxif_drv.sv
lib/uvm_agents/uvma_cvxif/src/comps/uvma_cvxif_mon.sv
lib/uvm_agents/uvma_cvxif/src/comps/uvma_cvxif_sqr.sv
lib/uvm_agents/uvma_cvxif/src/instr_pkg.sv
lib/uvm_agents/uvma_cvxif/src/seq/uvma_cvxif_base_seq.sv
lib/uvm_agents/uvma_cvxif/src/seq/uvma_cvxif_req_item.sv
lib/uvm_agents/uvma_cvxif/src/seq/uvma_cvxif_resp_item.sv
lib/uvm_agents/uvma_cvxif/src/seq/uvma_cvxif_seq.sv
lib/uvm_agents/uvma_cvxif/src/uvma_cvxif_assert.sv
lib/uvm_agents/uvma_cvxif/src/uvma_cvxif_if.sv
lib/uvm_agents/uvma_cvxif/src/uvma_cvxif_pkg.flist
lib/uvm_agents/uvma_cvxif/src/uvma_cvxif_pkg.sv

This is a first version of the cvxif agent, a test environment is provided for the cva6 verification
- support 3 interfaces (issue_interface, commit_interface and result_interface)
- accept 2 instructions (CUS-ADD, CUS-ADD-RS3)

First version of CVXIF agent

---

cv32e40s/env/uvme/uvme_cv32e40s_cfg.sv
cv32e40s/sim/Common.mk
cv32e40s/tb/uvmt/uvmt_cv32e40s_constants.sv
cv32e40s/tb/uvmt/uvmt_cv32e40s_dut_wrap.sv

Update e40s hash and B_EXT parameter.

---

docs/CodingStyleGuidelines.md

Please let me fix my typo before someone else sees it.  ;-)

Typo: Manaul --> Manual

---

cv32e40p/sim/core/Makefile

Hotfix for core testbench

---

mk/README.md

Hi @silabs-hfegran, when I was looking for something else I noticed that the description of the Makefile structure was incomplete.  Hopefully this is a marginal improvement.

Improve discussion of Makefile structure

---

mk/uvmt/dvt.mk

Add stubs for shell env vars

---

.metrics.json
cv32e40s/env/uvme/uvme_cv32e40s_cfg.sv
cv32e40s/regress/cv32e40s_full.yaml
cv32e40s/sim/ExternalRepos.mk
cv32e40s/sim/core/Makefile
cv32e40s/tb/uvmt/uvmt_cv32e40s_constants.sv
cv32e40s/tb/uvmt/uvmt_cv32e40s_debug_assert.sv
cv32e40s/tb/uvmt/uvmt_cv32e40s_dut_wrap.sv
cv32e40s/tb/uvmt/uvmt_cv32e40s_interrupt_assert.sv
cv32e40s/tb/uvmt/uvmt_cv32e40s_tb.sv
cv32e40s/tb/uvmt/uvmt_cv32e40s_tb_ifs.sv
cv32e40x/env/uvme/uvme_cv32e40x_cfg.sv
cv32e40x/regress/cv32e40x_full.yaml
cv32e40x/sim/ExternalRepos.mk
cv32e40x/sim/core/Makefile
cv32e40x/tb/uvmt/uvmt_cv32e40x_constants.sv
cv32e40x/tb/uvmt/uvmt_cv32e40x_debug_assert.sv
cv32e40x/tb/uvmt/uvmt_cv32e40x_dut_wrap.sv
cv32e40x/tb/uvmt/uvmt_cv32e40x_interrupt_assert.sv
cv32e40x/tb/uvmt/uvmt_cv32e40x_tb.sv
cv32e40x/tb/uvmt/uvmt_cv32e40x_tb_ifs.sv
cv32e40x/tests/cfg/num_mhpmcounter_29.yaml
cv32e40x/tests/programs/custom/mhpmcounter29_csr_access_test_1/mhpmcounter29_csr_access_test_1.S
cv32e40x/tests/programs/custom/mhpmcounter29_csr_access_test_1/test.yaml
cv32e40x/tests/programs/custom/mhpmcounter29_csr_access_test_2/mhpmcounter29_csr_access_test_2.S
cv32e40x/tests/programs/custom/mhpmcounter29_csr_access_test_2/test.yaml

This PR is the merge of 40p/40x/40s into master.
Tested with "rel_check" using xcelium.
40p has the same 2 failures as [last time](https://github.com/openhwgroup/core-v-verif/pull/1133) (corev_rand_debug_single_step, twice).
40x is clean.
40s has the same two "csr_access_test" failures as last time, and sporadically fails on ["corev_rand_illegal_instr_test"](https://github.com/openhwgroup/cv32e40s/issues/113).

Silabs robin/pr/master merge 220207

---

cv32e40s/sim/ExternalRepos.mk
cv32e40s/tb/uvmt/uvmt_cv32e40s_tb.sv

Update e40s hash and probe in e40s TB after RTL change.

---

cva6/regress/linux.sh

linux.sh: Run Linux with target defiend by a variable, to be more generic

linux.sh: Run Linux only with target

---

cv32e40x/env/corev-dv/cv32e40x_csr_template.yaml
cv32e40x/env/uvme/uvma_cv32e40x_core_cntrl_drv.sv
cv32e40x/env/uvme/uvme_cv32e40x_cfg.sv
cv32e40x/env/uvme/uvme_cv32e40x_core_cntrl_if.sv
cv32e40x/sim/ExternalRepos.mk
cv32e40x/tb/core/cv32e40x_tb_wrapper.sv
cv32e40x/tb/uvmt/uvmt_cv32e40x_dut_wrap.sv
cv32e40x/tests/programs/custom/modeled_csr_por/modeled_csr_por.c
cv32e40x/tests/programs/custom/requested_csr_por/requested_csr_por.c
lib/uvm_agents/uvma_core_cntrl/uvma_core_cntrl_cfg.sv
lib/uvm_agents/uvma_rvvi_ovpsim/uvma_rvvi_ovpsim_agent.sv

Updates to support  https://github.com/openhwgroup/cv32e40x/pull/429 
silabs.com>

Updates to support changes in rtl core interface

---

cv32e40s/env/corev-dv/cv32e40s_csr_template.yaml
cv32e40s/env/uvme/uvma_cv32e40s_core_cntrl_drv.sv
cv32e40s/env/uvme/uvme_cv32e40s_cfg.sv
cv32e40s/env/uvme/uvme_cv32e40s_core_cntrl_if.sv
cv32e40s/sim/ExternalRepos.mk
cv32e40s/tb/core/cv32e40s_tb_wrapper.sv
cv32e40s/tb/uvmt/uvmt_cv32e40s_dut_wrap.sv
cv32e40s/tests/programs/custom/modeled_csr_por/modeled_csr_por.c
lib/uvm_agents/uvma_core_cntrl/uvma_core_cntrl_cfg.sv
lib/uvm_agents/uvma_rvvi_ovpsim/uvma_rvvi_ovpsim_agent.sv

Updates to match rtl interface updates

---

cva6/regress/linux.sh

linux.sh: add default value for DV_SIMULATORS

---

cv32e40s/env/uvme/uvme_cv32e40s_cfg.sv
cv32e40s/sim/ExternalRepos.mk
cv32e40s/tb/uvmt/uvmt_cv32e40s_constants.sv
cv32e40s/tb/uvmt/uvmt_cv32e40s_dut_wrap.sv
lib/uvm_agents/uvma_obi_memory/src/uvma_obi_memory_assert.sv

Updates to make tests compile with the updated rtl interface.

Removed A extension from rtl interface

---

cv32e40p/sim/uvmt/Makefile
mk/Common.mk
mk/uvmt/dvt.mk
mk/uvmt/uvmt.mk

Hi @MikeOpenHWGroup ! These are the changes needed in order to make Verissimo work again. Please let me know what you think or have better ideas.

Fix Verissimo integration

---

cv32e40p/sim/uvmt/Makefile
mk/Common.mk
mk/uvmt/dvt.mk
mk/uvmt/uvmt.mk

Same fix as proposed by @gabrielrad for the master branch.

Fix Verissimo intergation for cv32e40p/release #1198

---

cv32e40s/sim/ExternalRepos.mk
cv32e40s/tb/uvmt/uvmt_cv32e40s_dut_wrap.sv
cv32e40s/tb/uvmt/uvmt_cv32e40s_tb.sv

Fixed outdated core interfaces

---

cv32e40x/env/corev-dv/cv32e40x_instr_test_pkg.sv
cv32e40x/env/corev-dv/cv32e40x_pma_cfg.sv
cv32e40x/env/corev-dv/ldgen/cv32e40x_ldgen.sv
cv32e40x/env/uvme/uvme_cv32e40x_core_cntrl_if.sv
cv32e40x/sim/ExternalRepos.mk
cv32e40x/tb/ldgen/ldgen_tb.sv
cv32e40x/tb/uvmt/uvmt_cv32e40x_constants.sv
cv32e40x/tb/uvmt/uvmt_cv32e40x_dut_wrap.sv
cv32e40x/tb/uvmt/uvmt_cv32e40x_fencei_assert.sv
lib/mem_region_gen/pma_adapted_mem_region_gen.sv

Update e40x hash and tb after RTL renaming, pma_region_t -> pma_cfg_t

---

cv32e40s/env/corev-dv/cv32e40s_instr_test_pkg.sv
cv32e40s/env/corev-dv/cv32e40s_pma_cfg.sv
cv32e40s/env/corev-dv/ldgen/cv32e40s_ldgen.sv
cv32e40s/env/uvme/uvme_cv32e40s_core_cntrl_if.sv
cv32e40s/sim/ExternalRepos.mk
cv32e40s/tb/ldgen/ldgen_tb.sv
cv32e40s/tb/uvmt/uvmt_cv32e40s_constants.sv
cv32e40s/tb/uvmt/uvmt_cv32e40s_dut_wrap.sv
cv32e40s/tb/uvmt/uvmt_cv32e40s_fencei_assert.sv
lib/mem_region_gen/pma_adapted_mem_region_gen.sv

Update e40s hash, and rename pma_region_t to pma_cfg_t

---

cv32e40s/tb/uvmt/uvmt_cv32e40s_debug_assert.sv
cv32e40s/tb/uvmt/uvmt_cv32e40s_tb.sv
cv32e40s/tb/uvmt/uvmt_cv32e40s_tb_ifs.sv

Fixes imported from 40x, and modifications due to user mode

---

cv32e40s/tb/uvmt/uvmt_cv32e40s.flist
cv32e40s/tb/uvmt/uvmt_cv32e40s_constants.sv
cv32e40s/tb/uvmt/uvmt_cv32e40s_interrupt_assert.sv
cv32e40s/tb/uvmt/uvmt_cv32e40s_pmp_assert.sv
cv32e40s/tb/uvmt/uvmt_cv32e40s_tb.sv

Added PMP assertions

---

cv32e40p/env/uvme/uvme_cv32e40p_env.sv
lib/uvm_agents/uvma_clknrst/uvma_clknrst_agent.sv
lib/uvm_agents/uvma_debug/uvma_debug_agent.sv

Fix and/or waive a set of Verissimo Linter errors.

Cleanup more linter errors

---

.gitlab-ci.yml
.gitlab-ci/cv32.yml
.gitlab-ci/cva6.yml
.gitlab-ci/setup-ci-example/core-v-verif-cv32.yml
.gitlab-ci/setup-ci-example/core-v-verif-cva6.yml

Update for gitlab CI, add new features, fix limitations and optimize resources via new workflow.

Update Gitlab CI: new workflow, new jobs, code optimization

---

lib/uvm_agents/uvma_clknrst/uvma_clknrst_mon_trn_logger.sv
lib/uvm_agents/uvma_debug/uvma_debug_drv.sv
lib/uvm_agents/uvma_interrupt/uvma_interrupt_agent.sv

The previous PR (#1224) has a set of ill-formatted Verissimo waivers.  This PR fixes those.  No functional changes.

Fix Verissimo (UVM Lint) waivers

---

cv32e40x/tb/uvmt/uvmt_cv32e40x_interrupt_assert.sv

Or-ed multibit signal that was treated as single-bit

---

cv32e40x/env/corev-dv/cv32e40x_csr_template.yaml
cv32e40x/env/uvme/uvma_cv32e40x_core_cntrl_drv.sv
cv32e40x/env/uvme/uvme_cv32e40x_cfg.sv
cv32e40x/env/uvme/uvme_cv32e40x_core_cntrl_if.sv
cv32e40x/sim/ExternalRepos.mk
cv32e40x/tb/core/cv32e40x_tb_wrapper.sv
cv32e40x/tb/uvmt/uvmt_cv32e40x_dut_wrap.sv
lib/uvm_agents/uvma_core_cntrl/uvma_core_cntrl_cfg.sv
lib/uvm_agents/uvma_core_cntrl/uvma_core_cntrl_pma_region.sv
lib/uvm_agents/uvma_rvvi_ovpsim/uvma_rvvi_ovpsim_agent.sv

Signed-off-by: Arjan Bink <Arjan.Bink@silabs.com>

Fixed for addition of PMA integrity bit. Fixed for mimpid pin change

---

.gitlab-ci/cva6.yml

Gitlab CI yaml variables badly propagated on smoke gate job

Gitlab CI: post synthesis smoke job hot fix

---

.gitlab-ci/cva6.yml

Fix typo VIVALDO
Remove SyncDpRam dependency

cva6.yml: Add synthesis of 32 bits configuration

---

cv32e40p/tests/programs/custom/pulp_vectorial_add_sub/pulp_vectorial_add_sub.S
cv32e40p/tests/programs/custom/pulp_vectorial_bit_manip/pulp_vectorial_bit_manip.S

This is the same as pull-request #1243, but this time for the `cv32e40p/dev` branch.

Fix errors in cv32e40p pulp_vectorial tests for cv32e40p/dev branch

---

mk/Common.mk

Updated filename for new agent script in common makefile to match changes in v1p1

Updated filename for new agent script

---

bin/run_embench.py
cv32e40p/sim/core/Makefile
cv32e40p/sim/tools/vsim/waves.tcl
cv32e40p/tb/uvmt/uvmt_cv32e40p.flist
cv32e40p/tests/cfg/default.yaml
cv32e40p/tests/cfg/pulp.yaml
cv32e40p/tests/programs/custom/coremark/test.yaml
mk/Common.mk
mk/uvmt/vcs.mk
mk/uvmt/vsim.mk
mk/uvmt/xrun.mk

Some environment corrections and improvments.

Environment fixes

---

lib/uvm_agents/uvma_rvfi/uvma_rvfi_instr_mon.sv

#https://github.com/openhwgroup/core-v-verif/issues/1268#issue-1235352499
Signed-off-by: Zineb El Kacimi <zineb.el-kacimi@external.thalesgroup.com>

uvma_rvfi_instr_mon.sv: fix a non compliant LRM SystemVerilog code

---

.gitlab-ci/cva6.yml
cva6/regress/smoke-tests.sh
cva6/sim/cva6.py
cva6/tests/testlist_hwconfig.yaml
cva6/tests/testlist_riscv-compliance-cv32a60x.yaml
cva6/tests/testlist_riscv-tests-cv32a60x-p.yaml
cva6/tests/testlist_riscv-tests-cv32a60x-v.yaml

Create cv32a60x HW configuration
@ASintzoff @Gchauvon

Add cv32a60x config platform

---

cv32e40x/env/uvme/uvme_cv32e40x_cfg.sv
cv32e40x/sim/ExternalRepos.mk
cv32e40x/tb/uvmt/uvmt_cv32e40x_tb.sv

Updated cvverif to fix core interface changes

---

cva6/sim/Makefile

Signed-off-by: Guillaume Chauvon <guillaume.chauvon@thalesgroup.com>

Makefile: fix VERDI option

---

cv32e40x/sim/ExternalRepos.mk
cv32e40x/tests/programs/custom/illegal/illegal.c
lib/uvm_agents/uvma_rvvi_ovpsim/uvma_rvvi_ovpsim_agent.sv

Fixed illegal test as the used instruction was no longer illegal, updated core hash
Teilgard <mateilga@silabs.com>

Illegal test updated

---

cv32e40s/sim/ExternalRepos.mk

Updated core hash to fix regression timeout issues

---

cv32e40s/env/uvme/uvme_cv32e40s_core_sb.sv
cv32e40s/sim/ExternalRepos.mk
cv32e40s/tb/uvmt/uvmt_cv32e40s_tb.sv
lib/uvm_agents/uvma_rvfi/seq/uvma_rvfi_instr_seq_item.sv
lib/uvm_agents/uvma_rvfi/uvma_rvfi_constants.sv
lib/uvm_agents/uvma_rvfi/uvma_rvfi_instr_if.sv
lib/uvm_agents/uvma_rvfi/uvma_rvfi_instr_mon.sv
lib/uvm_agents/uvma_rvvi_ovpsim/seq/uvma_rvvi_ovpsim_control_seq.sv
lib/uvm_agents/uvma_rvvi_ovpsim/seq/uvma_rvvi_ovpsim_control_seq_item.sv
lib/uvm_agents/uvma_rvvi_ovpsim/uvma_rvvi_ovpsim_agent.sv
lib/uvm_agents/uvma_rvvi_ovpsim/uvma_rvvi_ovpsim_drv.sv

RVFI extension to support multiop instructions integrated

Extend rvfi multiop

---

cva6/sim/Makefile
cva6/sim/cva6.py

Makefile, cva6.py: add sim_do yaml entry option + code clean-up

---

.metrics.json

Solves the so-called [stale dedupe](https://support.metrics.ca/hc/en-us/requests/1239) issue.

New version of dsim

---

cv32e40x/env/corev-dv/cv32e40x_asm_program_gen.sv
cv32e40x/env/corev-dv/cv32e40x_pma_instr_lib.sv
cv32e40x/env/corev-dv/ldgen/cv32e40x_ldgen.sv
cv32e40x/regress/cv32e40x_pma.yaml
cv32e40x/sim/ExternalRepos.mk
lib/corev-dv/corev_asm_program_gen.sv

Implements same fixes as PR #1348 for cv32e40s

Ported regression timeout fixes from 40S to 40X

---

cv32e40s/sim/ExternalRepos.mk
cv32e40s/tb/uvmt/uvmt_cv32e40s_tb.sv

Hash update + pmp path update

---

cv32e40s/tests/programs/custom/interrupt_priv_test/helpers.S
cv32e40s/tests/programs/custom/interrupt_priv_test/interrupt_priv_test.c
cv32e40s/tests/programs/custom/interrupt_priv_test/test.yaml

Four test-cases checking privilege mode functionality between user and machine mode trap/interrupt handlers.

Interrupt test finished and passes

---

cv32e40s/tb/uvmt/uvmt_cv32e40s_support_logic.sv
cv32e40s/tb/uvmt/uvmt_cv32e40s_tb.sv
cv32e40s/tb/uvmt/uvmt_cv32e40s_tb_ifs.sv

"Fixed support logic reset and zc assert logic"

---

.gitlab-ci/cva6.yml

CI update : Support new synthesis and simulation gate flow
@yanicasa @JeanRochCoulon

.gitlab-ci/cva6.yml: Update synthesis and smoke-gate jobs

---

cv32e40x/env/uvme/uvme_cv32e40x_buserr_sb.sv
cv32e40x/env/uvme/uvme_cv32e40x_core_sb.sv
lib/uvm_agents/uvma_rvfi/seq/uvma_rvfi_instr_seq_item.sv

ton Teilgard <mateilga@silabs.com>

"changed rvfi_trap to a struct in uvm context"

---

lib/uvm_agents/uvma_isacov/cov/uvma_isacov_cov_model.sv

Isacov Agent: fix miss assign signals in cover group declaration

---

lib/uvm_agents/uvma_rvfi/uvma_rvfi_instr_mon.sv

Isacov: Fix the issue #1408

---

cv32e40s/tb/uvmt/uvmt_cv32e40s_pmp_assert.sv
cv32e40s/tests/cfg/pmp.yaml
cv32e40s/tests/programs/custom/pmp/DefaultFull.c
cv32e40s/tests/programs/custom/pmp/DefaultNone.c
cv32e40s/tests/programs/custom/pmp/MmodeOnly.c
cv32e40s/tests/programs/custom/pmp/README.md
cv32e40s/tests/programs/custom/pmp/ResetRegisters.c
cv32e40s/tests/programs/custom/pmp/TorNomatch.c
cv32e40s/tests/programs/custom/pmp/TorZero.c
cv32e40s/tests/programs/custom/pmp/helper.S
cv32e40s/tests/programs/custom/pmp/intr.c
cv32e40s/tests/programs/custom/pmp/pmp.c
cv32e40s/tests/programs/custom/pmp/pmp.h
cv32e40s/tests/programs/custom/pmp/test.yaml

Signed-off-by: Kun Zhu <Kun.Zhu@silabs.com>

Added tests for PMP

---

cv32e40s/tests/programs/custom/debug_priv_test/debug_priv_test.c
cv32e40s/tests/programs/custom/debug_priv_test/debugger.S
cv32e40s/tests/programs/custom/debug_priv_test/helpers.S
cv32e40s/tests/programs/custom/debug_priv_test/test.yaml

Suite of 6 test-cases focused on verifying correct behavior when switching between user and debug mode.

Debug privilege tests

---

lib/uvm_agents/uvma_isacov/uvma_isacov_instr.sv
lib/uvm_agents/uvma_isacov/uvma_isacov_tdefs.sv

ISACOV: Make the isacov agent more flexible for different XLEN value

---

cv32e40s/regress/cv32e40s_full.yaml
cv32e40s/tests/cfg/b_ext_abs.yaml
cv32e40s/tests/cfg/b_ext_all.yaml
cv32e40s/tests/cfg/default.yaml
cv32e40s/tests/cfg/pma_test_cfg_1.yaml
cv32e40s/tests/cfg/pma_test_cfg_2.yaml
cv32e40s/tests/cfg/pma_test_cfg_3.yaml
cv32e40s/tests/cfg/pma_test_cfg_4.yaml
cv32e40s/tests/cfg/pma_test_cfg_5.yaml
cv32e40s/tests/programs/custom/b_ext_test/test.yaml
cv32e40s/tests/programs/custom/zc_test/test.yaml
cv32e40s/tests/programs/custom/zc_test/test_gen/asm_manual_func.s
cv32e40s/tests/programs/custom/zc_test/test_gen/asm_manual_top.s
cv32e40s/tests/programs/custom/zc_test/test_gen/h_manual_top.h
cv32e40s/tests/programs/custom/zc_test/test_gen/zc_gen.py
cv32e40s/tests/programs/custom/zc_test/zc_test.S
cv32e40s/tests/programs/custom/zc_test/zc_test.c
cv32e40s/tests/programs/custom/zc_test/zc_test.h
lib/uvm_agents/uvma_rvvi_ovpsim/uvma_rvvi_ovpsim_agent.sv
mk/Common.mk

Directed test checking atomicity of zcmp instructions

Zc directed test

---

lib/uvm_agents/uvma_isacov/cov/uvma_isacov_cov_model.sv
lib/uvm_agents/uvma_isacov/uvma_isacov_tdefs.sv

ISACOV : Fix #1437 Issue

---

cv32e40s/tb/uvmt/uvmt_cv32e40s_constants.sv
cv32e40s/tb/uvmt/uvmt_cv32e40s_dut_wrap.sv
cv32e40s/tb/uvmt/uvmt_cv32e40s_tb.sv
cv32e40s/tb/uvmt/uvmt_cv32e40s_tb_ifs.sv
cv32e40s/tb/uvmt/uvmt_cv32e40s_xsecure_assert.sv

Signed-off-by: Kristine Dosvik <krdosvik@silabs.com>

CSR hardning and register file ECC assertions, and rewritten dummy freq instruction assertion

---

cv32e40s/tests/cfg/default.yaml
cv32e40s/tests/cfg/pma_test_cfg_1.yaml
cv32e40s/tests/cfg/pma_test_cfg_2.yaml
cv32e40s/tests/cfg/pma_test_cfg_3.yaml
cv32e40s/tests/cfg/pma_test_cfg_4.yaml
cv32e40s/tests/cfg/pma_test_cfg_5.yaml
cv32e40x/env/uvme/uvme_cv32e40x_cfg.sv
cv32e40x/sim/ExternalRepos.mk
cv32e40x/tb/uvmt/uvmt_cv32e40x_interrupt_assert.sv
cv32e40x/tb/uvmt/uvmt_cv32e40x_tb.sv
cv32e40x/tests/cfg/default.yaml
cv32e40x/tests/cfg/no_bitmanip.yaml
cv32e40x/tests/cfg/pma.yaml
cv32e40x/tests/cfg/pma_test_cfg_1.yaml
cv32e40x/tests/cfg/pma_test_cfg_2.yaml
cv32e40x/tests/cfg/pma_test_cfg_3.yaml
cv32e40x/tests/cfg/pma_test_cfg_4.yaml
cv32e40x/tests/cfg/pma_test_cfg_5.yaml
cv32e40x/tests/programs/custom/hello-world/hello-world.c
lib/uvm_agents/uvma_core_cntrl/uvma_core_cntrl_cfg.sv

Updates to get the new _dv interface to work with the latest core

---

.gitlab-ci/setup-ci-example/core-v-verif-cva6.yml

Gitlab-ci: Update setup-ci example

---

.gitlab-ci/cva6.yml

code coverage: add CI jobs (generated tests & report)

---

.gitlab-ci/cva6.yml

Need to wait dashboard before merge:
https://riscv-ci.pages.thales-invia.fr/dashboard/dashboard_core-v-verif.html

gitlab-ci: fix artifact location and add missing job reports

---

lib/uvm_agents/uvma_isacov/cov/uvma_isacov_cov_model.sv

Fix Issue #1456

---

lib/uvm_agents/uvma_isacov/cov/uvma_isacov_cov_model.sv

ISACOV : Re-fix issue #1442

---

cv32e40s/tests/programs/custom/b_ext_test/b_ext_test.c
cv32e40s/tests/programs/custom/csr_instructions/csr_instructions.c
cv32e40s/tests/programs/custom/debug_priv_test/debug_priv_test.c
cv32e40s/tests/programs/custom/debug_test/debug_test.c
cv32e40s/tests/programs/custom/debug_test_boot_set/debug_test_reset.c
cv32e40s/tests/programs/custom/debug_test_reset/debug_test_reset.c
cv32e40s/tests/programs/custom/debug_test_trigger/debug_test.c
cv32e40s/tests/programs/custom/dhrystone/dhrystone.c
cv32e40s/tests/programs/custom/fencei/fencei.c
cv32e40s/tests/programs/custom/fibonacci/fibonacci.c
cv32e40s/tests/programs/custom/hello-world/hello-world.c
cv32e40s/tests/programs/custom/hpmcounter_basic_nostall_test/hpmcounter_basic_nostall_test.c
cv32e40s/tests/programs/custom/hpmcounter_basic_test/hpmcounter_basic_test.c
cv32e40s/tests/programs/custom/hpmcounter_hazard_test/hpmcounter_hazard_test.c
cv32e40s/tests/programs/custom/illegal/illegal.c
cv32e40s/tests/programs/custom/instr_bus_error/instr_bus_error.c
cv32e40s/tests/programs/custom/interrupt_bootstrap/interrupt_bootstrap.c
cv32e40s/tests/programs/custom/interrupt_priv_test/interrupt_priv_test.c
cv32e40s/tests/programs/custom/interrupt_test/interrupt_test.c
cv32e40s/tests/programs/custom/misalign/misalign.c
cv32e40s/tests/programs/custom/modeled_csr_por/modeled_csr_por.c
cv32e40s/tests/programs/custom/perf_counters_instructions/perf_counters_instructions.c
cv32e40s/tests/programs/custom/pma/pma.c
cv32e40s/tests/programs/custom/pma_0reg/pma_0reg.c
cv32e40s/tests/programs/custom/pma_debug/pma_debug.c
cv32e40s/tests/programs/custom/pmp/pmp.h
cv32e40s/tests/programs/custom/privilege_test/privilege_test.c
cv32e40s/tests/programs/custom/requested_csr_por/requested_csr_por.c
cv32e40s/tests/programs/custom/xsecure_csrs/xsecure_csrs.c

Added missing stdint.h includes

---

docs/VerifStrat/source/quick_start.rst

I noticed a few items did not render correctly (e.g. the numbered lists) and while fixing these I also added a few minor edits for clarity.
Skipping CI because no code is changed.

[skip ci] Clarified and improved (?) some content

---

cv32e40s/tests/programs/custom/zc_test/zc_test.c

changed uint to unsigned int to comply with new tools

---

cv32e40s/env/uvme/uvme_cv32e40s_cfg.sv
cv32e40s/sim/ExternalRepos.mk

Updated ISS config to support Zc* extensions

---

cv32e40s/tb/uvmt/uvmt_cv32e40s_tb.sv
cv32e40s/tb/uvmt/uvmt_cv32e40s_tb_ifs.sv
cv32e40s/tb/uvmt/uvmt_cv32e40s_xsecure_assert.sv

Needed to update the PC hardening assertions to take into account multi cycled instructions and pointers. One assertion is comment out as we need to look into this assertion once more when we have decided to change rtl or not.

Pc hardening update

---

cva6/tb/core/Flist.cva6_tb

fix dm package dependency

---

cva6/sim/Makefile
cva6/sim/cva6.yaml

Use only one Flist for all configurations

---

cv32e40s/sim/ExternalRepos.mk
cv32e40s/tb/uvmt/uvmt_cv32e40s_debug_assert.sv
cv32e40s/tb/uvmt/uvmt_cv32e40s_tb.sv
cv32e40s/tb/uvmt/uvmt_cv32e40s_tb_ifs.sv

Quick fix to keep things moving for everyone else while I'm working on updating debug_assert file.

temporary fix to keep simulation functional after unstickying debug__req

---

cv32e40s/tb/uvmt/uvmt_cv32e40s_pmprvfi_assert.sv

As the title says.
Passes ci_check, as far as that is possible right now (known debug test, known fencei assert).
Formal still runnable.
Incidentally also adds a few more comments, etc.

PmpAssert - Update exception codes

---

cv32e40s/tb/uvmt/uvmt_cv32e40s_xsecure_assert.sv

Reverts openhwgroup/core-v-verif#1547

Revert "CSR hardening update, because rtl is updated"

---

cv32e40s/sim/ExternalRepos.mk
cv32e40s/tb/uvmt/uvmt_cv32e40s_debug_assert.sv
cv32e40s/tb/uvmt/uvmt_cv32e40s_tb.sv
cv32e40s/tb/uvmt/uvmt_cv32e40s_tb_ifs.sv

This file is WIP, PR now to solve the BOOT_SET issue

Updates to fix BOOT_SET disappearing and other assert updates

---

cv32e40s/fv/fv.flist
cv32e40s/tb/uvmt/uvmt_cv32e40s.flist
cv32e40s/tb/uvmt/uvmt_cv32e40s_tb_files.flist
mk/fv/fv.mk

Just the periodic sync of the formal flist.
We still have this https://github.com/openhwgroup/core-v-verif/issues/1384 ticket to properly fix it.
But I don't know how to optimally solve it...

Fv - Update Flist

---

cv32e40p/tb/uvmt/uvmt_cv32e40p.flist
mk/Common.mk
mk/uvmt/vcs.mk

https://github.com/openhwgroup/core-v-verif/pull/1574

Fix cv32e40p Makefile error

---

cv32e40s/tests/programs/custom/clic/clic.c

Clic directed test bugfix

---

cv32e40s/tb/uvmt/imperas_dv.flist

Removed obsolete imperas_dv path

---

cv32e40s/env/uvme/vseq/uvme_cv32e40s_vp_fencei_tamper_seq.sv

fencei test: fixed ISS error when ISS is explicitly disabled

---

cv32e40s/env/uvme/uvma_cv32e40s_core_cntrl_agent.sv
cv32e40s/sim/ExternalRepos.mk

Pulled in latest rtl for 40s and updated ISS config to match new tdata1 reset value.

Update to Latest 40s RTL

---

cv32e40p/bsp/Makefile
cv32e40p/sim/core/Makefile

Signed-off-by: Pascal Gouedo <pascal.gouedo@dolphin.fr>

Corrected core tb simulation directories for questa

---

cv32e40s/tb/uvmt/uvmt_cv32e40s_clic_interrupt_assert.sv
cv32e40s/tb/uvmt/uvmt_cv32e40s_imperas_dv_wrap.sv
cv32e40s/tb/uvmt/uvmt_cv32e40s_tb.sv
cv32e40s/tests/cfg/clic_default.yaml

Added missing CSR binds to imperas dv wrapper

---

cv32e40s/env/uvme/uvma_cv32e40s_core_cntrl_agent.sv
cv32e40s/tests/cfg/clic_default.yaml

CFG change for updated ISS

---

cv32e40s/sim/ExternalRepos.mk
cv32e40s/tb/uvmt/uvmt_cv32e40s_clic_interrupt_assert.sv
cv32e40s/tb/uvmt/uvmt_cv32e40s_imperas_dv_wrap.sv
cv32e40s/tb/uvmt/uvmt_cv32e40s_tb.sv
cv32e40s/tests/cfg/clic_default.yaml

Hotfix + update to latest hash

---

cv32e40x/env/uvme/vseq/uvme_cv32e40x_vp_fencei_tamper_seq.sv
cv32e40x/tb/uvmt/uvmt_cv32e40x_imperas_dv_wrap.sv

Correctly name core model
It requires the Imperas Simulator with this hash
e94875756e1ecd171be7da1c4313ceedc53ac26d

Cv32e40x dev 20230210

---

cv32e40s/regress/cv32e40s_full.yaml

This PR adds the FENCEI directed tests to the "full" regression list
Test status:
* ci_check - _(Should not be relevant for this PR)_
* full - The added tests pass in this regression.
* Formal - _(Should not be relevant for this PR)_

Fencei Directed - Add to "full" Regression

---

cv32e40x/env/uvme/uvme_cv32e40x_cntxt.sv
cv32e40x/env/uvme/uvme_cv32e40x_env.sv
cv32e40x/env/uvme/uvme_cv32e40x_vsqr.sv
cv32e40x/env/uvme/vseq/uvme_cv32e40x_vp_debug_control_seq.sv
cv32e40x/env/uvme/vseq/uvme_cv32e40x_vp_fencei_tamper_seq.sv
cv32e40x/env/uvme/vseq/uvme_cv32e40x_vp_interrupt_timer_seq.sv
cv32e40x/env/uvme/vseq/uvme_cv32e40x_vp_sig_writer_seq.sv
cv32e40x/env/uvme/vseq/uvme_cv32e40x_vp_status_flags_seq.sv
cv32e40x/sim/ExternalRepos.mk
cv32e40x/tb/uvmt/uvmt_cv32e40x.flist
cv32e40x/tb/uvmt/uvmt_cv32e40x_tb.sv
lib/uvm_agents/uvma_obi_memory/src/seq/uvma_obi_memory_slv_seq.sv
lib/uvm_agents/uvma_rvfi/seq/uvma_rvfi_instr_seq_item.sv
mk/uvmt/vsim.mk

PR updates environment to support simulations with questa and imperasDV for recent 40x core hashes

Fix questa/idv simulations with latest hash

---

cv32e40s/sim/ExternalRepos.mk
cv32e40s/tb/uvmt/uvmt_cv32e40s_clic_interrupt_assert.sv
cv32e40s/tb/uvmt/uvmt_cv32e40s_constants.sv
cv32e40s/tb/uvmt/uvmt_cv32e40s_dut_wrap.sv
cv32e40s/tb/uvmt/uvmt_cv32e40s_imperas_dv_wrap.sv
cv32e40s/tb/uvmt/uvmt_cv32e40s_rvfi_assert.sv
cv32e40s/tb/uvmt/uvmt_cv32e40s_tb.sv
cv32e40s/tb/uvmt/uvmt_cv32e40s_xsecure_assert.sv
cv32e40s/tests/cfg/clic_default.yaml
cv32e40s/tests/programs/custom/clic/clic.c

Updated core hash to latest. Changed SMCLIC to CLIC to follow latest RTL.
Mostly search-and-replace, some indentation differences may occur. If you want the indentation fixed in this PR, please let me know.

Changed SMCLIC to CLIC

---

cv32e40s/tb/uvmt/support_logic/uvmt_cv32e40s_support_logic.sv
cv32e40s/tb/uvmt/uvmt_cv32e40s_debug_assert.sv
cv32e40s/tb/uvmt/uvmt_cv32e40s_tb.sv
cv32e40s/tb/uvmt/uvmt_cv32e40s_tb_ifs.sv

These are fixes and updates originating from comments to PR #1684, which was merged before these changes made it online.

Updates to debug_asserts

---

cv32e40p/env/corev-dv/custom/isa/custom/riscv_custom_instr.sv

I added a small warning before doing the PR, and of course I made a mistake...

corrected typo

---

cv32e40s/tb/uvmt/uvmt_cv32e40s_debug_assert.sv
cv32e40s/tb/uvmt/uvmt_cv32e40s_tb.sv

Fixed the issues hit in simulation. Some issues still remain, but PRing now to support sim work.

cleared issues with clic runconfig

---

docs/VerifStrat/source/quick_start.rst

My previous MR #1696 introduced an error of format which this MR solves.

Quick Start: Add space to fix format

---

.gitlab-ci/cva6.yml
cva6/sim/cva6.py

Added a synthesis job and allow to simulate with this new config

Add new config target called cv32a6_embedded

---

cv32e40s/regress/cv32e40s_full.yaml
cv32e40s/tests/programs/custom/debug_test_0_triggers/debug_test_0_trigger.c
cv32e40s/tests/programs/custom/debug_test_0_triggers/test.yaml

Implements a debug trigger register test for NUM_DBG_TRIGGERS==0.

Debug test 0 triggers

---

cv32e40s/tests/programs/custom/debug_test_reset/debugger.S

Updated debug_test_reset test for cv32e40s register map.

Updated debug_test_reset test for cv32e40s

---

cv32e40s/tb/uvmt/uvmt_cv32e40s_imperas_dv_wrap.sv

Removed no compare on DCSR ISS comparison

---

cv32e40s/env/uvme/uvme_cv32e40s_cfg.sv
cv32e40s/env/uvme/vseq/uvme_cv32e40s_core_cntrl_fetch_toggle_seq.sv
cv32e40s/env/uvme/vseq/uvme_cv32e40s_random_debug_bootset_vseq.sv
lib/uvm_agents/uvma_debug/seq/uvma_debug_seq_item.sv

Made debug request in debug bootset sequence dependant on when the core starts fetching to ensure the request is captured.

Made debug_req aware of initial fetch delay

---

cva6/docs/verif-approvals.md

As discussed during CVA6 verification meeting, the goal of this file is to record formal approval for the different verification tasks.

cva6/docs/verif-approval: add file describing task approval process

---

cv32e40s/tb/uvmt/support_logic/uvmt_cv32e40s_support_logic.sv
cv32e40s/tb/uvmt/uvmt_cv32e40s_tb.sv
cv32e40s/tb/uvmt/uvmt_cv32e40s_tb_ifs.sv

Passes ci check.
The added assertion passes formal

add is_exception_trigger_hit in support logic

---

.gitlab-ci/scripts/report_builder.py
.gitlab-ci/scripts/report_fail.py
.gitlab-ci/scripts/report_fpga.py
.gitlab-ci/scripts/report_fpga_boot.py
.gitlab-ci/scripts/report_pass.py
.gitlab-ci/scripts/report_simu.py
.gitlab-ci/scripts/report_synth.py

This PR adds an object-oriented API to generate test reports for the dashboard.
@yanicasa

ci: refactor report generation

---

cv32e40s/tests/programs/custom/requested_csr_por/requested_csr_por.c

Fixed range of issues with the requested_csr_por test, most due to assumptions being out of date.

CSR POR test assumption update

---

cv32e40s/tests/programs/custom/data_bus_error/data_bus_error.c

Updated Data bus error test: handle user mode and clic, fix stack issues.

Data bus error test update

---

cv32e40s/tb/uvmt/uvmt_cv32e40s.flist
mk/uvmt/xrun.mk

Ref: https://github.com/openhwgroup/core-v-verif/pull/1824

fix idv flist inclusion

---

cv32e40p/env/corev-dv/custom/isa/custom/riscv_custom_instr.sv
cv32e40p/env/corev-dv/instr_lib/cv32e40p_base_instr_lib.sv
cv32e40p/env/corev-dv/instr_lib/cv32e40p_pulp_instr_lib.sv
cv32e40p/tests/programs/corev-dv/corev_sanity_instr_test/corev-dv.yaml
mk/uvmt/vsim.mk

Typo and code correction here and there. 
Added basic SIMD/MAC streams and improved base pulp instruction generation to be more flexible.

Corrections and PULP instruction generation updated

---

cv32e40s/tb/uvmt/uvmt_cv32e40s_pma_cov.sv

change iff to with as this dont generate warnings in "updated" formal, and:
1) 
and, 2)

change "iff" to "with" in cross coverage

---

lib/support/isa_support.sv
lib/uvm_agents/uvma_rvfi/uvma_rvfi_instr_if.sv

Initial work on a decoder for RV32I

Preliminary RV32I decoder & support

---

cv32e40p/sim/ExternalRepos.mk
cv32e40p/tests/programs/custom/coremark/test.yaml
cv32e40p/tests/programs/custom/matmul_32b_float/test.c
cv32e40p/tests/programs/custom/matmul_32b_int/test.c
cv32e40p/tests/programs/custom/pulp_hardware_loop/pulp_hardware_loop.S
mk/uvmt/uvmt.mk
mk/uvmt/vsim.mk

Some cleanup, restored assertions (corrected one in cv32e40p repo), new Zfinx CSR and Hwloop start/end address CSR check alignement to v1.3.1

Alignement to v1.3.1 spec.

---

cv32e40s/env/uvme/uvme_cv32e40s_cfg.sv
cv32e40s/tb/uvmt/support_logic/uvmt_cv32e40s_support_logic.sv
cv32e40s/tb/uvmt/uvmt_cv32e40s_imperas_dv_wrap.sv
cv32e40s/tb/uvmt/uvmt_cv32e40s_tb.sv
cv32e40s/tb/uvmt/uvmt_cv32e40s_tb_ifs.sv
cv32e40s/tb/uvmt/uvmt_cv32e40s_triggers_assert_cov.sv
cv32e40s/tb/uvmt/uvmt_cv32e40s_xsecure_assert/uvmt_cv32e40s_xsecure_interface_integrity_assert.sv
cv32e40s/tests/uvmt/base-tests/uvmt_cv32e40s_base_test_constants.sv
lib/uvm_agents/uvma_rvfi/uvma_rvfi_instr_if.sv

- Updates trigger assert and enviroment to new spec (important)
- fix bug in csh and csb opcode
- Add TODOs for stuff that is not yet 100% verified (I will continue looking into this, but since this PR holds environment changes, it is a good idea to merge it)
- ci check passes when not using the ISS

Update trigger asserts and general test environment to new spec

---

cva6/env/uvme/cvxif_vseq/custom_instruction.rst

Hello,
So as mention in the title, this document is a description of some custom instruction, that define to interact with the cvxif agent.

CVXIF : Add spec for custom instruction related to the cvxif agent

---

cv32e40s/tb/uvmt/imperas_dv.flist
cv32e40s/tb/uvmt/uvmt_cv32e40s_imperas_dv_wrap.sv
mk/uvmt/xrun.mk

@silabs-hfegran  additions for 0.9.0
this will require the simulator branch
ImperasDV-OpenHW/tree/b_0_9_0

0.9.0 additions

---

cv32e40s/fv/Makefile
cv32e40s/fv/README.md
cv32e40s/fv/fv.flist
cv32e40s/fv/jaspergold.tcl
cv32e40s/tests/uvmt/base-tests/uvmt_cv32e40s_base_test_pkg.sv
mk/fv/fv.mk

This PR updates the formal scripts so it can run with the latest core-v-verif code.

Formal - Sporadic Maintenance

---

cva6/sim/Makefile
cva6/sim/cva6.py
cva6/sim/cva6.yaml

This PR has the commits of PR #1603 but  breaks the branch naming convention of `cvvdev/` to make the CI work.

CVA6: Questasim support

---

cva6/regress/benchmark.sh
cva6/regress/install-cva6.sh
cva6/regress/install-riscv-compliance.sh
cva6/regress/install-riscv-dv.sh
cva6/regress/install-verilator.sh
cva6/sim/Makefile

This reverts the revert to fix the CI.
It has the content of the #1888 #1846.

CVA6: Infrastructure improvements

---

cv32e40s/bsp/handlers.S

- Fixed: u_sw_irq_handler compares mcause incorrectly when clic is used
- Fixed: replaced tabs with spaces

Updated default u_sw_irq_handler to support clic

---

bin/ci_check

Fix #1969 - use suggested module shutil instead of deprecated distutils

---

cv32e40s/tb/uvmt/uvmt_cv32e40s_clic_interrupt_assert.sv

Cleanup/fixup effort on clic assertions (w.i.p.)

Clic assertion updates

---

.gitlab-ci/scripts/report_synth.py

The CI will flag big variations in gates count (±100 gates).

ci: add synthesis checks

---

.gitlab-ci/cva6.yml

Signed-off-by: Guillaume Chauvon <guillaume.chauvon@thalesgroup.com>

[HOTFIX CI] Make all jobs requiring Spike dependents on build_tools job

---

cva6/env/uvme/cov/uvme_cvxif_covg.sv
lib/uvm_agents/uvma_cvxif/src/comps/uvma_cvxif_cov_model.sv
lib/uvm_agents/uvma_cvxif/src/obj/uvma_cvxif_cfg.sv

This is a FIX in the cvxif coverage model, to be aligned with the new spec of [custom instruction](https://github.com/openhwgroup/core-v-verif/pull/2040).

CVXIFCOV : Aligned cvxif cov with the new cvxif instr spec

---

cv32e40s/tb/uvmt/uvmt_cv32e40s_clic_interrupt_assert.sv
cv32e40s/tb/uvmt/uvmt_cv32e40s_debug_assert.sv
cv32e40s/tb/uvmt/uvmt_cv32e40s_tb.sv

These three asserts are unfinished, and are commented out to not slow down regression work. 
PR happens now, even though this code is unfinished, since I am going on vacation for three weeks, and we wish to have visibility on these asserts being unfinished.

unfinished clic asserts disabled, wip

---

cv32e40s/env/uvme/uvme_cv32e40s_cfg.sv
cv32e40s/tb/uvmt/uvmt_cv32e40s_clic_interrupt_assert.sv
cv32e40s/tests/programs/custom/clic/clic.c
cv32e40s/tests/programs/custom/clic/test.yaml
lib/uvm_agents/uvma_clic/uvma_clic_cfg.sv
lib/uvm_agents/uvma_clic/uvma_clic_drv.sv

- Added mnxti, mscratchcsw(l), mintthresh, minhv-tests to clic tests
- Fixed test issues
- Made sticky/non-sticky clic irq requests configurable

Added clic tests to cover coverage holes, fixed clic test issues

---

cv32e40p/sim/ExternalRepos.mk

PR to update the cv32e40p core hash to latest one at the time of PR

Update cv32e40p core hash

---

.gitlab-ci/cva6.yml

Due to license constraints, limit the number of synthesis jobs.

Make some synthesis CI jobs manual

---

cv32e40s/tests/programs/custom/clic/clic.c

* Added tests to check for illegal csr-instruction usage with mscratchcsw/mscratchcswl-registers

Added illegal access tests for mscratchcsw* to clic test

---

cv32e40p/tests/programs/custom/interrupt_test/interrupt_test.c

- Some printfs have been deleted
- Some printfs have been standardized

CV32E40P: Delete debug printf 

---

lib/uvm_agents/uvma_isacov/cov/uvma_isacov_cov_model.sv

ISACOV : remove rs2_toggle from c.lw cover group (fix issue #2073)

---

lib/uvm_agents/uvma_isacov/cov/uvma_isacov_cov_model.sv
lib/uvm_agents/uvma_isacov/uvma_isacov_instr.sv
lib/uvm_agents/uvma_isacov/uvma_isacov_mon.sv

Hello @silabs-robin @MikeOpenHWGroup, so this PR is related to what we discuss last week, creating an independent decoder from the disassemble of spike, there is nothing smart there just simple systemverilog functions
Please have a look and let's discuss

Decoder for some C instructions 

---

cv32e40p/tests/cfg/default.yaml
cv32e40p/tests/cfg/no_pulp.yaml
cv32e40p/tests/cfg/num_mhpmcounter_29.yaml
cv32e40p/tests/cfg/pulp.yaml
cv32e40p/tests/cfg/pulp_cluster.yaml
cv32e40p/tests/cfg/pulp_cluster_fpu.yaml
cv32e40p/tests/cfg/pulp_cluster_fpu_1cyclat.yaml
cv32e40p/tests/cfg/pulp_cluster_fpu_2cyclat.yaml
cv32e40p/tests/cfg/pulp_cluster_fpu_zfinx.yaml
cv32e40p/tests/cfg/pulp_cluster_fpu_zfinx_1cyclat.yaml
cv32e40p/tests/cfg/pulp_cluster_fpu_zfinx_2cyclat.yaml
cv32e40p/tests/cfg/pulp_fpu.yaml
cv32e40p/tests/cfg/pulp_fpu_1cyclat.yaml
cv32e40p/tests/cfg/pulp_fpu_2cyclat.yaml
cv32e40p/tests/cfg/pulp_fpu_zfinx.yaml
cv32e40p/tests/cfg/pulp_fpu_zfinx_1cyclat.yaml
cv32e40p/tests/cfg/pulp_fpu_zfinx_2cyclat.yaml
cv32e40p/tests/programs/custom/hello-world/hello-world.c

Config yaml files adapted to new CV32E40P parameters definition.
hello-world test adapted to comply with v1 AND all v2 possibilities and made mimpid check compliant w/ cv32e40p_v1.4.0 User Manual.

Config files and hello-world test

---

cva6/regress/install-cva6.sh
cva6/regress/install-riscv-arch-test.sh

This PR will close the [issue#1919](https://github.com/openhwgroup/core-v-verif/issues/1919)

Updated riscv-arch-test suites

---

lib/uvm_agents/uvma_isacov/cov/uvma_isacov_cov_model.sv

Ignore OFLOW bins when it's disable

ISACOV : Ignore OFLOW BIN when check_overflow = 0

---

.gitlab-ci/cva6.yml
cva6/env/corev-dv/cva6_instr_gen_config.sv
cva6/env/corev-dv/cva6_instr_hazard_test.sv
cva6/env/corev-dv/cva6_instr_test_pkg.sv
cva6/env/corev-dv/cva6_reg_hazard_stream.sv
cva6/env/corev-dv/target/rv32imc/riscv_core_setting.sv
cva6/regress/dv-generated-xif-tests.sh
cva6/sim/Makefile
cva6/sim/cva6.py
cva6/sim/cva6_base_testlist.yaml
cva6/tests/custom/cv_xif/cvxif_macros.h
cva6/tests/custom/cv_xif/cvxif_s_mode.S
cva6/tests/custom/cv_xif/cvxif_u_mode.S
cva6/tests/testlist_cvxif.yaml

Hello,
This PR contain commit related to integrate cvxif tests into continuous integration :
1. Add cvxif description in the yaml file also create a shell script to generate & run it
2. Add job for generate and directed cvxif tests 
3. Modify in CVA6-DV to generate more cvxif tests as we want to cover some corner cases
4. Add directed tests in Supervisor and user mode for cvxif tests

CVXIF : Integrate cvxif tests into CI

---

cv32e40s/fv/dummy_pkg.sv
cv32e40s/fv/fv.flist
cv32e40s/fv/jaspergold.tcl
cv32e40s/tb/uvmt/uvmt_cv32e40s_interrupt_assert.sv
cv32e40s/tb/uvmt/uvmt_cv32e40s_xsecure_assert/uvmt_cv32e40s_xsecure_interface_integrity_assert.sv

This PR repairs formal again. _(Plus fixes for some warnings.)_
Test status:
* ci_check - Pass
* (Except pma2 rand instr test hasn't finished yet).
* Cvverif formal - Runable
* Internal formal - Runable

40s Formal - Maintenance

---

.gitlab-ci/scripts/report_synth.py

The ±100 gates becomes ±300 gates

ci: widens the validity window of gate count

---

cv32e40s/tb/uvmt/uvmt_cv32e40s_debug_assert.sv

* Adds covers for the case where we encounter an nmi in debug mode, drets to single step with both options for step interrupt enable

Added covers for nmi in debug followed by single stepping with stepie = 0/1

---

bin/clonetb

Updated 40x-dv hash to 653a93fc

---

cva6/tb/uvmt/cva6_tb_wrapper.sv
cva6/tb/uvmt/uvmt_cva6_dut_wrap.sv
cva6/tb/uvmt/uvmt_cva6_tb.sv
cva6/tb/uvmt/uvmt_cva6_tb_ifs.sv

Add variant into cva6 parameter

---

cv32e40s/tb/uvmt/uvmt_cv32e40s_clic_interrupt_assert.sv

This PR fixes a CEX in the mentioned assert, by recording the return address from a clic related pointer fetch and using it for comparison.
Note that the assert has not been proven to converge at the time of writing, but has been proven beyond the bound of the CEX this attempts to fix. PRing now, as the runtime for this is several days, maybe weeks.

fixed a CEX in assert a_mepc_set_correct_after_irq

---

docs/VerifStrat/source/quick_start.rst

Fixed misspelled $CORE_V_VERIF

Corrected typo in quick_start.rst

---

cv32e40s/env/uvme/uvme_cv32e40s_buserr_sb.sv

Disabled assertion that frequently gives false positives in sim, needs a rewrite

Disabled buserr ifault assertion

---

bin/clonetb

Updated cv32e40x-dv hash to latest

---

cv32e40s/tests/programs/custom/clic/clic.c

Added minhv clear to reset_interrupt_level function for robustness

---

mk/uvmt/xrun.mk

This PR facilitates getting that top-level toggle coverage.
Test status:
* Hello world - Compiles and passes without new warnings.
* ci_check - Only fails on "clic" test.
* Formal - N/A.

Toggle Coverage

---

cv32e20/bsp/handlers.S
cv32e20/bsp/vectors.S
cv32e20/sim/ExternalRepos.mk
cv32e20/sim/tools/xrun/probe.tcl
cv32e20/tb/uvmt/uvmt_cv32e20_dut_wrap.sv
cv32e20/tb/uvmt/uvmt_cv32e20_imperas_dv_wrap.sv
cv32e20/tests/cfg/default.yaml
cv32e20/tests/programs/custom/hello-world/hello-world.c
cv32e20/tests/programs/custom/interrupt_test/interrupt_test.c
cv32e20/tests/programs/custom/interrupt_test/interrupt_test.h

fixing MIE wiring and updating to hash 9e0615b to get newest interrupt config.

fixing Interrupt wiring, imperas wiring, and updating to hash 9e0615b

---

lib/uvm_agents/uvma_obi_memory/src/obj/uvma_obi_memory_cfg.sv
lib/uvm_agents/uvma_obi_memory/src/seq/uvma_obi_memory_slv_base_seq.sv
lib/uvm_agents/uvma_pma/src/comps/uvma_pma_sb.sv

1) Add exokay obi behavior
2) Out comment atomic uvm error
ci check: passes 
formal: compiles
This PR is connected to: https://github.com/openhwgroup/cv32e40x-dv/pull/49
Touching UVM code. I think what I have done is correct, but would appreciate if reviewers took a closer look.

Atomic sanity test

---

lib/isa_decoder/isa_decoder.sv
lib/isa_decoder/isa_typedefs.sv
lib/uvm_agents/uvma_isacov/uvma_isacov_mon.sv

- Added compressed csr representation to isa_decoder
- Updated isacov to use the non-translated variant (same as before)
ci_check, formal OK
(Recommend reviewing diff with "hide whitespace changes")

Added compressed csr-representation to isa decoder

---

cv32e40s/tb/uvmt/uvmt_cv32e40s_umode_assert.sv

Covers did not function properly in simulation (cov_prv_entry_u/m and cov_data_prot_equal_memact_store/load)
Cleanup
Formal + sim OK

Fixed umode covers/asserts

---

cv32e40s/sim/ExternalRepos.mk

Update to latest hash
ci_check ok

Updated 40s core hash

---

cv32e40s/tests/cfg/param_set_1.yaml

Add paramset 1

---

bin/clonetb
bin/merge.sh

This PR makes a few small tweaks to the `merge` and `clonetb` scripts.
(See in-line comments in the diff.)

Tweak Scripts -  `merge` and `clonetb`

---

lib/isa_decoder/isa_decoder.sv
lib/isa_decoder/isa_typedefs.sv
lib/uvm_agents/uvma_isacov/uvma_isacov_mon.sv

- mva01s, mvsa01 missed sreg-representaitons of GPRs, fixed

Updated disassembler to handle sreg representation of compressed regs

---

cv32e40s/bsp/bsp.h
cv32e40s/sim/ExternalRepos.mk
cv32e40s/tests/programs/custom/clic/clic.c
cv32e40s/tests/programs/custom/zcmt_test/zcmt_test.c

This is an override of PR #2301, as Henrik is on vacation, and we need to update hash before merging. Ci_check passes, as well as both the changed tests.

Dev hf clic minhv trap test

---

ACKNOWLEDGEMENTS.md
README.md

Following a meeting with @davideschiavone (TRISTAN) and Flo, for a solution common to all projects (and alignment with TRISTAN project).

Organizing acknowledgements in the repo.

---

cv32e20/tests/programs/custom/riscv_csr/README.md
cv32e20/tests/programs/custom/riscv_csr/custom_handlers.S
cv32e20/tests/programs/custom/riscv_csr/custom_handlers.h
cv32e20/tests/programs/custom/riscv_csr/gen_csr_test.py
cv32e20/tests/programs/custom/riscv_csr/riscv_csr.c
cv32e20/tests/programs/custom/riscv_csr/riscv_csr_test_0.S

Changed copyright notice to "Intrinsix" based on feedback during an internal meeting. 
There are no functional changes in this pull request.

Copyright Comment Change

---

bin/merge.sh

merge script update

---

cv32e40p/env/uvme/uvme_cv32e40p_tdefs.sv

Remove magic number

---

cv32e40p/tb/uvmt/uvmt_cv32e40p_debug_assert.sv

Temporary resolution of #1084.

Flag duplicate properties for future FIXME

---

bin/merge.sh

Address issue https://github.com/openhwgroup/core-v-verif/issues/2134
Add check if merge is up to date
Better branch names, 
Add checks befor/after operations. 
Remove unused option

address issue 2134

---

lib/uvm_agents/uvma_core_cntrl/uvma_core_cntrl_cfg.sv
lib/uvm_agents/uvma_isacov/cov/uvma_isacov_cov_model.sv
lib/uvm_agents/uvma_isacov/uvma_isacov_instr.sv
lib/uvm_agents/uvma_isacov/uvma_isacov_macros.sv
lib/uvm_agents/uvma_isacov/uvma_isacov_mon.sv
lib/uvm_agents/uvma_isacov/uvma_isacov_tdefs.sv

This MR add to ISACOV the ZCB extension

Add ZCB extension to ISACOV

---

lib/uvm_agents/uvma_obi_memory/src/comps/uvma_obi_memory_cov_model.sv

As per a request from BeeNee.Lim@dolphin.fr

Update cv32e40p/dev OBI Fcov to match master

---

lib/uvm_agents/uvma_isacov/cov/uvma_isacov_cov_model.sv
lib/uvm_agents/uvma_isacov/uvma_isacov_instr.sv
lib/uvm_agents/uvma_isacov/uvma_isacov_mon.sv

Hello, 
This MR Related to :
1. Remove in spike-dasm CSR pseudo-code
2. Fix Decode ZB* & fence_i
3. Complete Zb* implementation in ISACOV
4. Ignore UNKNOWN_GROUP from coverage
5. Fix issue #2137

ISACOV : Update Zb* implementation & Fix issues

---

lib/uvm_agents/uvma_axi5/src/comps/uvma_axi_amo_synchronizer.sv
lib/uvm_agents/uvma_axi5/src/seq/uvma_axi_slv_seq.sv

Modify the axi agent to support r_ready and b_ready delays for unordered transactions.

Modify axi agent to support r_ready and b_ready delay

---

bin/illegal_instr_generator_cv32e40p_v1.pl

Illegal instruction generator for CV32E40P V1

Illegal instruction generator for CV32E40P V1

---

lib/uvm_agents/uvma_rvfi/uvma_rvfi_utils.sv
vendor/patches/riscv/riscv-isa-sim/0008-implement-spike-tandem.patch
vendor/patches/riscv/riscv-isa-sim/0012-params-and-value-injection.patch
vendor/riscv/riscv-isa-sim/riscv/Proc.cc
vendor/riscv/riscv-isa-sim/riscv/Proc.h
vendor/riscv/riscv-isa-sim/riscv/Simulation.cc
vendor/riscv/riscv-isa-sim/riscv/Simulation.h
vendor/riscv/riscv-isa-sim/riscv/csrs.cc
vendor/riscv/riscv-isa-sim/riscv/csrs.h
vendor/riscv/riscv-isa-sim/riscv/csrs_ext.cc
vendor/riscv/riscv-isa-sim/riscv/csrs_ext.h
vendor/riscv/riscv-isa-sim/riscv/riscv.mk.in

* Inject values coming from RTL (cycle/h,mcycle/h)
* Add parameter to enable extension as the cv32a60x
* Add parameters to alter VS and XS behaviour

[TANDEM] New parameters and values injection

---

vendor/patches/riscv/riscv-isa-sim/0013-spike-disasm-fix-CSR-pseudo-code.patch
vendor/riscv/riscv-isa-sim/disasm/disasm.cc

This MR fix the CSR pseudo-code decode in spike-disam.

Spike-disasm : Fix CSR Pseudo code

---

vendor/patches/riscv/riscv-isa-sim/0015-spike-disasm-fix-pseudo-code.patch
vendor/riscv/riscv-isa-sim/disasm/disasm.cc

Hello this MR is a fix for SLTU and BRANCH instructions decode

Fix SLTU & BRANCH pseudo-code instructions decode

---

lib/cv_dv_utils/uvm/memory_rsp_model/axi2mem/axi2mem.svh
lib/cv_dv_utils/uvm/memory_rsp_model/memory_response_model.svh

Fixed for issues #2317 and #2377 on one cv_dv_utils module (memory_rsp_model and the axi2mem coming with this module).
Thanks

[CV_DV_UTILS]:Fixed for issues #2317 and #2377

---

lib/uvm_components/uvmc_rvfi_reference_model/rvfi_spike.sv
vendor/patches/riscv/riscv-isa-sim/0018-conditional-csr-injection.patch
vendor/riscv/riscv-isa-sim/riscv/Proc.cc
vendor/riscv/riscv-isa-sim/riscv/Proc.h

Add a parameter to activate the injection of values in CSR Counters as mcycle

[VENDOR/RISCV-ISA-SIM] Conditional CSR Counters injection

---

lib/uvm_agents/uvma_axi5/src/comps/uvma_axi_ext_synchronizer.sv

The bug occurs when the master perform more than two outstanding transaction.

Fix AXI agent bug

---

cv32e40p/env/corev-dv/instr_lib/cv32e40p_pulp_hwloop_instr_lib.sv
cv32e40p/tb/uvmt/uvmt_cv32e40p_tb_ifs.sv
cv32e40p/tests/programs/custom/zfinx_func_cov_improve_test/zfinx_func_cov_improve_test.S

1) Update to follow guideline in tb when applying assertion.
2) Fix failing test
3) Improve functional coverage

Add esle clause on assertion

---

cv32e40p/env/corev-dv/instr_lib/cv32e40p_float_instr_lib.sv

(Redo) Add store restore SP for fpu streams when load store with sp is enabled

---

lib/uvm_components/uvmc_rvfi_scoreboard/uvmc_rvfi_scoreboard_utils.sv
vendor/patches/riscv/riscv-isa-sim/0024-fix-csr-injection.patch
vendor/riscv/riscv-isa-sim/riscv/Proc.cc

- Disable intr field comparison until well specified in cve2 and cva6
- Fix CSRs injection on riscv-isa-sim

[TANDEM] Fix CSR injection

---

lib/uvm_agents/uvma_rvfi/seq/uvma_rvfi_instr_seq_item.sv
lib/uvm_agents/uvma_rvfi/uvma_rvfi_constants.sv
lib/uvm_agents/uvma_rvfi/uvma_rvfi_instr_if.sv
lib/uvm_components/uvmc_rvfi_scoreboard/uvmc_rvfi_scoreboard_utils.sv
vendor/patches/riscv/riscv-isa-sim/0024-debug-infrastructure.patch
vendor/patches/riscv/riscv-isa-sim/0025-debug-infra.patch
vendor/riscv/riscv-isa-sim/riscv/Proc.cc
vendor/riscv/riscv-isa-sim/riscv/Proc.h
vendor/riscv/riscv-isa-sim/riscv/execute.cc
vendor/riscv/riscv-isa-sim/riscv/processor.h

* rvfi_dbg: make the field compliant with cv32e40s
* Add debug injection on riscv-isa-sim

[TANDEM] Debug events injection

---

cv32e40p/env/corev-dv/cv32e40p_instr_base_test.sv
cv32e40p/env/corev-dv/cv32e40p_instr_test_pkg.sv
cv32e40p/env/corev-dv/cv32e40p_loop_instr.sv

As I did in #2439, this time it's for loop_instr...

CV32E40Pv2 another case of conflict around compress reg fixed

---

lib/uvm_agents/uvma_axi5/src/obj/uvma_axi_cntxt.sv

1. Make the declaration and create consistent with same parameter.
2. Use AXI address width as the parameter of uvml_mem_c .

Update uvml_mem_c declaration/create with parameter of AXI address width

---

lib/uvm_agents/uvma_core_cntrl/uvma_core_cntrl_cfg.sv
lib/uvm_agents/uvma_core_cntrl/uvma_core_cntrl_tdefs.sv
lib/uvm_agents/uvma_isacov/cov/uvma_isacov_cov_model.sv
lib/uvm_agents/uvma_isacov/uvma_isacov_tdefs.sv

Fix issue CVV#2484

---

lib/uvm_agents/uvma_core_cntrl/uvma_core_cntrl_cfg.sv
lib/uvm_agents/uvma_core_cntrl/uvma_core_cntrl_tdefs.sv
lib/uvm_agents/uvma_core_cntrl/uvma_core_cntrl_utils.sv
vendor/patches/riscv/riscv-isa-sim/0026-Fix-mtvec-issue-2479.patch
vendor/riscv/riscv-isa-sim/riscv/Proc.cc

This MR fix issues cvv #2479 & #2468

Fix issue #2479 #2468

---

.gitmodules
lib/uvm_components/uvmc_rvfi_reference_model/rvfi_spike.sv
lib/uvm_components/uvmc_rvfi_scoreboard/uvmc_rvfi_scoreboard_utils.sv
vendor/patches/riscv/riscv-isa-sim/0028-yaml-support.patch
vendor/riscv/riscv-isa-sim/Makefile.in
vendor/riscv/riscv-isa-sim/fesvr/fesvr.mk.in
vendor/riscv/riscv-isa-sim/riscv/Params.cc
vendor/riscv/riscv-isa-sim/riscv/Params.h
vendor/riscv/riscv-isa-sim/riscv/Proc.cc
vendor/riscv/riscv-isa-sim/riscv/Simulation.cc
vendor/riscv/riscv-isa-sim/riscv/YamlParamSetter.cc
vendor/riscv/riscv-isa-sim/riscv/YamlParamSetter.h
vendor/riscv/riscv-isa-sim/riscv/riscv.mk.in
vendor/riscv/riscv-isa-sim/riscv/riscv_dpi.cc
vendor/riscv/riscv-isa-sim/spike_main/spike.cc
vendor/riscv/riscv-isa-sim/spike_main/spike_main.mk.in

Bring Yaml support up to date with Spike evolutions.
Fix race conditions and correctness issues in yaml-cpp build.

[Spike Yaml] Update Spike Yaml infrastructure, fix yaml-cpp build issues.

---

lib/cv_dv_utils/python/tp_translator/tp_translator.py
lib/cv_dv_utils/uvm/bp_gen/bp_vif.sv
lib/cv_dv_utils/uvm/generic_agent/generic_agent.svh
lib/cv_dv_utils/uvm/generic_agent/generic_txn.svh

[cv_dv_utils generic_agent] by default it is an active agent now
[cv_dv_utils tp_trans] added a python script to create OHG verification TestPlan
[cv_dv_utils bp] added force and release task

Few enhancements on cv_dv_utils

---

lib/uvm_components/uvmc_rvfi_scoreboard/uvmc_rvfi_scoreboard_utils.sv

This was also included in another PR but I think it is better to merge it earlier

Add exit code in RVFI Yaml report

---

lib/uvm_agents/uvma_isacov/cov/uvma_isacov_cov_model.sv
lib/uvm_agents/uvma_isacov/uvma_isacov_macros.sv

Remove the workaround after fix VCS compile time issue for the **_with_** key word
the code compile using 2023 version of VCS

Fix issue cvv#1914

---

lib/uvm_agents/uvma_axi5/src/comps/uvma_axi_amo_synchronizer.sv
lib/uvm_agents/uvma_axi5/src/comps/uvma_axi_drv.sv
lib/uvm_agents/uvma_axi5/src/comps/uvma_axi_mon.sv
lib/uvm_agents/uvma_axi5/src/comps/uvma_axi_synchronizer.sv
lib/uvm_agents/uvma_axi5/src/obj/uvma_axi_cfg.sv
lib/uvm_agents/uvma_axi5/src/seq/uvma_axi_slv_seq.sv
lib/uvm_agents/uvma_axi5/src/seq/uvma_axi_transaction.sv

Add more maintainability to the memory access method.
Include the ability to support the user signal.
Improve performance by reducing the randomization of all transactions in each clock cycle when the response is not valid.

AXI Agent: Enhancement in the slave section.

---

lib/uvm_agents/uvma_cvxif/src/comps/uvma_cvxif_cov_model.sv
lib/uvm_agents/uvma_cvxif/src/comps/uvma_cvxif_drv.sv
lib/uvm_agents/uvma_cvxif/src/comps/uvma_cvxif_mon.sv
lib/uvm_agents/uvma_cvxif/src/obj/uvma_cvxif_cfg.sv
lib/uvm_agents/uvma_cvxif/src/obj/uvma_cvxif_cntxt.sv
lib/uvm_agents/uvma_cvxif/src/seq/uvma_cvxif_req_item.sv
lib/uvm_agents/uvma_cvxif/src/seq/uvma_cvxif_resp_item.sv
lib/uvm_agents/uvma_cvxif/src/uvma_cvxif_assert.sv
lib/uvm_agents/uvma_cvxif/src/uvma_cvxif_intf.sv
lib/uvm_agents/uvma_cvxif/src/uvma_cvxif_macros.sv
lib/uvm_agents/uvma_cvxif/src/uvma_cvxif_pkg.sv
lib/uvm_agents/uvma_cvxif/src/uvma_cvxif_tdefs.sv

Update cvxif uvm agent based on the new cvxif spec v1.0.0 : https://github.com/openhwgroup/core-v-xif/blob/main/docs/source/x_ext.rst

CVXIF Verif : Update UVM cvxif agent v1.0.0

---

lib/cv_dv_utils/python/sim_cmd/compile.py
lib/cv_dv_utils/python/sim_cmd/run_test.py

Hello,
I have added a first version of run_test. 
Thanks and Regards
Tanuj Khandelwal

Added a first version of run_test

---

lib/uvm_agents/uvma_isacov/cov/uvma_isacov_cov_model.sv

After a review in ISA dvplan, we found some missing items, which were added in dvplan but not yet implemented

ISACOV : Add missing coverpoints in isacov coverage model

---

lib/uvm_agents/uvma_cvxif/src/uvma_cvxif_assert.sv

Add checking of rs stability to be sure !

CVXIF ASSERT : Add assertion to check rs stability

---

lib/uvm_agents/uvma_isacov/cov/uvma_isacov_cov_model.sv

Disable fencei group from isacov cross_group when it's disabled

ISACOV : ignore fencei group when it's disabled

---

lib/cv_dv_utils/python/sim_cmd/run_test.py
lib/cv_dv_utils/uvm/generic_agent/generic_monitor.svh
lib/cv_dv_utils/uvm/memory_partition/memory_partitions_cfg.svh

Hello,
This PR contrains the fix for 
1. generic monitor: made collect resps task virtual
2. memory partition: correct random generator of addresses
Regards
Tanuj Khandelwal

Fixes for issue #2605 and #2604

---

lib/uvm_agents/uvma_isacov/cov/uvma_isacov_cov_model.sv

NO need to cover RO csr for hazard csr as it raise an exception on a write on CSR RO

ISACOV : no need to cover RO csr for csr_hazard

---

lib/uvm_agents/uvma_cvxif/src/comps/uvma_cvxif_drv.sv

covering senarios like : 
issue_valid == 0 && issue_ready == 1 && accept == 1
issue_valid == 1 && issue_ready == 0 && accept == 1

CVXIF agent : add some randomization on issue packet to cover some condition in CC

---

lib/cv_dv_utils/python/sim_cmd/compile.py
lib/cv_dv_utils/python/sim_cmd/get_cmd.py
lib/cv_dv_utils/python/sim_cmd/run_reg.py
lib/cv_dv_utils/python/sim_cmd/run_test.py

Hello,
In this PR I have added scripts to run regression 
1. run_reg.py for regression
2. get_cdm.py: Now contains all commands to compile and run simulations 
thanks and regards
Tanuj

updated script to be able to run regression

---

bin/README.md
bin/requirements.txt

This PR addresses Issue #2628.

Fix invalid version specifier for Jinja2

---

lib/cv_dv_utils/python/sim_cmd/get_cmd.py
lib/cv_dv_utils/python/sim_cmd/run_reg.py
lib/cv_dv_utils/python/sim_cmd/run_test.py

Hello,
In this pull request I have added options to generate ucdb file (questa coverage). 
Thanks and Regards
Tanuj Khandelwal

added cover ucdbfile for questa
