cv32/tb/core/dp_ram.sv
cv32/tests/core/Makefile

Modified cv32/tb/core/dp_ram.sv and cv32/tests/core/Makefile to be able to compile with xcelium and run simulations.

Changed makefile and dp_ram.sv files to compile with xcelium

---

GitCheats.txt

There are lots of cheat-sheets for Git out there, but I was asked to produce a quick-and-dirty version specifically tailored to the OpenHW Group workflow.  This is the first draft - as our workflow develops more will be added.
The file also has some useful directory and branch naming conventions.

Add OpenHW specific cheat-sheet for Git (by popular request)

---

cv32/sim/Common.mk
cv32/sim/uvmt_cv32/xrun.mk
cv32/tb/core/mm_ram.sv
cv32/tb/tb_riscv/riscv_random_stall.sv
cv32/tb/uvmt_cv32/uvmt_cv32_dut_wrap.sv
cv32/tb/uvmt_cv32/uvmt_cv32_tb.sv
cv32/tb/uvmt_cv32/uvmt_cv32_tb_ifs.sv

Hi Arjan.  This is directly related to #277.  I believe it addresses all you issues in that pull-request, plus a few other items I've been meaning to clean up.  It also updates the CV32E40P_HASH and FPNEW_HASH variables to point to the latest RTL (which Davide has indicated is good ready for verif to use).
If you approve this PR I will kill #277.

Parameter and pinout cleanup: take2

---

lib/uvm_libs/uvml_logs/uvml_logs_rs_json.sv

Hey!
This pull request is for assign enum to string. Correct way to do this is to use method name():
`The name() method returns the string representation of the given enumeration value. If the given value is not a member of the enumeration, the name() method returns the empty string`

Fix to assign enum to string

---

cv32/sim/Common.mk
cv32/tb/core/riscv_wrapper.sv
cv32/tb/core/tb_top.sv
cv32/tb/core/tb_top_verilator.sv
cv32/tb/uvmt_cv32/uvmt_cv32_dut_wrap.sv
cv32/tb/uvmt_cv32/uvmt_cv32_tb.sv

This PR brings the `uvmt_cv32` environment and `core` testbench up-to-date with the latest RTL as of 2020-04-26.

Update to latest RTL (744e507)

---

cv32/sim/Common.mk
cv32/sim/uvmt_cv32/xrun.mk
cv32/tests/core/custom/riscv_ebreak_test_0.S
cv32/tests/core/custom/user_define.h

Fixes for supporting custom .c test
Addition of riscv_ebreak_test_0.S and changes to .mk to support this.
Fixed RISCV_EXE_PREFIX ?= issue in Common.mk

Fixes for supporting custom .c test and specific riscv_ebreak_test_0.S

---

cv32/tb/uvmt_cv32/uvmt_cv32_tb_ifs.sv

Fix to remove VCS compilation error.

uvmt_cv32_tb_ifs.sv: use wire to make VCS happy. Fix #122

---

cv32/sim/uvmt_cv32/vcs.mk

VCS support for `uvmt_cv32` testbench
`riscv-tests` and `riscv-compliance-tests` passed except:
- `I-NOP-01.S`
- `I-SB-01.S`
- `I-SH-01.S`

vcs.mk: update to support VCS for uvmt_cv32 testbench

---

cv32/sim/Common.mk
cv32/tb/uvmt_cv32/uvmt_cv32_dut_wrap.sv
cv32/tb/uvmt_cv32/uvmt_cv32_step_compare.sv
cv32/tb/uvmt_cv32/uvmt_cv32_tb_ifs.sv

Hi @GTumbush.  This is an update to point to the current head of the RTL (hash 101f455de).  As expected, a couple of changes to top-level interrupt pins was required.   There are also changes to the CSRs and I am worried that this will impact the ability of the OVPsim ISS to serve as a reference model when we add verification of interrupts.
I do not yet know if we should merge in this update, but I wanted you to be aware of the implications of the latest changes to the RTL.

Update for the latest RTL (101f455de)

---

cv32/sim/uvmt_cv32/dsim.mk
vendor_lib/imperas/design/riscv_CV32E40P.ic

Hi @eroom1966.  I took an action to enable dumping of OVPsim parameters at run-time.  This PR is my attempt at that.  I also made an attempt to align the simulator debug parameters with the RTL+TB setup.  To wit;
```
--override root/cpu0/debug_mode=halt
--override root/cpu0/debug_address=0x1A110800
--override root/cpu0/dexc_address=0
```
I believe what this does is the following:
- configure the model to entry debug mode when the halt input is asserted.
- set the dm_halt_address
- set the dm_exception_address (need to set that to something that matches the TB setup).
Can you confirm that this is all correct?
Also, a couple of dumb user questions:
First, this doesn't seem to have any affect:
```
--override root/cpu0/verbose=T
```
Second, this does what you'd expect, but it shows *all* …

Add debug control to OVPsim RM

---

cv32/sim/uvmt_cv32/xrun.mk

Avoid fatal ovpsim error
Signed-off-by: Paul Zavalney <paul.zavalney@silabs.com>

fix typo in xrun.mk to bring in proper flags 

---

cv32/bsp/README.md

Hi @MikeOpenHWGroup.
I have added documentation for the BSP in `cv32/bsp/README.md`. I prefer having the readme where the code lives, but if it needs integrating with the Verification Strategy, I can help with this.
Look forward to your review.

Add README.md for CV32 Board Support Package

---

ci/README.md
ci/ci_check
cv32/sim/Common.mk
cv32/sim/uvmt_cv32/Makefile
cv32/sim/uvmt_cv32/dsim.mk
cv32/sim/uvmt_cv32/vcs.mk
cv32/sim/uvmt_cv32/vsim.mk
cv32/tb/core/riscv_wrapper.sv
cv32/tb/uvmt_cv32/uvmt_cv32_dut_wrap.sv

This PR updates the `core` testbench and `uvmt_cv32` verification environment to pick up the latest RTL as of 2020-07-07.  It also includes a few updates to ci/ci_check and various Makefiles to improve user regressions.

Latest RTL and ci_check  update

---

cv32/sim/Common.mk

otherwise elf is deleted after running test and will not be rebuilt on subsequent runs because hex file is already present in the prereq

retain elf files between runs using PRECIOUS target

---

cv32/sim/Common.mk
cv32/tests/core/custom/pulp_bit_manipulation.S
cv32/tests/core/custom/pulp_general_alu.S
cv32/tests/core/custom/pulp_immediate_branching.S
cv32/tests/core/custom/pulp_multiply_accumulate.S
cv32/tests/core/custom/pulp_vectorial_add_sub.S
cv32/tests/core/custom/pulp_vectorial_avg.S
cv32/tests/core/custom/pulp_vectorial_bit_manip.S
cv32/tests/core/custom/pulp_vectorial_bitwise.S
cv32/tests/core/custom/pulp_vectorial_comparison_1.S
cv32/tests/core/custom/pulp_vectorial_comparison_2.S
cv32/tests/core/custom/pulp_vectorial_comparison_3.S
cv32/tests/core/custom/pulp_vectorial_complex.S
cv32/tests/core/custom/pulp_vectorial_dot_product_1.S
cv32/tests/core/custom/pulp_vectorial_dot_product_2.S
cv32/tests/core/custom/pulp_vectorial_max.S
cv32/tests/core/custom/pulp_vectorial_min.S
cv32/tests/core/custom/pulp_vectorial_shift.S
cv32/tests/core/custom/pulp_vectorial_shuffle_pack.S

Added 18 tests for Xpulp instruction set. Two additional tests left out of this pull request due to test failures due to unknown causes. Of the 18 tests that were added, 3 fail due to issues in either rtl or the toolchain. Test pulp_vectorial_bit_manip fails due to toolchain issues with the pv.insert.(b/h) instructions. Test pulp_vectorial_add_sub fails due to toolchain issues with pv.add.(div2/div4/div8) and pv.sub.(div2/div4/div8). Test pulp_vectorial_complex fails due to rtl issue reported at https://github.com/openhwgroup/cv32e40p/issues/407. 
These tests add limited coverage for all Xpulp instructions with the exception of hardware looping and post-increment load/store instructions (the two tests that were not added to this pull request).
The additions to cv32/sim/Common.mk change …

added pulp tests, added capability for pulp compilation

---

cv32/tests/core/custom/pulp_post_increment_load_store.S

This adds the test pulp_post_increment_load_store.S which adds limited coverage for all post-increment load/store Xpulp instructions. After this test, there is only 1 remaining Xpulp test I have made but haven't submitted, pulp_hardware_loop.S. As a quick question, @MikeOpenHWGroup, does OpenHW want the hardware loop test? Presently exceptions are generated when any Xpulp hardware loop instructions are run, so the test hasn't been included.

Added post increment load store Xpulp test

---

cv32/tb/core/mm_ram.sv
cv32/tb/uvmt_cv32/uvmt_cv32_dut_wrap.sv

Allows software to invoke an IRQ based on timer, as specified in verification strategy documentation.
Signed-off-by: Paul Zavalney <paul.zavalney@silabs.com>

update mm_ram to drive all 32 IRQ lines

---

cv32/tb/uvmt_cv32/uvmt_cv32_tb.sv
cv32/tests/uvmt_cv32/base-tests/uvmt_cv32_base_test.sv

rewrite test pass fail logic for both riscv and directed tests

fix latching of exit value from virtual peripheral

---

cv32/bsp/README.md
cv32/bsp/handlers.S
cv32/bsp/vectors.S

Proposed additional irq handlers for the mtvec table in the BSP
Please review and give any comments or suggested changes

add explicit weak handlers for all external interrupts in cv32e40p

---

cv32/tests/core/custom/csrs_test.c

Added EM's CSR test. The test currently fails due to differences in CSR implementations between EM's RTL and the OpenHW RTL. Since it was mentioned that contribution as is was acceptable in this scenario, the test is provided as is, with minimal modifications as needed. Usage for this test that has been checked is "make custom SIMULATOR=xrun CUSTOM_PROG=csrs_test USE_ISS=YES" from directory "core-v-verif/cv32/sim/uvmt_cv32"

Added EM csr test

---

cv32/tb/uvmt_cv32/uvmt_rv32isa_covg.sv

Hi @alfredoh1234.  The RV32ISA functional coverage model (`uvmt_rv32isa_covg.sv`) is running well on the master branch so I took a few moment to look at some of the holes.   In this PR I've updated c_srai_cg to (hopefully) fix what I believe is a bug in the way the code was identifying a c.srai instruction.  With this change the coverage for c.srai increases from ~45% to 75%.
Please have a look and if you agree with my changes, approve the PR (I will do the merge), or add you comments.

Update to c_srai_cg

---

.gitignore
bin/README.md
bin/ci_check
bin/cv_regress
bin/lib/README.md
bin/lib/cv_regression.py
bin/makecv32
bin/templates/README.md
bin/templates/metrics.json.j2
bin/templates/regress_macros.j2
bin/templates/regress_sh.j2
ci/ci_check
cv32/regress/cv32_ci_check.yaml
cv32/regress/cv32_full.yaml
cv32/regress/cv32_interrupt.yaml

@MikeOpenHWGroup  We will want to have a call over this particular pull request.  I'm sure all of this is non-controversial. :-)
- Introduces CWD portability (i.e. add wrappers and make sure scripts can be run from any directory)
-- Made slight changes to ci_check for directory robustness, but no functional change
-- regression testlist YAML NOT applied to ci_check yet
- First cut of the cv_regress script which generates various output regression products (metrics json, shell, other regression tools...) from common YAML regression lists
- Initial yaml regression lists for cv32
- Introduce bin/ directory for common utilities in core-v-verif
- README markdowns provided in all new bin and template directories for utility and YAML documentation
All changes should still be backwards compatible …

initial cv_regress release

---

cv32/tests/core/custom/pulp_vectorial_complex.S

Since https://github.com/openhwgroup/cv32e40p/pull/436 isn't likely to be merged/resolved very soon, I updated the tracer in my test area temporarily to test the pv.cplxmul._ instructions and see if they worked as expected. This required the test to be updated and also revealed that my math was less than accurate for some tests. I've fixed the instruction hex values and the results that were incorrect, and the test should now pass once the tracer has been updated

Updated pulp_vectorial_complex test

---

cv32/tb/uvmt_cv32/uvmt_cv32_step_compare.sv
cv32/tb/uvmt_cv32/uvmt_cv32_tb.sv
cv32/tests/core/interrupt_test/interrupt_test.c
cv32/tests/core/interrupt_test/interrupt_test.h

restore full directed interrupt_test from old commit
fix mip deassertion issue with iss step and compare

remove hack to skip mip compares with ISS

---

vendor_lib/google/corev-dv/corev_asm_program_gen.sv
vendor_lib/google/corev-dv/corev_instr_base_test.sv
vendor_lib/google/corev-dv/corev_instr_test_pkg.sv
vendor_lib/google/corev-dv/corev_interrupt_csr_instr_lib.sv
vendor_lib/google/corev-dv/corev_report_server.sv

Fix issue of taking interrupt as test_done is entered and corrupting kernel stack
add the custom report server to riscv-dv to get more readable uvm_info messages
add CSR interrupt write streams into random instruction generator

corev-dv interrupt streams and fixes

---

cv32/tb/uvmt_cv32/uvmt_cv32e40p_interrupt_assert.sv

Fixed bug in interrupt asserts found by debug testing

add debug_req_i as wakeup condition

---

cv32/env/uvme_cv32/vseq/uvme_cv32_reset_vseq.sv
cv32/tb/uvmt_cv32/uvmt_cv32_iss_wrap.sv
cv32/tb/uvmt_cv32/uvmt_cv32_step_compare.sv
lib/uvm_agents/uvma_clknrst/uvma_clknrst_if.sv

avoid clock == x overlap with reset assertion
do not ring clocks until a stable reset cycle (1->0->1) is completed

rework clknrst_if clock and reset init behavior to match async reset strategy

---

cv32/env/uvme_cv32/cov/uvme_rv32isa_covg.sv
cv32/env/uvme_cv32/uvme_cv32_tdefs.sv
cv32/sim/Common.mk
cv32/sim/tools/xrun/indago.tcl
cv32/sim/uvmt_cv32/Makefile
cv32/tb/uvmt_cv32/uvmt_cv32_iss_wrap.sv

Add UVM warnings for unmapped instructions
Add pseudo-op conversion to ISA instructions
Fill all known holes in missing instructions from the ISS
Includes update of cv32e40p repo hash to include compressed hint signal from tracer, (required)

fix compressed instruction decoding from ISS

---

cv32/sim/uvmt_cv32/xrun.mk
cv32/tb/uvmt_cv32/uvmt_cv32_uvm_macros_inc.sv

ensure uvm_macros.svh is always sourced first in Xcelium

---

cv32/tests/core/debug_test/debugger.S
cv32/tests/core/debug_test/single_step.S

Updates the debug_test by writing DCSR.STEPIE and checking if interrupts are blocked or not during single step execution.
This PR should be merged after the RTL fix is merged:
https://github.com/openhwgroup/cv32e40p/pull/494
Signed-off-by: Paul Zavalney <paul.zavalney@silabs.com>

update debug_test to test stepie fix

---

bin/cfgyaml2make
bin/cv_regress
bin/templates/regress_sh.j2
bin/templates/regress_vsif.j2
cv32/regress/cv32_ci_check.yaml
cv32/regress/cv32_full.yaml
cv32/sim/Common.mk
cv32/sim/uvmt_cv32/Makefile
cv32/sim/uvmt_cv32/README.md
cv32/sim/uvmt_cv32/dsim.mk
cv32/sim/uvmt_cv32/vsim.mk
cv32/sim/uvmt_cv32/xrun.mk
cv32/tb/uvmt_cv32/uvmt_cv32_step_compare.sv
cv32/tb/uvmt_cv32/uvmt_cv32_tb.sv
cv32/tests/cfg/default.yaml
cv32/tests/cfg/no_pulp.yaml

Build configurations enable a user to customize compile flags for their simulation build.
It also enables user to customize an Imperas ISS IC control file (one is built for each sim run now).  
Example:
% make test TEST=hello-world CFG=no_pulp
Notes:
- configs are in cv32/tests/cfg
- YAML is used for the configuration
- There is a "default.cfg"
- README.md added here:
https://github.com/strichmo/core-v-verif/blob/strichmo/pr/build_cfg/cv32/sim/uvmt_cv32/README.md#build-configurations
- Makes assumption that a single compilation configuration per workspace
- Always dumps ISS configuration via config file.  I like the self-documenting nature of that.

add build configuration specifications

---

cv32/tb/uvmt_cv32/uvmt_cv32e40p_interrupt_assert.sv

Hey!
In this pull request I fix typo: `cv32/tb/uvmt_cv32/uvmt_cv32e40p_interrupt_assert.sv `

Typo in cv32/tb/uvmt_cv32/uvmt_cv32e40p_interrupt_assert.sv 

---

ci/ci_check

Easy, one-liner for you @strichmo.  This will add the corev-dv tests to ci_check with xrun.

XRUN now runs all ci_regression tests

---

cv32/sim/mcy/alu_div/Makefile
cv32/sim/mcy/alu_div/miter.sv
cv32/sim/mcy/alu_div/riscv_alu_div_mutated_wrapper.sv
cv32/sim/mcy/alu_div/test_eq.sh
cv32/sim/mcy/alu_div/test_sim.sh

Fixes #242.
`config.mcy` and `test_eq.sby` don't support comments and therefore cannot have license headers included.

mcy: add license headers 

---

cv32/sim/Common.mk

Hi @strichmo, as discussed here is an attempt to allow users to select their toolchain **_and_** maintain backward compatibility for Contributors that do not want/need to change:
From the comment block in `core-v-verif/cv32/sim/Common.mk`:
```
#
#
#
#
```

Add option to select Toolchain from command-line

---

cv32/sim/uvmt_cv32/xrun.mk
cv32/tb/uvmt_cv32/uvmt_cv32_tb.sv
cv32/tb/uvmt_cv32/uvmt_cv32e40p_interrupt_assert.sv
vendor_lib/google/corev-dv/corev_asm_program_gen.sv
vendor_lib/google/corev-dv/corev_instr_base_test.sv
vendor_lib/google/corev-dv/corev_instr_test_pkg.sv
vendor_lib/google/corev-dv/corev_privileged_common_seq.sv

Rewrite all interrupts and "deferint modeling" code with the ISS to work with the new interrupt controller introduced in this PR:
https://github.com/openhwgroup/cv32e40p/pull/511
These changes should regress clean against all current cv32e40p directed and random interrupt tests.
Note that the above RTL PR update to the git hash in core-v-verif must occur in conjunction with merging this PR.

interrupt testbench updates to work with new simplified interrupt controller

---

cv32/bsp/handlers.S
cv32/tests/programs/custom/generic_exception_test/general_exception_test.S
cv32/tests/programs/custom/generic_exception_test/test.yaml

The only change to the BSP was to make the exception handler weak, so that I could supplant it with my own exception handler. The test (generic_exception_test.S) tests (to a limited extent) rows 3, 6, 12, 13, 16, 23, 24, and 30 of the exception Vplan.

added basic exception test

---

cv32/sim/Common.mk
cv32/tb/uvmt_cv32/uvmt_cv32_tb_ifs.sv
cv32/tests/programs/custom/interrupt_bootstrap/interrupt_bootstrap.S
cv32/tests/programs/custom/interrupt_bootstrap/interrupt_bootstrap.c
cv32/tests/programs/custom/interrupt_bootstrap/interrupt_test.h
cv32/tests/programs/custom/interrupt_bootstrap/test.yaml
cv32/tests/programs/custom/interrupt_test/test.yaml

Very simple directed test of mtvec_addr_i.  
Also adds following:
- Adds plusarg hook to set mtvec_addr_i as a short-term fix to set pins using existing interface initial block
- Add common makefile target to allow tests with both assembly and C source.  The bootstrap test uses this to implement a different start routine to avoid BSP's setting of mtvec.

add the interrupt_bootstrap directed test to verify mtvec_addr_i pins

---

cv32/tb/uvmt_cv32/uvmt_cv32_tb.sv
cv32/tb/uvmt_cv32/uvmt_cv32_tb_ifs.sv
cv32/tb/uvmt_cv32/uvmt_cv32e40p_debug_assert.sv

Detection of [c.]ebreak instructions were not robust, [c.]ebreak directly after taken branches would lead to properties expecting exception entry. Properties were also not checking enough cycles to allow long running instructions like DIV to complete before entering exception. Ebreak test now passes again.

Fix for issue #256

---

cv32/tb/uvmt_cv32/uvmt_cv32_tb.sv
cv32/tb/uvmt_cv32/uvmt_cv32e40p_interrupt_assert.sv

all interrupt asserts now formally proven in a no pulp config
Changes should also address multiple interrupt assert failures in the debug random tests

update interrupt assertions with feedback from formal verification

---

cv32/tb/uvmt_cv32/uvmt_cv32_tb_ifs.sv
cv32/tests/cfg/default.yaml

Fixes issue with default.yaml usage.  YAML string does not support inline comments so simply moved comments out of the ovpsim: section.

fix default.yaml

---

cv32/tb/uvmt_cv32/uvmt_cv32_tb_ifs.sv

fix alignment and vector mode when bootstrapping

fix stray semicolon forcing mtvec_addr into ovpsim.ic

---

cv32/sim/uvmt_cv32/xrun.mk

Removing functional coverage from the corev-dv compilation run in the Makefile.  This caused some occasional compilation failures when running Cadence regressions.

remove xrun elab flags from comp_corev-dv target

---

cv32/tb/uvmt_cv32/uvmt_cv32_dut_wrap.sv
cv32/tests/uvmt_cv32/compliance-tests/uvmt_cv32_firmware_test.sv

Hi Greg.  You've probably forgotten, but back in May of this year you updated the `dut_wrap` module to initialize unused instruction memory which could lead to step-and-compare mismatches because the RTL and TB model 4-state values and the ISS models 2-state values.
In this PR I have slightly modified this code so that the RTL's instruction memory is _always_ initialized, even if the ISS is not used.  This resolves #263.

Initialize RTL instruction memory even when ISS not used

---

cv32/tests/programs/custom/cv32e40p_csr_access_test/cv32e40p_csr_access_test.S

Bigger version of the CSR access test.  Doesn't test the access modes of the CSRs any better, but it uses all available GPRs to do it, so it should produce a small bump in ISA Fcov.

Bigger CSR access test

---

cv32/bsp/Makefile
cv32/sim/Common.mk

Hi @strichmo, this is a high-urgency PR, please review as soon as you get a chance.
To mimic what we'll have on the MetricsCI system, I have installed the PULP toolchain at **/opt/riscv** and the [COREV toolchain](https://www.embecosm.com/resources/tool-chain-downloads/#corev) (from Embecosm) at **/opt/corev** on my local machine.  With these updates I can use the COREV variable to select the COREV toolchain for any testcase.   For example, the following does what you'd expect:
```
$ make test TEST=interrupt_test COREV=YES
```
Note that using the PULP toolchain, the `interrupt_test` test-program does not compile.
So, this all works for me locally.   I want to ensure that it doesn't break anything you have.   I'd also like to know why its necessary to pass variables explicitly to the `bsp` …

Support for multiple GCC toolchains

---

cv32/tb/uvmt_cv32/uvmt_cv32_iss_wrap.sv

Hey!
I added WA for Riviera-PRO, this WA is copy from ifdef for `DSIM`

WorkAround for Riviera-PRO, incompatible array assign

---

cv32/sim/uvmt_cv32/xrun.mk

Otherwise you can get a pile of regression failures when other users take up all of your licenses

set licqueue for Xcelium by default for running tests and corev-dv

---

cv32/sim/Common.mk
cv32/tb/uvmt_cv32/uvmt_cv32_tb.sv

Hi @silabs-oysteink and @strichmo.  Here is my attempt to update the environment to point to the latest RTL (hash a26b194).  In the past week there have been some surprisingly large updates to the RTL and this had a big impact on the `debug_cov_assert_if` in the tb.  The `inst_ret` signal in the cs_registers module is gone, but fortunately the `id_valid` and `is_decoding` signals generated in the core module are still there so I created a logically equivalent signal that you'll spot right away.
This compiles and runs a ci_check regression without issue.  However, I am not in a position to understand if that `inst_ret` signal is still doing what the debug assertions assume it is doing.  @silabs-oysteink, you'll need to drill into that.

Integrate RTL hash a26b194

---

cv32/tests/programs/custom/hpmcounter_basic_test/hpmcounter_basic_test.c

Made various fixes to the test case (that were only reported by email before). The test now also contains a part aimed at the bug from https://github.com/openhwgroup/cv32e40p/issues/540. This new addition triggers the a_minstret_count and in this case the assertion itself is wrong (has been communicated to the writer)
Signed-off-by: Arjan Bink <Arjan.Bink@silabs.com>

Fixed counter test and added test scenarios

---

cv32/tests/programs/corev-dv/corev_rand_debug_ebreak/corev-dv.yaml

Thanks @silabs-oysteink for the tip!
Note that this addition while necessary does make the test susceptible to failure from the known ISS/exception/debug request issue.

add ebreaks in general program to hit missing coverage

---

cv32/sim/Common.mk
cv32/sim/uvmt_cv32/Makefile
cv32/sim/uvmt_cv32/dsim.mk

Hi @strichmo.  This PR is in response to [cv32e40p pr #560](https://github.com/openhwgroup/cv32e40p/pull/560).  This PR removes the Makefile's cloning of fpnew, as this is now part of cv32e40p.

Update to latest RTL and remove FPNEW dependencies

---

cv32/sim/uvmt_cv32/dsim.mk
cv32/tb/core/mm_ram.sv

Changes up the randomization of the memory stalls a little bit and updates the dsim makefile to run with random seeds by default.

Improved randomization control

---

cv32/env/uvme_cv32/cov/uvme_rv32isa_covg.sv

Added covergroup instr_cg for cross of every instruction covered by every other instruction.  Individual coverpoints used to create cross are weighted with 0.  Verified with short 8-instruction test case which produced the expected 7 bins in cross coverage.
For the following instruction sequence:
Collected the following cross coverage:

Add instr x instr coverage

---

cv32/env/uvme_cv32/cov/uvme_rv32isa_covg.sv

Hi @GTumbush, this is a minor tweak to your #320.  For reasons that are not clear to me, the `per_instance` option to covergroups causes dsim generate duplicated results.  I am working that out with them, in the meantime, this kludge should ensure both xrun and dsim regressions produce good results.
I've tweaked the c.liu covergroup as I noticed it was not binning x16..x31 and had coverage for imm=0 which is not correct.

Mike ins cross

---

cv32/regress/cv32_ci_check.yaml
cv32/regress/cv32_full.yaml
cv32/regress/cv32_full_covg_no_pulp.yaml
cv32/sim/Common.mk
cv32/sim/uvmt_cv32/Makefile

...and use COREV toolchain for all tests in cv32_full_covg_no_pulp regression.

Point to latest RTL (769e00c)

---

cv32/tests/programs/custom/perf_counters_instructions/test.yaml

The `IMISS` event (cycles waiting for instruction fetches, excluding jumps and branches) routinely fails when random stalls on the instruction fetch bus are enabled.  That test will never be sophisticated enough to predict proper counting of IMISS events in the presence of stalls, so I have disabled them.
If we need to, we can split off the IMISS test into its own testcase so that the remaining perf counts can be tested in the presence of instruction fetch stalls.

No stalls on instruction fetch bus

---

cv32/sim/Common.mk

This pull request defines the default SHELL interpreter in make as /bin/bash
the standard default is /bin/sh
unfortunately ubuntu uses a symbolic link from /bin/sh -> /bin/dash
The dash shell is not compatible at running some of the interpreter commands in the Makefiles

define default SHELL interpreter

---

cv32/sim/Common.mk

Brings in core updates to improve coverage collection and closure
Locally ran with ci_check in Xcelium

point to latest core with generate block naming fixes

---

cv32/sim/Common.mk

Moving to the latest RTL
By the way: @MikeOpenHWGroup, maybe as a side effect of the previous RTL commit  (that added the names to generated blocks) the issues mentioned in https://github.com/openhwgroup/cv32e40p/issues/572 have been solved (as I had to rewrite the blocks mentioned by the dsim warnings). I have no way to check with dsim myself though.
Signed-off-by: Arjan Bink <Arjan.Bink@silabs.com>

Move to latest RTL

---

cv32/tests/programs/custom/debug_test_reset/debugger.S

Accessing csr's to fill holes in functional coverage.

Added previously unused csr instructions to debug_test_reset.

---

cv32/tests/programs/custom/load_store_rs1_zero/load_store_rs1_zero.S
cv32/tests/programs/custom/load_store_rs1_zero/test.yaml

From Steve Richmond spreadsheet cv32e40p_201115_cov_holes.xlsx
To address missing coverage created test load_store_rs1_zero which covers the following instructions with operand rs1=zero:
lw, lb, lbu, lh, lhu
sw, sb, sh
Coverage has been verified.
Test is self-checking but can still run with the RM.

New test load_store_rs1_zero covers loads and stores with rs1=zero

---

cv32/sim/Common.mk
cv32/sim/core/Makefile

Hey!
In this pull request i correct path to CORE_TEST and added core tests for Riviera-PRO:
core_tests                  = ['misalign', 'illegal', 'dhrystone', 'fibonacci', 'riscv_ebreak_test_0']

update path for core tests

---

lib/uvm_agents/uvma_obi/uvma_obi_assert.sv

Hey!
I changed this assert property to support Riviera-PRO

workaround for Riviera-PRO

---

cv32/sim/tools/gtk/cv32e40p_core_IO.gtkw
cv32/sim/uvmt_cv32/Makefile

Fix the make invocation so that there is no generation of a test signature until the test-program actually runs in the UVM environment.   Fix for #253.

Fix signature check

---

cv32/regress/cv32_full.yaml
cv32/regress/cv32_full_covg_no_pulp.yaml

Noticed that the `isa_fcov_holes` test-program was not set to use the COREV toolchain in regression, which it needs to compile properly.

isa_fcov_holes requires COREV toolchain

---

cv32/regress/cv32_full_covg_no_pulp.yaml

Added `iss: 0` to regression config.

mhpmcounter29_csr_access_test_2 cannot run with ISS

---

cv32/tests/programs/custom/hello-world/hello-world.c

Fixes 2 issues with the MISA check in hello-world.c
1) printf had no argument for format specifier %x
2) check would fail if PULP was defined.

Add argument to printf of misa check. Enhance misa check for PULP

---

.gitignore
CONTRIBUTING.md
cv32/regress/cv32_debug.yaml
cv32/tests/programs/custom/debug_test/test.yaml
cv32/tests/programs/custom/debug_test_boot_set/test.yaml
cv32/tests/programs/custom/debug_test_known_miscompares/test.yaml

This is a fix for #447.
The `test.yaml` for a couple of the directed debug tests had a TEST_INDEX post-fix in their name.  I cannot understand why, but this only affects Riviera-PRO.  This fix cleans things up and works with dsim and xrun.  In order to  test that the problem goes away using Riviera-PRO I needed to stub out the simulator, but I can confirm that the original issue reported in #447 shows up using these stubs and goes away with the update on this branch.

Remove RUN_INDEX from single tests

---

.github/workflows/metrics-regress.yml
bin/metrics-regress
bin/metrics-regress.py

Using the scripts added in this PR, a regression will be launched on the Metrics platform in response to a push or pull request operation on the master branch of the core-v-verif repository. Additional customization of this GitHub action is possible.
Signed-off-by: Aimee Sutton <aimee.sutton@metrics.ca>

Add scripts to create a GitHub action that launches a Metrics regression

---

lib/corev-dv/manifest.f
mk/uvmt/riviera.mk

Hey!
In this PR I update makefile for Riviera-PRO due issue #461.
```
make test SIMULATOR=riviera TEST=hello-world
```
works
```
$ make corev-dv CV_CORE=cv32e40p SIMULATOR=riviera
$ make gen_corev-dv test TEST=corev_rand_interrupt SIMULATOR=riviera
```
works, also I check
```
make compliance_regression RISCV_ISA=rv32imc
```
and works too

Core v verif multi, update Riviera-PRO makefile

---

bin/metrics-regress

- Better error reporting when a Metrics regression is not started
- Fixed lint errors: used value comparison operators instead of reference compare operators
- Fixed typo on line 75: GitHub references do not start with a leading /

Improvements to metrics-regress script

---

NEWS_ARCHIVE.md
README.md
cv32e40p/sim/core/Makefile
cv32e40p/sim/tools/gtk/cv32e40p_core_IO.fst.gtkw
cv32e40p/tb/core/cv32e40p_tb_wrapper.sv
mk/README.md
mk/core/core.mk

This get the core testbench working again in the new "core-v-verif multi" structure.  Tested with Verilator and dsim.

Restore CORE testbench

---

cv32e40p/tb/core/mm_ram.sv
cv32e40p/tb/core/tb_riscv/riscv_gnt_stall.sv
lib/uvm_agents/uvma_obi/uvma_obi_assert.sv

in both stall and non-stall randomization modes, add around gnt assertion for both I and D busses even if not requested
add cover property to obi assert to ensure coverage

OBI unrequested gnt coverage fix

---

mk/uvmt/riviera.mk

Hey!
In this pull request I added `$(CFG)` on path to library in simulation command

Correct path to library in riviera makefile

---

cv32e40p/env/corev-dv/cv32e40p_asm_program_gen.sv
cv32e40p/env/corev-dv/cv32e40p_privileged_common_seq.sv
cv32e40p/env/corev-dv/target/cv32e40p/riscv_core_setting.sv
cv32e40p/sim/Common.mk

Summary of changes:
- Removed jump to init_machine_mode (function location inlined
by Google, no longer needed).
- Reverted previous mret->ret change to init_machine_mode
generator function to avoid an infinite loop.
- Changed setup_mmode_reg to not enable MIE bit.
This is instead done by mret at the end of code section
by copying MPIE->MIE. (cf. riscv priv. spec.)
This prevents an infinite loop if an interrupt request is
present prior to init_machine_mode completion.
- Updated common interrupt handler jump for increased robustness
with large programs. (Ports over change from RISCV-DV
upstream).
- Added empty custom csr definitions for compatibility with
latest Riscv-dv.

Updated Riscv-dv to latest hash

---

cv32e40p/tb/core/mm_ram.sv

The magic numbers used to signify the mm_ram addresses have been made in to parameters for readability.
A cycle counter has been added to mm_ram. The motivation for this is to enable benchmarks running on the core to access and record the cycle count for a given testcase, which will be necessary for implementing EMBench and Coremark in core-v-verif.
This PR is relevant to issues #494 and #495.

Removed magic numbers for mm_ram addresses and added a cycle counter

---

cv32e40p/tb/core/mm_ram.sv

Hi @silabs-mateilga, this is my second attempt to hack `mm_ram` to run under Verilator.  Please have a look.   Thanks.

Hack mm_ram to support Verilator

---

bin/templates/metrics.json.j2
bin/templates/regress_sh.j2
cv32e40p/regress/cv32e40p_compliance.yaml
mk/uvmt/uvmt.mk

cv32e40p_compliance regression working again
functional coverage working in Metrics with compliance regression
should be able to deprecate the static_compliance regression after this PR

fix compliance issues

---

bin/run_embench.py
bin/templates/embench_test.yaml.j2
bin/yaml2make
cv32e40p/sim/Common.mk
cv32e40p/tests/.gitignore
cv32e40p/tests/embench/README.md
cv32e40p/tests/embench/config/corev32/arch.cfg
cv32e40p/tests/embench/config/corev32/boards/corev32/board.cfg
cv32e40p/tests/embench/config/corev32/boards/corev32/boardsupport.c
cv32e40p/tests/embench/config/corev32/boards/corev32/boardsupport.h
cv32e40p/tests/embench/config/corev32/chips/size/chip.cfg
cv32e40p/tests/embench/config/corev32/chips/size/chipsupport.c
cv32e40p/tests/embench/config/corev32/chips/size/chipsupport.h
cv32e40p/tests/embench/config/corev32/chips/speed/chip.cfg
cv32e40p/tests/embench/config/corev32/chips/speed/chipsupport.c
cv32e40p/tests/embench/config/corev32/chips/speed/chipsupport.h
cv32e40p/tests/embench/pylib/run_corev32.py
cv32e40p/tests/programs/embench/README.md
cv32e40p/vendor_lib/.gitignore
mk/Common.mk
mk/uvmt/riviera.mk
mk/uvmt/uvmt.mk
mk/uvmt/vcs.mk
mk/uvmt/vsim.mk
mk/uvmt/xrun.mk

Signedoff-by: Marton Teilgard <mateilga@silabs.com>
This is the deployment of EMBench support for Core-v-verif, as described in issue #495 .
The commit includes:
- EMBench integration via make environment
- The ability to build and run benchmarks for speed and size
- Option for setting target score that pass/fails the benchmark run
- Test artifacts than can be simulated through "make test"
Details can be found in the readme file:
core-v-verif/cv32e40p/tests/embench/README.md

Embench deployment to Core-v-verif for cv32e40p

---

cv32e40x/regress/cv32e40x_ci_check.yaml
cv32e40x/tb/uvmt/uvmt_cv32e40x_dut_wrap.sv

Quick fix to get debug_test to pass until we have verification of bus errors in place.

Fixes to reenable debug_test in ci_check

---

cv32e40p/sim/tools/xrun/probe.tcl

Fixes issues with tcl script that prevents xrun debugging with WAVES=1

Hotfix: xrun debug

---

cv32e40x/sim/Common.mk

Set "CV_CORE_HASH" in "cv32e40x/sim/Common.mk" to latest from 40x repo.
Relates to https://github.com/openhwgroup/core-v-verif/issues/544
Passes ci_check.
Tested with CV_CORE_PATH not set.

update the cv32e40x hash

---

.metrics.json
bin/README.md
bin/cfgyaml2make
bin/ci_check
bin/cv_regress
bin/templates/metrics.json.j2
bin/templates/regress_macros.j2
bin/templates/regress_sh.j2
bin/templates/regress_vsif.j2
bin/yaml2make
cv32e40x/regress/cv32e40x_interrupt.yaml
cv32e40x/sim/Common.mk
cv32e40x/tb/uvmt/uvmt_cv32e40x_dut_wrap.sv
cv32e40x/tb/uvmt/uvmt_cv32e40x_step_compare.sv
cv32e40x/tb/uvmt/uvmt_cv32e40x_tb.sv
cv32e40x/tb/uvmt/uvmt_cv32e40x_tb_ifs.sv
cv32e40x/tests/uvmt/base-tests/uvmt_cv32e40x_base_test.sv
cv32e40x/vendor_lib/imperas/riscv_CV32E40X_OVPsim/sv/riscv_CV32E40P.sv
lib/uvm_agents/uvma_interrupt/uvma_interrupt_mon.sv
mk/uvmt/dsim.mk
mk/uvmt/riviera.mk
mk/uvmt/vcs.mk
mk/uvmt/vsim.mk
mk/uvmt/xrun.mk

Remove all compile-time defines for Imperas ISS (USE_ISS)
Instead create run-time option (+USE_ISS).
Requires a PR to E40X to make tracer handoff with OVP ISS also run-time selectable.  Note that this PR points to a local fork which does this.  I will PR that update as well when we review/approve this PR.
Note that due to design of step-and-compare testcases will not repeat between running with and without ISS.
@MikeOpenHWGroup Will discuss this tomorrow morning.

make imperas iss ovpsim selectable at run-time

---

.github/workflows/cv32e40p-scheduled-metrics-regress.yml

using workflow_dispatch in schedule to convert this action to manual-start only

disable scheduled regression on the e40p

---

bin/run_embench.py
cv32e40x/tests/.gitignore
cv32e40x/vendor_lib/.gitignore
mk/Common.mk
mk/uvmt/unsim.mk

No real change to embench flow except to emit log location so user can debug failures in benchmarks
add gitignores for embench in e40x
reduce default verbosity of yaml2make to clean up log messages (re-enable with VERBOSE=1 to make)

improve error log reporting when embench fails

---

cv32e40x/sim/Common.mk
cv32e40x/tb/uvmt/uvmt_cv32e40x_tb.sv

Updated references in uvmt_cv32e40x_tb to reflect RTL changes. (Controller and interrupt controller was moved out of ID stage and into toplevel).

Updating references/bindings in toplevel tb

---

cv32e40x/tests/programs/custom/dhrystone/dhrystone.c

A simple call to the cycle counter implemented in mm_ram has been added to the dhrystone test, result is printed to log.

Added a simple cycle count report to dhrystone

---

lib/uvm_agents/uvma_isacov/uvma_isacov_mon.sv

The [PR about integrating a disassembler](https://github.com/openhwgroup/core-v-verif/pull/554) broke runs with GUI=1.
Sorry I was not aware of this until I tried GUI=1 just now.
Explanation:
The use of DPI includes a shared object file (.so).
By default this .so is not built and included in simulations.
It is ok to run without the .so and still have references to it in the code, as long as one don't attempt to call it.
Hence, I used ifdef to make such usage optional.
But running in gui (xrun) treats this differently and complained about the missing symbol linkage even when it would not get called.
Solution:
Ifdef the entire function that refers to the dpi function.
(As opposed to ifdef on only _the call to the function_ that refers to the dpi function).

Bugfix uvma_isacov GUI=1

---

cv32e40x/tb/core/mm_ram.sv

This options works in the same way as the existing `max_data_zero_instr_stall` config for generating random stalls on the obi interfaces.
We use this to test the performance impact of the 40x's changes to the prefetch aligner and FIFO.

Add a config for single-cycle stalls in mm_ram

---

bin/ci_check

`ci_check` incorrectly builds the Makefile variables for cloning the RTL repo in the case where the user wants to override what's in `/<core>/sim/Common.mk`.  I stumbled across this one while testing [576](https://github.com/openhwgroup/core-v-verif/pull/576).  The fix is trivial.
This is something we'll want to propagate the dev branch for all cores.  I'm deliberately pushing this onto the master, as it gives us an opportunity to see how that will work.

Fix REPO, BRANCH and HASH variables

---

cv32e40p/tb/core/mm_ram.sv
cv32e40p/tb/uvmt/uvmt_cv32e40p_step_compare.sv
cv32e40p/vendor_lib/imperas/design/ram.sv

This pull Request includes the feedback of IO updates for the virtual peripherals so that the RM sees the same values read from IO as the RTL

add in support for IO memory updating the RM memeory view

---

cv32e40x/env/uvme/uvme_cv32e40x_cfg.sv
lib/uvm_agents/uvma_isacov/cov/uvma_isacov_cov_model.sv
lib/uvm_agents/uvma_isacov/uvma_isacov_cfg.sv
lib/uvm_agents/uvma_isacov/uvma_isacov_constants.sv
lib/uvm_agents/uvma_isacov/uvma_isacov_instr.sv
lib/uvm_agents/uvma_isacov/uvma_isacov_mon.sv
lib/uvm_agents/uvma_isacov/uvma_isacov_pkg.sv
lib/uvm_agents/uvma_isacov/uvma_isacov_tdefs.sv

Hi. Sorry for making a PR from someone else's fork, but the reason is that I want to continue adding features that build upon the work in their branch. And I would also like to have each feature in their own PRs, such that both reviews and changes are more focused, flexible, and decoupled. This doesn't follow the typical flow so I wasn't sure about the best way to proceed.
Description:
Adds coverage for sequences of instructions and data dependency hazards.
Also defines csr covergroups and enum.
And it organizes into a new ...tdefs.sv file.
@strichmo, do you know any reason it should not be merged?
Is it for example not complete enough so it should wait?
An alternative might be having a temporary branch in openhwgroup/core-v-verif?
I have two PR's that (independently) build upon this PR: …

Expand ISACOV with sequences, groups, and hazards

---

cv32e40x/sim/Common.mk
cv32e40x/tb/uvmt/uvmt_cv32e40x_dut_wrap.sv
cv32e40x/tb/uvmt/uvmt_cv32e40x_tb.sv

In addition to the probe updates, there has been changes to the interface of cv32e40x and cv32e40x_wrapper:
Signals added: instr_memtype_o, instr_prot_o, data_memtype_o, data_prot_o, fencei_flush_req_o, nmi_addr_i, fencei_flush_ack_i
Signals removed: .pulp_clock_en_i
This PR removes pulp_clock_en_i, but TB cleanup is still needed. 
The added signals are unconnected in the TB.

Update probes in testbench after design updates

---

cv32e40x/env/uvme/uvme_cv32e40x_cfg.sv
lib/uvm_agents/uvma_isacov/cov/uvma_isacov_cov_model.sv
lib/uvm_agents/uvma_isacov/uvma_isacov_cfg.sv
lib/uvm_agents/uvma_isacov/uvma_isacov_constants.sv
lib/uvm_agents/uvma_isacov/uvma_isacov_instr.sv
lib/uvm_agents/uvma_isacov/uvma_isacov_mon.sv
lib/uvm_agents/uvma_isacov/uvma_isacov_pkg.sv
lib/uvm_agents/uvma_isacov/uvma_isacov_tdefs.sv

This is an attempt to simplify the filtering of bins in the instruction group cg.
As far as I can see, tweaking the cfg will make covergroups appear/disappear in the coverage results.
It should be the same as before except that the bins are shown prefixed "AUTO", unless if I have overlooked anything important (hence why I create this PR for review/discussion).
Continues from https://github.com/openhwgroup/core-v-verif/pull/592

Use ignore/illegal bins to filter instr group cg

---

cv32e40x/env/uvme/uvme_cv32e40x_cfg.sv
lib/uvm_agents/uvma_isacov/cov/uvma_isacov_cov_model.sv
lib/uvm_agents/uvma_isacov/uvma_isacov_cfg.sv
lib/uvm_agents/uvma_isacov/uvma_isacov_constants.sv
lib/uvm_agents/uvma_isacov/uvma_isacov_instr.sv
lib/uvm_agents/uvma_isacov/uvma_isacov_mon.sv
lib/uvm_agents/uvma_isacov/uvma_isacov_pkg.sv
lib/uvm_agents/uvma_isacov/uvma_isacov_tdefs.sv

Description:
Adds crosses of register coverpoints.
Example `rd` crossed with `rs1`.
By default these covers are disabled, and can be enabled via the config object.
Continues from https://github.com/openhwgroup/core-v-verif/pull/592
ps:
I don't like how flags must be passed to cg instantiation like this:
`addi_cg   = new("addi_cg", .reg_crosses_enabled(cfg.reg_crosses_enabled));`.
But SystemVerilog doesn't allow using the class handle of `cfg` in the constant expression of the `with` clause, and I found no other option. (i.e. the simulator claims so, but I wasn't 100% convinced after reading the SV formal syntax).

Add more register crosses to individual ISA coverage

---

cv32e40p/regress/cv32e40p_rel_check.yaml
cv32e40x/regress/cv32e40x_rel_check.yaml

As discussed in today's VTG meeting.  These failures are known false negatives that give grief to integrations onto the release branches.  We can reinstate once the false negative is resolved.
Note that these will need to be pushed to the e40x/release and e40s/release branches.

Temporarily remove "WFI" interrupt tests

---

bin/lib/cv_regression.py
bin/templates/metrics.json.j2
cv32e40p/regress/cv32e40p_rel_check.yaml
cv32e40x/regress/cv32e40x_rel_check.yaml

Fix waves button in Metrics by using standard dsim.vcd filename for the Metrics waveform file
Fix isFail in Metrics so that assertion-fails do not show as Incomplete.
Comment out more corev-dv interrupt tests in rel_check for e40p and e40x until Metrics issue fixed.

various Metrics fixes and another corev-dv interrupt test removal

---

cv32e40x/tb/uvmt/uvmt_cv32e40x_tb.sv
lib/uvm_agents/uvma_isacov/uvma_isacov_if.sv
lib/uvm_agents/uvma_isacov/uvma_isacov_instr.sv
lib/uvm_agents/uvma_isacov/uvma_isacov_mon.sv
lib/uvm_agents/uvma_isacov/uvma_isacov_mon_trn_logger.sv
lib/uvm_agents/uvma_isacov/uvma_isacov_tdefs.sv
mk/uvmt/uvmt.mk
mk/uvmt/xrun.mk

This change is for checking that ISA coverage samples correctly (try to detect false positives/negatives), and includes some corresponding fixes to the sampling/decoding itself.
It changes formatting in isacov's logging to be compatible with 40x's tracer log [1].
It also adds to get_instr_type() and convert2string() to handle those cases which were missing.
Essentially, since incoming binary words are decoded into uvm objects (which coverage samples) and these objects are printed to a log, they can be compared against a reference log (if the logs match, then the uvm objects should have correct data in them).
This diffing of logs actually did uncover some instructions being sampled wrong.
For example, branch instructions had the offset's sign bit wrong (due to Spike internals) and both …

Diffing isacov log vs tracer log

---

.metrics.json
cv32e40x/regress/cv32e40x_rel_check.yaml

Previously removed WFI tests from rel_check regression are now restored.
Note that the e40p will be upgraded in a separate PR.

update dsim version to fix sva and cov issues

---

lib/uvm_agents/uvma_debug/uvma_debug_drv.sv

This PR resolves (solves?) the issue we have been seeing with the `debug_test_boot_set` test-program when running under DSIM.  I have demonstrated to myself that the test now passes (and behaves as expected) with both DSIM and XRUN.

cleanup of uvma_debug_drv_c::drv_req()

---

cv32e40p/sim/Common.mk
cv32e40p/tb/core/mm_ram.sv
lib/uvm_agents/uvma_debug/uvma_debug_drv.sv

Please hold you nose and review.  I just noticed that the fixes put in for the cycle-counter virtual peripheral do not work for Verilator.
Also points to the latest version of CV32E40P RTL.

Fix verilator for CV32E40P

---

lib/uvm_agents/uvma_isacov/cov/uvma_isacov_cov_model.sv
lib/uvm_agents/uvma_isacov/uvma_isacov_tdefs.sv

Hi @silabs-robin.  This PR is to fix a typo I introduced in `uvma_isacov_tdefs.sv`.  While I was looking into this I noticed a second typo in `uvma_isacov_cov_model.sv`.

Fix a couple of typos in ISACOV

---

lib/uvm_agents/uvma_isacov/uvma_isacov_tdefs.sv
mk/uvmt/vsim.mk
mk/uvmt/xrun.mk

For Questa and Xcelium suppress multiple warnings dealing with empty cross and coverpoints.  This is part of the methodology of configuring coverage in ISACOV.
Add static initializer in ISACOV to fix a warning from Xcelium.

warning fixes with ISACOV

---

mk/Common.mk

only dump out executable sections to cut down noise and duplicate addresses in the objdump file

change objdump flags to optimize debugging

---

docs/VerifStrat/source/planning_requirements.rst

This chapter was both out-of-date and (now) redundant.  This PR cleans that up.

Cleanup the "Verification Planning" chapter

---

mk/Common.mk
mk/uvmt/dvt.mk

@MikeOpenHWGroup could you please review this PR? We need this new rule for the Verissimo integration.

Add new DVT makefile rule for extracting all makefile defined variables

---

cv32e40x/vendor_lib/imperas/riscv_CV32E40X_OVPsim/sv/riscv_CV32E40P.sv
mk/uvmt/dsim.mk

`import "DPI-C" context function void svPush(input  SVDataT SVData);  // was output`

Fix argument direction for svPush

---

lib/uvm_agents/uvma_isacov/cov/uvma_isacov_cov_model.sv

As per https://github.com/openhwgroup/core-v-verif/issues/664 this PR updates `cp_uimm` in sampling of `cg_csritype`.
The problem was a slightly confusing term in riscv formats, `uimm` (_"unsigned immediate"_) which name is used only in csr instructions and some compressed instructions. It is not the same as how `imm` differs between the instruction formats (e.g. U-type, R-type, etc). Hence, the existing `immu[31:12]` did not sample the immediate of csr instructions.
ps. There is also a question of whether "special" fields like `uimm` and `shamt` should be made into new properties of the instruction class or if it is fine to reuse the existing canonical fields like `rs1` and `rs2`. (i vote for the latter)

Fix cp_uimm in cg_csritype

---

lib/uvm_agents/uvma_rvvi/uvma_rvvi_sqr.sv

fix memory leak, do not enqueue rvfi instruction if rvvi is not enabled

---

lib/uvm_agents/uvma_rvfi/seq/uvma_rvfi_csr_seq_item.sv

This is probably a bug in Questa, but the scope identifier does seem to fix with Questa 2021.2

add pkg scope to workaround compilation issue in Questa

---

cv32e40x/regress/cv32e40x_ci_check.yaml
cv32e40x/regress/cv32e40x_rel_check.yaml

add skip_sim for DSIM on debug and interrupts tests until dsim fixed

---

cv32e40x/tb/uvmt/uvmt_cv32e40x_pkg.sv
cv32e40x/tests/uvmt/base-tests/uvmt_cv32e40x_base_test.sv
lib/uvm_agents/uvma_rvvi_ovpsim/uvma_rvvi_ovpsim_cfg.sv
lib/uvm_agents/uvma_rvvi_ovpsim/uvma_rvvi_ovpsim_drv.sv

Enables Imperas to restructure memory storage variable as needed.
Enables interfaces to avoid cross-module references to remain SV LRM compliant.
@eroom1966 will need to fix the path from bus.mem in 
cv32e40x/tests/uvmt/base-tests/uvmt_cv32e40x_base_test.sv
```
// FIXME: Lee Moore, please revert this commented out line when mem variable is moved back to ram
//rvvi_ovpsim_cfg.ovpsim_mem_path = "uvmt_cv32e40x_tb.iss_wrap.ram.mem";
rvvi_ovpsim_cfg.ovpsim_mem_path = "uvmt_cv32e40x_tb.iss_wrap.bus.mem";
```

move the ovpsim mem variable configuration to an HDL path

---

cv32e40p/tb/uvmt/uvmt_cv32e40p_dut_wrap.sv
cv32e40p/tb/uvmt/uvmt_cv32e40p_tb.sv
cv32e40s/env/uvme/uvme_cv32e40s_cfg.sv
cv32e40s/tb/uvmt/uvmt_cv32e40s_dut_wrap.sv
cv32e40s/tb/uvmt/uvmt_cv32e40s_iss_wrap.sv
cv32e40s/tb/uvmt/uvmt_cv32e40s_pkg.sv
cv32e40s/tests/uvmt/base-tests/uvmt_cv32e40s_base_test.sv

Tweaks to get e40p, e40x and e40s ci_checks all passing.
ISS memory locations needed to be fixed
Temporarily use E40X variant in unified ISS model.

ci_check fixes for cv32e40p and cv32e40s

---

cv32e40x/tests/programs/custom/pma/pma.c

I tweaked pma.c in correspondence with problems that arose when testing newest OVPsim features.
Making this PR in response to (or as an alternative to?) https://github.com/openhwgroup/core-v-verif/pull/746.
Details:
* Comments away parts not yet implemented in RTL
* Moves "store" test before "load" test, to resolve uninitialized memory

Pma test, fix LW/SW problems 

---

mk/Common.mk

use isa registers instead of ABI (x0-x31)
delineate compressed instructions in pnemonics with c. prefix

change options to objdump for better debug

---

cv32e40p/tests/programs/custom/perf_counters_instructions/test.yaml

Replace `max_data_zero_instr_stall` plusarg (used in the now deprecated mm_ram.sv) with `rand_stall_obi_disable` supported by the new obi_memory_agent (see [uvma_obi_memory_cfg.sv](https://github.com/openhwgroup/core-v-verif/blob/master/lib/uvm_agents/uvma_obi_memory/src/obj/uvma_obi_memory_cfg.sv#L225)).
The obi_memory_agent does not have a `max_data_zero_instr_stall` plusarg, and without some tight constraints on the instruction fetch OBI bus the `perf_counters_instructions` directed test will not accurately predict performance counter values.  This change also constrains the data load/store OBI bus, so we may wish to implement a `max_data_zero_instr_stall` type constraint in the future.

Replace max_data_zero_instr_stall plusarg with rand_stall_obi_disable

---

cv32e40s/env/uvme/vseq/uvme_cv32e40s_vp_debug_control_seq.sv
cv32e40x/env/uvme/vseq/uvme_cv32e40x_vp_debug_control_seq.sv

This should fix the debug_test_trigger (on master) for the cv32e40x and cv32e40s.  Adding as hotfix to assist with an ongoing issue with OVPSim.
Will follow up with a merge up to cv32e40x/release and cv32e40x/dev

debug_req must be clocking drive

---

cv32e40x/env/uvme/uvme_cv32e40x_env.sv
lib/uvm_agents/uvma_obi_memory/src/obj/uvma_obi_memory_cfg.sv
lib/uvm_agents/uvma_obi_memory/src/seq/uvma_obi_memory_slv_base_seq.sv
lib/uvm_agents/uvma_obi_memory/src/seq/uvma_obi_memory_vp_cycle_counter_seq.sv

virtual peripheral register to print cycle count was missing
fix adding latencies on rvalid in the uvma obi memory sequence

fix cycle count print virtual peripheral

---

.gitignore
bin/objdump2itb
lib/uvm_agents/uvma_rvfi/seq/uvma_rvfi_instr_table_seq_item.sv
lib/uvm_agents/uvma_rvfi/uvma_rvfi_mon_trn_logger.sv
lib/uvm_agents/uvma_rvfi/uvma_rvfi_pkg.sv
mk/Common.mk
mk/uvmt/dsim.mk
mk/uvmt/riviera.mk
mk/uvmt/uvmt.mk
mk/uvmt/vcs.mk
mk/uvmt/vsim.mk
mk/uvmt/xrun.mk

Annotates the RVFI with execution information from the ELF file of the program being executed:
Example:
```
0.000 ns: RVFI  Order       PC    Instr M rs1 rs1_data rs2 rs2_data  rd  rd_data mem mem_addr mem_data instr
54.000 ns: RVFI      1 00000080 0000d197 M x 1 00000000 x 0 00000000 x 3 0000d080  -- -------- -------- _start crt0.S 23 - auipc x3,0xd
74.000 ns: RVFI      2 00000084 42018193 M x 3 0000d080 x 0 00000000 x 3 0000d4a0  -- -------- -------- _start crt0.S 24 - addi x3,x3,1056 # d4a0 <__global_pointer$>
89.000 ns: RVFI      3 00000088 00400117 M x 0 00000000 x 4 00000000 x 2 00400088  -- -------- -------- _start crt0.S 28 - auipc x2,0x400
110.000 ns: RVFI      4 0000008c f7810113 M x 2 00400088 x24 00000000 x 2 00400000  -- -------- -------- _start crt0.S 28 - addi x2,x2,-136 # …
```

add instruction trace table generation and trace to rvfi

---

cv32e40p/env/uvme/vseq/uvme_cv32e40p_vp_status_flags_seq.sv
cv32e40s/env/uvme/vseq/uvme_cv32e40s_vp_status_flags_seq.sv
cv32e40x/env/uvme/vseq/uvme_cv32e40x_vp_status_flags_seq.sv
lib/uvm_agents/uvma_obi_memory/src/seq/uvma_obi_memory_slv_seq.sv
lib/uvm_agents/uvma_obi_memory/src/seq/uvma_obi_memory_vp_base_seq.sv
lib/uvm_agents/uvma_obi_memory/src/seq/uvma_obi_memory_vp_cycle_counter_seq.sv
lib/uvm_agents/uvma_obi_memory/src/seq/uvma_obi_memory_vp_interrupt_timer_seq.sv
lib/uvm_agents/uvma_obi_memory/src/seq/uvma_obi_memory_vp_sig_writer_seq.sv

Virtual peripherals should be installable at *any* address.  This PR provides a method and VP base variables to ensure that implementations can retrieve a register offset index independent of the the implementation's absolute address.

remove absolute addresses within virtual peripheral sequences

---

cv32e40s/sim/Common.mk

Should include RTL cleanups for negative index issue for DSIM.
ci_check still expected to fail until some user mode fixes are applied.

point to latest e40s RTL

---

cv32e40x/sim/Common.mk
cv32e40x/tb/uvmt/uvmt_cv32e40x_constants.sv
cv32e40x/tb/uvmt/uvmt_cv32e40x_debug_assert.sv
cv32e40x/tb/uvmt/uvmt_cv32e40x_dut_wrap.sv
cv32e40x/tb/uvmt/uvmt_cv32e40x_tb.sv
cv32e40x/tb/uvmt/uvmt_cv32e40x_tb_ifs.sv
lib/uvm_agents/uvma_rvfi/seq/uvma_rvfi_instr_seq_item.sv
lib/uvm_agents/uvma_rvfi/uvma_rvfi_constants.sv
lib/uvm_agents/uvma_rvfi/uvma_rvfi_instr_if.sv
lib/uvm_agents/uvma_rvfi/uvma_rvfi_instr_mon.sv
lib/uvm_agents/uvma_rvvi_ovpsim/seq/uvma_rvvi_ovpsim_control_seq.sv
lib/uvm_agents/uvma_rvvi_ovpsim/seq/uvma_rvvi_ovpsim_control_seq_item.sv
lib/uvm_agents/uvma_rvvi_ovpsim/uvma_rvvi_ovpsim_drv.sv

Manually integrate https://github.com/openhwgroup/core-v-verif/pull/817 with the latest cv32e40x RTL.

incorporate new RVFI debug signals and latest RTL

---

lib/uvm_agents/uvma_obi_memory/src/uvma_obi_memory_assert_if_wrp.sv

fix bug by chaining the IS_1P2 parameter in UVM OBI assertion wrapper

---

mk/uvmt/xrun.mk

Simplified gen_corev-dv makefile target as follows:
- Removed superfluous clean old tests-section
(rsync will fail if output files are missing, and will properly overwrite files in the destination directory anyway)
- replaced cp with rsync, to enable cleanup of output folder after completion 
(This will ensure that only newly generated files are copied to the test location)
- Comment removed to enable && \ after xrun-command and avoid the no-op ls-command 
(Comments do not play well inside split lines)

gen_corev-dv makefile target cleanup

---

mk/uvmt/xrun.mk

the rsync did not seem to work with some users
This change will effectively revert this PR: https://github.com/openhwgroup/core-v-verif/pull/826
On some systems, the rsync simply did not work properly.

revert copy of generated S files to old copy

---

lib/uvm_agents/uvma_core_cntrl/uvma_core_cntrl_cfg.sv

atoi and atohex sign-extends and truncates without warning,
Incorrect behavior when address width >32 bits or MSB=1
(setting `TEST_PLUSARGS=+nmi_addr=0xbc000100` replicates the problem this commit fixes)

Changed atoi and atohex to $sscanf as per LRM 6.16.9

---

cv32e40x/regress/cv32e40x_rel_check.yaml

remove csr_access_test from rel_check until OVPSIM issue is fixed

---

cv32e40p/tb/uvmt/uvmt_cv32e40p_iss_wrap.sv

patch changed valid behavior in iss by adding ecall exceptions in ste…p and compare
this should be temporary until RVFI/RVVI ported to E40P

fix ecall in E40P with latest OVPSIM

---

cv32e40x/env/uvme/uvme_cv32e40x_cfg.sv
cv32e40x/env/uvme/uvme_cv32e40x_cntxt.sv
cv32e40x/env/uvme/uvme_cv32e40x_env.sv
cv32e40x/env/uvme/uvme_cv32e40x_pkg.sv
cv32e40x/sim/Common.mk
cv32e40x/tb/uvmt/uvmt_cv32e40x.flist
cv32e40x/tb/uvmt/uvmt_cv32e40x_dut_wrap.sv
cv32e40x/tb/uvmt/uvmt_cv32e40x_interrupt_assert.sv
cv32e40x/tb/uvmt/uvmt_cv32e40x_tb.sv
lib/uvm_agents/uvma_fencei/seq/uvma_fencei_seq_item.sv
lib/uvm_agents/uvma_fencei/uvma_fencei_agent.sv
lib/uvm_agents/uvma_fencei/uvma_fencei_assert.sv
lib/uvm_agents/uvma_fencei/uvma_fencei_cfg.sv
lib/uvm_agents/uvma_fencei/uvma_fencei_cntxt.sv
lib/uvm_agents/uvma_fencei/uvma_fencei_constants.sv
lib/uvm_agents/uvma_fencei/uvma_fencei_drv.sv
lib/uvm_agents/uvma_fencei/uvma_fencei_if.sv
lib/uvm_agents/uvma_fencei/uvma_fencei_macros.sv
lib/uvm_agents/uvma_fencei/uvma_fencei_mon.sv
lib/uvm_agents/uvma_fencei/uvma_fencei_mon_trn_logger.sv
lib/uvm_agents/uvma_fencei/uvma_fencei_pkg.flist
lib/uvm_agents/uvma_fencei/uvma_fencei_pkg.sv
lib/uvm_agents/uvma_fencei/uvma_fencei_sqr.sv
lib/uvm_agents/uvma_fencei/uvma_fencei_tdefs.sv
mk/uvmt/uvmt.mk

Cleans up lingering warnings in the core-v-verif CV32E40X testbench.
Adds a basic UVM agent for the fence.i instruction interface (on the E40X/S) to provide random ack response to fence.i.  A driver, monitor and assertion module were added.

e40x warning cleanup and add fencei UVM agent

---

cv32e40p/tb/core/mm_ram.sv
cv32e40p/tb/uvmt/uvmt_cv32e40p_tb.sv
cv32e40p/tests/uvmt/base-tests/uvmt_cv32e40p_base_test.sv
lib/uvm_agents/uvma_obi_memory/src/comps/uvma_obi_memory_cov_model.sv
lib/uvm_agents/uvma_obi_memory/src/comps/uvma_obi_memory_drv.sv
lib/uvm_agents/uvma_obi_memory/src/comps/uvma_obi_memory_seq_item_logger.sv
lib/uvm_libs/uvml_trn/uvml_trn_seq_item.sv

This pull request address a few more of the SV/UVM lint errors reported by [Verissimo](https://dvteclipse.com/core5verif-verissimo/1/main/index.html).  @strichmo, some of this was merged onto the master branch already in PR #840.  I'm asking for a PR to cv32e40p/dev because I goofed up on at least one waiver, and I should have been PR'ing to dev all along (my bad).
- `mm_ram.sv`: The UVM environment no longer uses mm_ram, but the "redundant code" lint error was accurate, so I cleaned that up.
- `uvmt_cv32e40p_tb.sv` and `uvmt_cv32e40p_base_test.sv`: removed unused declarations and waived the "do not use `$display()`" rule (because it does not apply in these cases - see my comments to see if you agree).
- `uvma_obi_memory_cov_model`, `uvma_obi_memory_drv.sv` and …

Address lint errors in CV32E40P environment

---

cv32e40x/env/uvme/uvme_cv32e40x_cfg.sv
cv32e40x/regress/cv32e40x_obi_bus_err.yaml
lib/uvm_agents/uvma_obi_memory/src/comps/uvma_obi_memory_mon.sv
lib/uvm_agents/uvma_obi_memory/src/comps/uvma_obi_memory_mon_trn_logger.sv
lib/uvm_agents/uvma_obi_memory/src/obj/uvma_obi_memory_cfg.sv
lib/uvm_agents/uvma_obi_memory/src/obj/uvma_obi_memory_mon_trn.sv
lib/uvm_agents/uvma_rvfi/uvma_rvfi_mon_trn_logger.sv
lib/uvm_agents/uvma_rvvi/uvma_rvvi_mon_trn_logger.sv

Various cleanup for the monitor logs
ensure some standardization in order of fields and formatting of logs in these agent to optimize debug

standardize logs and cleanup logs for rvvi, rvfi and obi

---

cv32e40x/tb/uvmt/uvmt_cv32e40x_tb.sv

Discovered by random address tests by @silabs-hfegran.
We need this change to be able to test entire 32-bit address space.

configure ISS to consider entire 32-bit address space as RAM

---

bin/templates/regress_sve.j2

Excluded the primary prompt variable (PS1) from being parsed
into the regression enviornment.
Reasoning: Custom user prompts may cause regression scripts to
fail due to incompatible shell functionality settings.

Prevent regression scripts from parsing primary prompt variable

---

cv32e40s/env/uvme/uvme_cv32e40s_cfg.sv

Comment out constraint for non-existent member (b_ext) and cleanup white-space.

Comment out constraint for non-existant member (b_ext)

---

cv32e40s/env/uvme/uvme_cv32e40s_cfg.sv
cv32e40s/sim/Common.mk
cv32e40s/tb/uvmt/uvmt_cv32e40s_constants.sv
cv32e40s/tb/uvmt/uvmt_cv32e40s_dut_wrap.sv
cv32e40s/tb/uvmt/uvmt_cv32e40s_tb.sv

This is a cherry-pick of https://github.com/openhwgroup/core-v-verif/pull/883
retargeted to the master branch with some cleanup for core cntrl extension switches for the Zb* extensions.
This passes all e40s ci_check but I am pushing up anyway to get these fixes working and I am not sure of the expected state of the E40S ci_check.

Fixes to get e40s bench up and running to master branch

---

cv32e40x/sim/Common.mk
lib/uvm_agents/uvma_rvfi/uvma_rvfi_instr_mon.sv

reference model will update interrupt CSR and take the debug handler
updates the E40X RTL to bring in bugfix for https://github.com/openhwgroup/cv32e40x/issues/204

allow interrupt and debug to be signalled on same RVFI instruction

---

cv32e40x/bsp/handlers.S
cv32e40x/tests/programs/custom/data_bus_error/data_bus_error.c

This was accidentally omitted from a previous PR.  The test was updated such that the custom handlers in the test will properly handshake with the BSP.  Thus data_bus_error will now pass with USE_ISS=0.

fix handling and recovery of data bus errors in data bus error directed test

---

vendor_lib/verissimo/waivers.xml

Disable SVTB.12.1.2 (Methods defined outside of classes must be explicitly declared automatic or static) for all SV sources in core-v-verif.
(This will also check that I understand how to update the waiver file correctly.)

Disable Check: SVTB.12.1.2

---

cva6/regress/install-cva6.sh

update to latest commit on master branch of cva6
Test suites (riscv-compliance, riscv-tests) have the same results as before the cva6_reorg.

install-cva6.sh: use master branch for cva6

---

cva6/regress/install-cva6.sh
cva6/tb/core/cva6_tb.sv

use of $plusargs in CVA6 (see 5c5c704d1d14190ec349fae12fe39fbe025456ae)

cva6_tb.sv: remove .SIM_FINISH as replaced by time_out

---

bin/templates/regress_vsif.j2

- this debug broke some features with vManager-Jenkins integration
- has no real functional effect other than RUN_INDEX of all Jenkins runs will match the overall jenkins ID instead of always being an incrementing index per job

remove seed hack in vManager to increment index

---

cv32e40x/sim/Common.mk

Updates CV_CORE_HASH to the latest 40x.
There was initially a few problems, but they were fixed and merged in the 40x repo.
It now passes ci_check.

Update rtl hash for 40x

---

cv32e40x/tests/programs/custom/b_ext_test/test.yaml
mk/Common.mk

always enable experimental extensions in LLVM
update march strings for the latest top-of-tree releases of LLVM and corev toolchains

fix bug selecting the COREV toolchain

---

cv32e40x/env/corev-dv/cv32e40x_fencei_instr_lib.sv

This PR fixes a bug in the `corev_store_fencei_load_instr_stream` random test.
The problem was that I used a completely random addresses that were stored to and it led to iss mismatch when certain addresses were used that shouldn't have been used.
Fixed by reusing the methods in the parent class `riscv_load_store_rand_instr_stream` to get sensible addresses.
I have tested with 10 different seeds now and I have not seen any more problems.

Fix bug in "store_fencei_load" test for 40x

---

cv32e40x/env/corev-dv/cv32e40x_pma_instr_lib.sv
cv32e40x/env/uvme/uvme_cv32e40x_core_sb.sv

This PR fixes two major issues with the _corev_pma_rand_pma_test_ in cv32e40x regressions.
- OVPSIM does not seem to handle fetches from the _end_ of memory (i.e 0xffff_fffc) well.
- super.post_randomize() usage in many PMA instructions streams is cleaned up to avoid inserting instructions from super classes that are not properly constrained in accordance with the intended class.  This caused address generation for these instructions to be not-as-intended which could overwrite instructions in the flat memory space.

corev_pma_rand_pma_test fixes for instruction corruption

---

cv32e40x/env/uvme/uvme_cv32e40x_core_sb.sv
lib/uvm_agents/uvma_rvfi/uvma_rvfi_instr_mon.sv

Enables data bus errors in debug mode to be properly signaled for NMI pending.

connect nmip CSR RVFI to ISS NMI signal

---

cv32e40x/tb/uvmt/uvmt_cv32e40x_debug_assert.sv

For reasons unknown, the addition of `a_dmhaltaddr_stable` cause Metrics DSIM simulations of some (but not all) testcases to drastically slow down. For example, "make test TEST=interrupt_test" goes from ~8.5 minutes to more than 87 minutes.  Oddly, the simulation runs correctly, it just takes a very long time.   I have raised a support issue with Metrics.
The code that causes this issue is changed in this PR.  A redundant whitespace (`2'b 00`) is also fixed, but that is of no consequence to either xrun or dsim.  Please have a look and satisfy yourself that I have not broken anything.

Remove redundant use of always for a_dmhaltaddr_stable

---

cva6/sim/Makefile
cva6/sim/cva6.yaml

Hello @MikeOpenHWGroup,
To make simulation faster, i added memory preloading support for vcs-testharness. `cva6.yaml` takes the right commands to preload memory using the makefile in the cva6 repository.
This PR is highly dependent on the PR n°772 i did in the cva6 repository. (https://github.com/openhwgroup/cva6/pull/772)
I recommend to wait for the CVA6 PR to be merged before merging this one.

Add memory preloading support for vcs-testharness

---

cva6/README.md
cva6/regress/install-cva6.sh

To ensure people will use a recent CVA6 version when executing scripts (cva6/regress/) from core-v-verif, update the default value of CVA6_HASH variable.

Use recent CVA6 version

---

.metrics.json

Docker image with dsim version `20211122.2.0` and the `riscv32-embecosm-gcc-ubuntu1804-20211128` toolchain.
Should resolve issue #1045 which in turn unlocks pull-request #1050.

Update Metrics docker image

---

cv32e40x/env/corev-dv/ldgen/cv32e40x_ldgen.sv
cv32e40x/tb/uvmt/uvmt_cv32e40x_constants.sv
cv32e40x/tests/cfg/pma_test_cfg_3.yaml
lib/mem_region_gen/pma_adapted_mem_region_gen.sv

Coverage analysis revealed a problem with the parsing of the PMA configs (parsed in reverse order), leading the configs to not capture the original test intent. This introduced the need for bug fixes in the linker and corev-dv memory region generation as well. 
Additionally, some regions were changed to main memory to fix lacking coverage.

Fixed PMA region configs wrong order

---

cv32e40x/env/corev-dv/cv32e40x_fencei_instr_lib.sv

JAL takes symbol, not a number-immediate. In the test,
linker failures occurred in cases when the store
fence.i exec stream randomization inserted a JAL instruction.
The instruction in question is supposed to never execute,
so the jump symbol is set to be at the beginning of the stream,
thus intentionally creating an infinite loop that will never
be entered.
Additionally, compiler guards were added around the instructions
that are being intentionally overwritten, to avoid potential 
problems with alignment and compressed instructions. 

Fixed JAL instruction in corev-dv fence.i test

---

cv32e40x/env/corev-dv/cv32e40x_fencei_instr_lib.sv

Hotfix for the case where the store_fencei_exec stream is the first instruction in the stream (first stream gets its label changed from 0: to main: ) leading to compilation failure - changed jump/branch target to 1: instead. The exact symbol is not important as it is never executed, but it needs to exist for compilation to succeed

Hotfix for store_fencei_exec stream located as first stream in program

---

cv32e40p/env/uvme/vseq/uvme_cv32e40p_interrupt_noise_vseq.sv
cv32e40p/env/uvme/vseq/uvme_cv32e40p_random_debug_vseq.sv
cv32e40p/env/uvme/vseq/uvme_cv32e40p_vp_rand_num_seq.sv
cv32e40p/tb/core/tb_riscv/riscv_gnt_stall.sv
cv32e40p/tb/core/tb_riscv/riscv_rvalid_stall.sv
cv32e40p/tb/uvmt/uvmt_cv32e40p_iss_wrap.sv
cv32e40p/tb/uvmt/uvmt_cv32e40p_pkg.sv
cv32e40p/tb/uvmt/uvmt_cv32e40p_step_compare.sv
cv32e40p/tests/uvmt/base-tests/uvmt_cv32e40p_base_test.sv
cv32e40p/tests/uvmt/base-tests/uvmt_cv32e40p_test_randvars.sv
cv32e40p/tests/uvmt/compliance-tests/uvmt_cv32e40p_firmware_test.sv
docs/CodingStyleGuidelines.md
lib/uvm_agents/uvma_obi_memory/src/comps/uvma_obi_memory_drv.sv
lib/uvm_agents/uvma_obi_memory/src/obj/uvma_obi_memory_cfg.sv
lib/uvm_agents/uvma_obi_memory/src/seq/uvma_obi_memory_vp_debug_control_seq.sv
lib/uvm_agents/uvma_obi_memory/src/seq/uvma_obi_memory_vp_rand_num_seq.sv
lib/uvm_libs/uvml_hrtbt/uvml_hrtbt_mon.sv
lib/uvm_libs/uvml_logs/uvml_logs_rs_json.sv
lib/uvm_libs/uvml_mem/uvml_mem.sv

Hi @silabs-hfegran, this is a big PR in terms of files, but technically a bit of a softball.  All changes are one of three categories:
1. Fixing lint errors as reported by Verissimo.
2. Removal of unnecessary white-space (continuing an on-going effort started by Steve).
3. Update to the Coding Style guidelines as per the discussion in #926.

Address multiple lint errors

---

cv32e40x/env/corev-dv/target/cv32e40x/riscv_core_setting.sv
cv32e40x/regress/cv32e40x_compliance.yaml
cv32e40x/regress/cv32e40x_full.yaml
cv32e40x/sim/Common.mk
cv32e40x/tests/cfg/b_ext_abs.yaml
cv32e40x/tests/cfg/b_ext_all.yaml
cv32e40x/tests/cfg/default.yaml
cv32e40x/tests/cfg/no_bitmanip.yaml
cv32e40x/tests/cfg/pma_test_cfg_1.yaml
cv32e40x/tests/cfg/pma_test_cfg_2.yaml
cv32e40x/tests/cfg/pma_test_cfg_3.yaml
cv32e40x/tests/cfg/pma_test_cfg_4.yaml
cv32e40x/tests/cfg/pma_test_cfg_5.yaml
cv32e40x/tests/programs/corev-dv/corev_rand_instr_test/corev-dv.yaml
mk/Common.mk
mk/uvmt/xrun.mk

Added Zba,Zbb,Zbc,Zbs-extension support to all tests.
Summary of changes:
- Updated cv32e40x hash.
- Updated riscv-dv hash (Now with support for bitmanip v1.0.0).
- Updated supported march for corev-dv to include Zba,Zbb,Zbc,Zbs.
- Added support for configuration-wide plusargs.
- Updated test configurations to use bitmanip by default.
- Added test configuration (no_bitmanip) without bitmanip support.
- Expanded full regression to include a few non-bitmanip enabled tests.
- Removed invocation of old Zbb extension in corev_rand_instr_test.
- Removed duplicate pma-test entry in regression list.
- Disabled DLCPTH-warning from xrun as it caused a lot of clutter in the log files.
- Removed COREV=1 flag from two tests in regression that should have been removed previously.
- Compliance test …

Added Zba,Zbb,Zbc,Zbs-extension support to all tests.

---

cv32e40x/tests/programs/custom/illegal_instr_test/illegal_instr_test.S

Updated illegal_instr_test to be able to handle bitmanip extensions present/not present
Summary of changes:
- Gatheres all bitmanip instructions present in the original test into one function (test_bitmanip)
- Housekeeping to keep registers in a sane state
- A few bitmanip-instructions were modified to avoid stack pointer corruption
- Sets a register to a55a5aa5 if all bitmanip instructions pass as valid instructions - this value is used as a flag to signal bitmanip support.
- Evaluates if the amount of invalid instructions matches the expected value (this value differs by 77 depending on if bitmanip support is enabled or not).
Signed-off-by: Henrik Fegran Henrik.Fegran@silabs.com

Updated illegal_instr_test to handle bitmanip extension on/off

---

cv32e40x/env/uvme/uvme_cv32e40x_cfg.sv
cv32e40x/tests/cfg/b_ext_abs.yaml
cv32e40x/tests/cfg/b_ext_all.yaml
cv32e40x/tests/cfg/default.yaml
cv32e40x/tests/cfg/pma_test_cfg_1.yaml
cv32e40x/tests/cfg/pma_test_cfg_2.yaml
cv32e40x/tests/cfg/pma_test_cfg_3.yaml
cv32e40x/tests/cfg/pma_test_cfg_4.yaml
cv32e40x/tests/cfg/pma_test_cfg_5.yaml

Merges Steve Richmonds changes to resolve issue 
https://github.com/openhwgroup/cv32e40x/issues/347
Additionally adds a temporary fix to restore functional ci_check until toolchain cleanup is in place

mcountinhibit update

---

cv32e40p/tb/uvmt/uvmt_cv32e40p_iss_wrap.sv
cv32e40p/tb/uvmt/uvmt_cv32e40p_step_compare.sv
cv32e40p/tests/uvmt/base-tests/uvmt_cv32e40p_base_test.sv
lib/uvm_agents/uvma_obi_memory/src/comps/uvma_obi_memory_drv.sv
lib/uvm_agents/uvma_obi_memory/src/seq/uvma_obi_memory_slv_seq.sv
lib/uvm_libs/uvml_logs/uvml_logs_mon_trn_logger.sv
lib/uvm_libs/uvml_logs/uvml_logs_reg_logger_cbs.sv
lib/uvm_libs/uvml_logs/uvml_logs_rs_json.sv
lib/uvm_libs/uvml_logs/uvml_logs_rs_text.sv
lib/uvm_libs/uvml_logs/uvml_logs_seq_item_logger.sv

This PR resolves and/or waives two distinct linter errors identified by Verissimo:
1. Duplicated code in `lib/uvm_agents/uvma_obi_memory/src/comps/uvma_obi_memory_drv.sv`.  Please look at this change carefully. The change is straightforward - two functions have been collapsed into a single function.  Having said that the OBI memory Agent is a critical component in our environments, so we want to be cautious about changes to it.
2. Dealing with `Verissimo SVTB.32.2.0` (Pass strings by reference).  For the most part, these have been waived.

Resolve or waive linter issues

---

cv32e40x/tests/programs/custom/illegal_instr_test/illegal_instr_test.S

Fixed an issue when restoring the signature value from wrong address in memory

Fixed error in illegal_instr_test

---

cva6/sim/Makefile
cva6/sim/cov-exclude-mod.lst
cva6/sim/cva6-simulator.yaml
cva6/sim/cva6.py
cva6/sim/cva6.yaml

- to support code coverage, test output files need to have a unique name (add timestamp to the filename)
- provide a way to exclude some modules from coverage (e.g. rvfi_tracer module)
- to support riscv-dv random tests, use unique name for program file to be loaded (no more Mem_init.txt)

Add code coverage and riscv-dv random tests

---

cva6/regress/install-riscv-dv.sh
cva6/regress/install-spike.sh
cva6/sim/cva6.py
cva6/sim/cva6_spike_log_to_trace_csv.py
cva6/sim/spike_log_to_trace_csv.py

Hello, 
This PR updates our version of spike and riscv-dv. 
Hashs for the installation are updated.
A script, `spike_log_to_trace_csv.py`, in riscv-dv needed a fix due to the new spike version. The file has been moved into sim directory until the fix is merged in riscv-dv. I will open an issue to the google team with a way to fix it. Until then, i suggest to use the new script.

Update spike and riscv-dv version

---

lib/uvm_agents/uvma_obi_memory/src/comps/uvma_obi_memory_drv.sv

Removed the redundant if() from the code snipit below:
```
// Wait for rvalid
if (mstr_mp.drv_mstr_cb.rvalid !== 1'b1) begin
while (mstr_mp.drv_mstr_cb.rvalid !== 1'b1) begin
@(mstr_mp.drv_mstr_cb);
end
end
```

Remove redundant if()

---

cva6/sim/cva6.py

problem introduced in 5b43db03d8c9fae733e720c49293e3e2996bc0e1

cva6.py: fix module import

---

cv32e40x/regress/cv32e40x_full.yaml
cv32e40x/tests/cfg/num_mhpmcounter_29.yaml
cv32e40x/tests/programs/custom/mhpmcounter29_csr_access_test_1/mhpmcounter29_csr_access_test_1.S
cv32e40x/tests/programs/custom/mhpmcounter29_csr_access_test_1/test.yaml
cv32e40x/tests/programs/custom/mhpmcounter29_csr_access_test_2/mhpmcounter29_csr_access_test_2.S
cv32e40x/tests/programs/custom/mhpmcounter29_csr_access_test_2/test.yaml

The mhpmcounter29_csr_access_test_* should be run with NUM_MHPMCOUNTERS=29.
Full regression changed to use the num_hpmcounter_29 config for these tests,  
and added support for bitmanip instructions to this cfg.

Fixed wrong cfg used for mhmpcounter29_csr_access tests

---

cv32e40x/tb/uvmt/uvmt_cv32e40x_debug_assert.sv

Corner case taken out of assertion. We are planning on covering this in a different assertion(s) when we look at the debug/nmi cross.

Excluding the cross with nmi to a_illegal_insn_debug_req

---

.gitlab-ci.yml
.gitlab-ci/cv32.yml
.gitlab-ci/cva6.yml

new CI for gitlab is massively generic to allow each group to be able to use it directly without modifications in the CI source code regardless of their runtime environment. 
Adaptations to the environment are done only in the settings of the projects. (paths of tools, version of tools, urls of repositories to use...)

Add continuous integration for gitlab-ci

---

cv32e40x/sim/core/Makefile

##Change makefile name called in another makefile for 40x
https://github.com/Nicolas-Gaudin/core-v-verif/blob/a13787838c108f9e6d55af308a2bc1b70acd6419/cv32e40x/sim/core/Makefile#L66
Change in l66 of cv32e40x/sim/core/Makefile
include ../Common.mk
into
include ../ExternalRepos.mk
As is in ../ directory

40X changing Makefile name in line 66 as is in ../ directory

---

cva6/sim/Makefile
cva6/sim/cva6.yaml

Just a small fix : Mem_init.txt has been renamed to $(TESTNAME).txt in PR #1108. 
I have updated vcs_core and vcs_gate target so it would work with this PR.

Rename Mem_init.txt to expected name for vcs_core and vcs_gate target

---

cv32e40x/tb/uvmt/uvmt_cv32e40x_debug_assert.sv
cv32e40x/tb/uvmt/uvmt_cv32e40x_tb.sv
cv32e40x/tb/uvmt/uvmt_cv32e40x_tb_ifs.sv

This PR adds 3 checks to see that [this](https://cv32e40x-user-manual.readthedocs.io/en/latest/debug.html#debug-state) part of the user manual holds true.
I initially just wanted to see for my self, but I think it makes sense to include in the debug_assert assertion set.
@silabs-oysteink do you agree with these assertions?
(I realized the first assert is redundant vs the core SVAs, so I can remove it if we want, but for completeness of the debug_assert module we could keep it.)

debug_assert: add checks for havereset/running/halted

---

cva6/sim/cva6.yaml

without this argument, all vcs-uvm simulations are using cv64a6_imafdc_sv39 configuration
fix 887a396

cva6.yaml: add missing target argument for vcs-uvm

---

.metrics.json
cv32e40x/tb/uvmt/uvmt_cv32e40x_interrupt_assert.sv

This PR brings in an updated version of dsim that resolves #1122 (and removes the hack exclude the TB code that the previous dsim release didn't like).
For the record, the Metrics issue number for this is 1163 (that is not a GitHub issue number!).
This PR has a DO NOT MERGE lable on it as I just noticed a mistake with the .metrics.json that will impact the cv32e40s.  I will fix it before removing the label.

New version of DSIM resolves #1122

---

cv32e40s/regress/cv32e40s_rel_check.yaml

This PR re-enables some tests that were commented out in relation to the merge procedure and known problems.
The two tests fails, but we want to re-enable these checks for our regressions.
Passes ci_check.
Same as https://github.com/openhwgroup/core-v-verif/pull/1167

uncomment temporarily disabled tests in 40s rel_check

---

cv32e40x/regress/cv32e40x_rel_check.yaml

This PR re-enables some tests that were commented out in relation to the merge procedure and known problems.
The tests actually did pass now, but that should not be a criteria for re-enabling them anyway.
Passes ci_check (this change shouldn't impact ci_check anyway, but for good measures).

uncomment temporarily disabled tests in 40x rel_check

---

cva6/tb/core/Flist.cva6_tb
cva6/tb/core/tb_components/axi_master_connect.sv

Hello,
I added `axi_master_connect.sv` to `cva6/tb/core/tb_components` because it no longer exists in cva6 repositories after PR-813. (https://github.com/openhwgroup/cva6/commit/741e82133d8e7e646869f78bf11969629cb474a3)
Guillaume

Add axi_master_connect.sv to tb_components

---

cva6/tb/uvmt/uvmt_cva6_dut_wrap.sv
cva6/tb/uvmt/uvmt_cva6_tb.sv

Fix the uvm testbench parameter declaration. Down size the number from 2**25 downto 2**24 because verilog array cannot be greater than 2**24 

uvmt_cva6_dut_wrap.sv, uvmt_cva6_tb.sv: fix parameter declaration

---

lib/uvm_agents/uvma_cvxif/src/obj/uvma_cvxif_cfg.sv

Fix the issue_ready by default in config class, because its randomization is not yet supported by cva6.

uvma_cvxif_cfg.sv: Do not randomize the issue_ready, by default

---

cva6/sim/Makefile
cva6/sim/init_uvm.do

The init.do is executed at simulaiton start in Verdi to dump all testbench signals. Very useful when debuging RTL !

Makefile, init_uvm.do: dump signals with init_uvm in VCS simulator

---

cva6/sim/cva6.py

Signed-off-by: Zineb El Kacimi <zineb.el-kacimi@external.thalesgroup.com>

cva6.py: add time to output files juste in case of coverage activated

---

bin/run_compliance.sh
cv32e40p/sim/ExternalRepos.mk
cv32e40s/sim/ExternalRepos.mk
cv32e40x/sim/ExternalRepos.mk
cv32e40x/tests/uvmt/compliance-tests/uvmt_cv32e40x_firmware_test.sv
lib/uvm_agents/uvma_obi_memory/src/seq/uvma_obi_memory_vp_sig_writer_seq.sv
mk/Common.mk
mk/README.md
mk/uvmt/uvmt.mk
mk/uvmt/vsim.mk
mk/uvmt/xrun.mk

Updated arch-test-suite to latest - temporarily using a fork to include
the latest bitmanip tests currently in PR. (This fork should be removed, 
and changes upstreamed when PR is approved)

Updated compliance test infrastructure

---

cv32e40s/tb/uvmt/uvmt_cv32e40s_interrupt_assert.sv
cv32e40s/tb/uvmt/uvmt_cv32e40s_tb.sv

This PR fixes 4 CEXes in "interrupt_assert".
Passes ci_check (which includes some interrupt tests).
Passes formal on pma 3 and pma 1.
All the CEXes related to user mode not being handled by the assertions.

Fix CEXes, interrupt_assert U-mode

---

.gitlab-ci/cva6.yml
cva6/regress/dv-riscv-compliance.sh
cva6/regress/dv-riscv-tests.sh

Just a small fix and change default simulators to vcs-testharness since veri-core does no longer exist. @JeanRochCoulon

Typo + veri-testharness as default simulator

---

lib/uvm_agents/uvma_cvxif/src/seq/uvma_cvxif_seq.sv

assign default value to result signals to fix unkown values in case of illegal instructions
Signed-off-by: Zineb El Kacimi <zineb.el-kacimi@external.thalesgroup.com>

uvma_cvxif_seq.sv: assign default value to result signals

---

GitCheats.md
cv32e40p/tests/uvmt/compliance-tests/uvmt_cv32e40p_firmware_test.sv

This is an easy one - I wanted to add something to `GitCheats` and took advantage by sneaking in a trivial fix of a [lint error](https://dvteclipse.com/core5verif-verissimo/1/reports/run/cdf7ee911e6f2268cf98f2bc6e0f7e484a7f396d/index.html).
@YoannPruvost, I am going to start adding you as a reviewer for all pull-requests to cv32e40p branches.

Move uvm_component_utils to top of file

---

cv32e40x/tb/uvmt/uvmt_cv32e40x_tb.sv

Fixed bit-width warnings for rvfi_intr struct connection.

Fixed bit-width warnings

---

cv32e40p/tests/programs/custom/pulp_vectorial_add_sub/pulp_vectorial_add_sub.S
cv32e40p/tests/programs/custom/pulp_vectorial_bit_manip/pulp_vectorial_bit_manip.S

(Signed the commit this time to pass ECA test)
Two of the cv32e40p pulp_vectorial_* tests were found to have minor errors when we used them to help verify the addition of the PULP_XPULP extension to the Imperas model:
1) The manual (using .word) encodings of the cv.add.div{2,4,8} instructions in pulp_vectorial_add_sub are incorrect. Specifically the funct5 field values do not match [the cv32e40p documentation](https://github.com/openhwgroup/cv32e40p/blob/master/docs/source/instruction_set_extensions.rst) for any of these instructions, and the funct3 values are incorrect for the cv.add.div2 instructions.
2) A few of the expected values defined in the tests for the cv.add.div2 instructions are not correct (missing shifts)
1) Incorrect register used for comparisons
2) One expected value was …

Fix errors in cv32e40p pulp_vectorial tests (signed this time)

---

.gitlab-ci/cva6.yml

Gitlab CI yaml seems to support only integer and string types in variables keys. So when we want to define float variables we have to set them as string with quotes. 
Synthesis scripts don't work properly with theses quote. This PR fix it.

Gitlab CI: synthesis job hot fix

---

cv32e40p/sim/core/Makefile

Add `$CUSTOM` path for vsim; 
syntax error: Add a space before new line symbol at make target `vsim-run`.

fix issue #1225 ;

---

cva6/sim/cva6.py

Exit regression with RET_FAIL code error when a test from the testlist fails.

cva6.py: return FAIL when test compare is failed

---

.gitlab-ci/scripts/merge_job_reports.py

Related to gitlab-ci,
To fix limitation of gitlab that doesn't support variable that contains white spaces I put it into quotes in previous commits.
The script fixed here have some part where this quotes are "'doubled'" and then evaluated as part of the string that cause trouble in the end.

gitlab-ci: dashboard generation scripts fix

---

.gitlab-ci/cva6.yml
cva6/regress/hwconfig_tests.sh
cva6/sim/cva6.py
cva6/tests/testlist_hwconfig.yaml

Related to https://github.com/openhwgroup/cva6/pull/862#issue-1211045880
Hello,
I have integrated the use of custom configurations in our core-v-verif flow. It allow us to create CI on features that we don't check with our ISA tests. It also ease the creation and the use of configurations different from the 4 already existing configs in CVA6. 
I've also added a testlist and a script to be runned in CI. `testlist_config.yaml` has a field `needs` to check that the configuration we use can run the test.
@JeanRochCoulon @ASintzoff can you look at this ?

CI Generated configuration

---

cva6/regress/linux.sh
cva6/regress/smoke-tests.sh
cva6/sim/Makefile
cva6/sim/cva6.py
cva6/sim/cva6.yaml

Before simulation compilation and run configuration was setup in several files (cva6.py, cva6.yaml, core-v-verif/cva6/sim/Makefile and cva6/Makefile, cva6.yaml). This modification makes the configuration accessible from cva6.py through isscomp_opts and issrun_opts. It leads to cva6.py, cva6.yaml simplification. 

introduce isscom_opts, issrun_opts and isspostrun_opts

---

cva6/regress/install-riscv-compliance.sh

as master branch was replaced by main branch on 2022-05-13
in riscv-compliance/riscv-arch-test repository

install-riscv-compliance.sh: use main branch

---

.metrics.json

This PR only affects MetricsCI regressions. Applies the same VM image used for cv32e40x/dev to cv32e40s/dev.

New image for MetricsCI

---

cv32e40s/tb/uvmt/uvmt_cv32e40s.flist

This was caught by a prospective member of the OpenHW Group who is using Synopsys VCS.  Apparently both dsim and xrun accept both curley braces and round braces around variable names in manifests and VCS does not.  Who knew?

[skip ci] Fix curly braces

---

cva6/sim/cva6.py

Small fix in order to use hwconfig regression from cva6 repository via Thales-CI
@JeanRochCoulon or @yanicasa can you review it ?
Guillaume

cva6.py: save cva6/sim path to go back to it after generating config

---

.gitlab-ci/cva6.yml
.gitlab-ci/scripts/report_fail.py

Related to gitlab-ci dashboard management
Currently, the report of each test is created at the end of the script of each job.
The problem is that if one of the commands of the job returns a non-zero error code, then no report exists for the job and nothing mentions in the dashboard that the job is failed.
Ideally, jobs should not return a zero error code even in case of fail. The fault should be seen and generated by the script that generates the report for the job.
To fix the problem, this PR adds a script ran at the beginning of each job. That generates a "fail" report, and if the job is OK, it will be overwritten by the real report at the end.
Some descriptions in the CI has also been changed

gitlab-ci: show test fail in dashboard

---

cva6/regress/install-spike.sh
cva6/regress/spike/cvxif-ext-files/customext/cvxif.cc
cva6/regress/spike/cvxif-ext-files/customext/cvxif_test.c
cva6/regress/spike/cvxif-ext-files/riscv/cvxif.h
cva6/regress/spike/cvxif-ext-files/riscv/cvxif_base.cc
cva6/regress/spike/patches/spike-cvxif-extension.patch
cva6/regress/spike/patches/spike-dlopen-diagnostics.patch
cva6/regress/spike/patches/spike-shared-fesvr-lib.patch

This PR provides a Spike extension implementing instructions for use in verifying the Core-V side of the CV-X interface in both 32b qand 64b configurations.
To use the CVXIF instructions:
* Remove the existing Spike installation located in `tools/spike`
* Run the Spike instllation script: `sh cva6/regress/install-spike.sh`
* Invoke Spike with `cvxif` extension: `spike --extension=cvxif ...`
The test program 'cva6/regress/spike/cvxif-ext-files/customext/cvxif_test.c' provides a basic test case and the instructions for checking the correct operation of the CVXIF extension.
Files changed/added:
* cva6/regress/install-spike.sh: Apply additional patches. Copy CV-X-IF
files to spike source directory.  Update copyright.
* cva6/regress/spike-shared-fesvr-lib.patch: Update and move to separate …

Add CV-X-IF extension to Spike.  Improve diagnostics of extension loader.

---

cva6/env/corev-dv/README.md
cva6/env/corev-dv/custom/cvxif_custom_instr.sv
cva6/env/corev-dv/custom/riscv_custom_instr_enum.sv
cva6/env/corev-dv/custom/rv32x_instr.sv
cva6/env/corev-dv/cva6-files.f
cva6/env/corev-dv/cva6_asm_program_gen.sv
cva6/env/corev-dv/cva6_defines.svh
cva6/env/corev-dv/cva6_instr_pkg.sv
cva6/env/corev-dv/cva6_instr_test_pkg.sv
cva6/env/corev-dv/simulator.yaml
cva6/env/corev-dv/target/rv32imc/riscv_core_setting.sv
cva6/env/corev-dv/target/rv64gc/riscv_core_setting.sv
cva6/env/corev-dv/user_extension/user_define.h
cva6/env/corev-dv/user_extension/user_define.include
cva6/sim/cva6.py

Customize and Extend the Random Instruction Generator, to add cvxif custom instructions used by cvxif agent.
Signed-off-by: Zineb El Kacimi <zineb.el-kacimi@external.thalesgroup.com>

corev-dv: add cvxif custom instructions, for cva6, to the Random Instruction Generator

---

tools/vptool/VPTOOL-readme.txt
tools/vptool/vptool/vptool.yml

Files changed:
* tools/vptool/VPTOOL-readme.txt (Configuration): Fix typo.
(Directory structure): Fix names and descriptions of dirs/files.
(Basic use): Fix incorrect paths.
* tools/vptool/vptool/vptool.yml (toplevel): Update copyright holder name.
Refer to license text using SPDX identifier.
(gui.title): Remove comment with a site-dependent list of themes.
@JeanRochCoulon @ASintzoff, please review.

[VPTOOL] Clean up documentation and code.  Update copyright notice.

---

cva6/sim/verilator_log_to_trace_csv.py

Hello, 
I set back end_trampoline back to 0x80000000 but suppress the continue statement to process instruction at 80000000.
We had issue with the UVM testbench which has no bootrom and start at 80000000. 
The script was not able to find instruction at address 10014 ( it doesn't exist in UVM tb) and didn't process the log correctly resulting in an empty csv.
The solution I propose solves this issue and still process the 1st instruction to match spike trace.

Set end_trampoline back to 80000000 and process 1st instruction

---

cva6/sim/verilator_log_to_trace_csv.py

Hello,
PR #1342 has been merge too quickly. 
testharness testbench trace to csv does not work with the changes I made in #1342. My bad ! It worked locally on a slightly different test from the ones in the regression. 
It should work well now. 
@JeanRochCoulon make sure to check dashboard before merging this PR.
@MikeOpenHWGroup I have seen the remark about not using static parameters (in this case addresses). I agree with you and it is a lot of work to do. Meanwhile this PR should fix the regression until we update our workflow for verification.
Guillaume

[HOTFIX] put back "continue" in else statement

---

cv32e40s/tb/uvmt/uvmt_cv32e40s_debug_assert.sv

Assertions appeared to start evaluation and sample a local variable value unconditionally - moved sampling to only sample on actual match

Fixed xcelium warning: Frequent false starts for some debug assertions

---

cv32e40s/env/corev-dv/cv32e40s_asm_program_gen.sv
cv32e40s/env/corev-dv/cv32e40s_pma_instr_lib.sv
cv32e40s/env/corev-dv/ldgen/cv32e40s_ldgen.sv
cv32e40s/regress/cv32e40s_pma.yaml
lib/corev-dv/corev_asm_program_gen.sv

Previous implementation for trap handler generation and nmis did not take vectored/non-vectored mode into account and used the wrong symbol as mtvec handler reference. 
This PR aims to solve these issues by:
- nmi is always located at mtvec + 4*15 (actual configured mtvec, not the address of mtvec_handler)
- vectored and direct mode interrupt should have different handlers, one using trampoline code to get to the right handler (leaving room for nmi at the correct offset), the other places the jump-instructions directly at mtvec (and includes a jump to the nmi handler at the correct location)
These changes should resolve most timeouts due to interrupt-related runaway code.

Fixes for mtvec-related issues in regressions

---

.gitlab-ci/cva6.yml

Always creates artifacts for pub_fgpa-boot job.

.gitlab-ci/cva6.yml: add always for fpga boot artifact

---

cva6/sim/Makefile

when coverage is enabled, wrong dpi library is called due to missing space

cva6/sim/Makefile: fix typo introduced in 6500c38

---

.gitlab-ci/cva6.yml

Hello,
Two fixes in this PR:
- add timeout to benchmarks job which takes around 1h30 in CI
- fix path in wb_dcache job to find report_pass.py script
Guillaume

cva6.yaml: add timeout to benchmarks + fix in wb_dcache job

---

cva6/sim/Makefile
cva6/sim/cva6.yaml

Hello,
This PR fixes the vcs-gate target which was broken since the removal of the core only testbench. 
vcs-gate now uses vcs-uvm testbench to run post synthesis simulation. 
We can directly use vcs-uvm Makefile targets and remove old vcs-gate targets.
Guillaume

Use vcs-uvm Makefile target in vcs-gate iss

---

cv32e40x/tb/uvmt/uvmt_cv32e40x_tb.sv
lib/uvm_agents/uvma_rvfi/uvma_rvfi_instr_if.sv
lib/uvm_agents/uvma_rvfi/uvma_rvfi_tdefs.sv

Switched rvfi_trap in the tb if definition to the struct matching the core rvfi"

rvfi_trap changed to struct

---

cva6/sim/cva6.py

This allows the linking of correct libgcc version for tests that require libgcc support.
* cva6.py (load_config): Change ABI to FP-capable ones for all ISA configs that have floating-point extension(s) enabled.

Fix incorrect ABI settings in FP-capable simulation configurations.

---

tools/vptool/vptool/vp.py

This PR fixes an incorrect import in VPTOOL python code which caused issue #1341.
Files changed:
* tools/vptool/vptool/vp.py (OrderedDict): Import from 'collections', not from 'typing'.

Fix incorrect Python import (fixes issue #1341.)

---

cv32e40s/tb/uvmt/uvmt_cv32e40s_zc_assert.sv

As of version 20220328.14.0 or earlier, DSIM cannot accept localparams as arguments of properties.   Tracking as Metrics service request 1253.

Workaround for known DSIM issue

---

.gitlab-ci/cva6.yml

Fix for continuous integration
report_pass.py needs to be used from core-v-verif directory, not cva6 one. Thir PR fixes that.
@JeanRochCoulon @zchamski can you look at that ?
Guillaume

[CI]: cva6.yml: fix for wb_dcache job

---

.gitlab-ci/cva6.yml

FPGA build job take a little less than 1 hour to complete but sometimes it takes longer and fails due to timeout limit.
This should make that the job does not timeout anymore.

cva6.yml: Add timeout to 1h30 for FPGA build job

---

cv32e40s/tb/uvmt/uvmt_cv32e40s_constants.sv

As the title says, this PR adds more PMP configs.
Adding these configs because we wanted more variation in regressions (specifically G = {0, 1, >1} to stimulate generate blocks).
The other configs are picked semi-arbitrarily, with regards to PMA configs and the nature of PMP behavior and CSRs etc.

Add more pmp configs

---

mk/uvmt/dsim.mk

Several of the latest updates to the CV32E40S environment inadvertently trip over the DSIM issue mentioned in #1389.  This means MetricsCI is currently failing for that core.
Rather than continue to issue PRs similar to #1383 (and then have to back them out later), this PR will disable SVA compilation by DSIM (and only DSIM) for the CV32E40S (and only the CV32E40S).

(temporarily) disable SVA for the E40S

---

lib/uvm_agents/uvma_isacov/uvma_isacov_mon.sv

I replace the **get_field_imm** by **get_data_imm** method, and instead of passing constant argument of the **imm** field length (we can make some error in counting the field length),I used **$bits** to return automatically the length field. 
We can use the same logic for the rs1 & rs2, because in CVA6 rs1 & rs2 are 64bits length, but in CV32 are 32bits length.
I change also the signed field, instead of passing directlly the value, i used the type definition (**c_imm_is_signed**).

ISACOV: Fix issue #1414

---

cva6/sim/Makefile

Fix incorrect disassembling of 32-bit traces in presence of compressed instructions.  By default `spike-dasm` uses the RV64GC ISA to disassemble the raw opcodes.  However, on RV32C the bit patterns of several compressed instructions have a meaning different from the one on RV64(G)C.  Wit the default setting of `spike-dasm` these patterns were disassembled incorrectly in RV32C traces, resulting in trace comparison failures.
* cva6/sim/Makefile (target_isa): New variable.
(vcs-testharness): Pass ISA argument to DASM.
(veri-testharness): Ditto. (vcs-uvm): Ditto.
@ASintzoff , @JeanRochCoulon : Please review.

Instruct DASM to use the correct 32/64b ISA for current target.

---

cva6/sim/Makefile
cva6/sim/init_run_uvm_fsdb.do
cva6/sim/init_run_uvm_vpd.do

This PR adds a uniform support for waveform collection using Verilator and VCS.  ***It supersedes PR #1417 and PR #1424.***
Unless the previous version of the PR, there is no need anymore to modify the RTL in order to generate traces using Verilator.  Instead, command-line options to the verilated model control the generation of the waveform file. 
The PR introduces a scheme for controlling waveform generation both at the elaboration and the execution of simulation models in VCS- and Verilator-based environments.  The process of waveform generation is controlled by two environment variables:
* `TRACE_COMPACT` (default: empty): When non-empty, activates generation and collection of the most compact waveform format available on the given platform, usually at the expense of compilation and …

[tracing] Add uniform tracing support for VCS and Verilator.

---

cv32e40s/tests/cfg/b_ext_abs.yaml
cv32e40s/tests/cfg/b_ext_all.yaml
cv32e40s/tests/cfg/default.yaml
cv32e40s/tests/cfg/pma_test_cfg_1.yaml
cv32e40s/tests/cfg/pma_test_cfg_2.yaml
cv32e40s/tests/cfg/pma_test_cfg_3.yaml
cv32e40s/tests/cfg/pma_test_cfg_4.yaml
cv32e40s/tests/cfg/pma_test_cfg_5.yaml

Hello world and ci_check is broken. This PR fixes it by removing Zc from "march" in the cfg yamls, as that was pushed before the rest of the system has Zc enabled. I will be doing x-s merging and need clean points of comparison. If this is not merged into cv32e40s/dev now, then I will either have to juggle having lots of temporarily not-checked-in files at the same time as I am trying to hold track of the manual copy of untracked files from x to s and it will make the job a lot harder, or I can check it in to the local merging branch and then it will get merged into cv32e40s/dev later but with the disadvantage that it will happen more silently and hello world etc will not work in the meantime.
Passes ci_check, except for "debug_test" which was known to fail before.
@silabs-hfegran …

Fix ci_check and hello world

---

cv32e40s/sim/ExternalRepos.mk
cv32e40s/tb/uvmt/uvmt_cv32e40s_dut_wrap.sv
cv32e40s/tb/uvmt/uvmt_cv32e40s_interrupt_assert.sv
cv32e40s/tb/uvmt/uvmt_cv32e40s_tb.sv
cv32e40s/tb/uvmt/uvmt_cv32e40s_xsecure_assert.sv
cv32e40s/tests/cfg/no_bitmanip.yaml
cv32e40s/tests/cfg/num_mhpmcounter_29.yaml
cv32e40s/tests/cfg/pma.yaml
cv32e40s/tests/cfg/pma_debug.yaml
cv32e40s/tests/cfg/pmp.yaml
cv32e40s/tests/cfg/pmp_g3r3.yaml
lib/uvm_agents/uvma_rvvi_ovpsim/uvma_rvvi_ovpsim_agent.sv

Temporary fixes to get the integrity related signals to a non-blocking state. Work on obi_memory_agent and a thorough look at the signal connections in the wrappers required to solve these properly.

temporary fixes to integrity-related signals

---

cva6/sim/cva6.py

The cva6.py script use the YAML description to generate random tests, the problem here in the compressed instructions, actually these instructions are active by default, so to disable these instructions we should add an option in the YAML description (disable_compressed_instr=1), but in the **cva6.py** disable the compressed instructions when it detect the string **disable_compressed_instr** only, but what if we passed to disable_compressed_instr=0, that's means the C extension still active, so we need to modify the condition to disable compered inst only when **disable_compressed_instr=1**.

cva6.py : Disable compressed instruction when 'disable_compressed_instr=1'

---

cva6/docs/VerifPlans/FRONTEND/runme.sh
cva6/docs/VerifPlans/source/dvplan_FRONTEND.md
tools/vptool/vptool/vp.py
tools/vptool/vptool/vp_pack.py

Improve usability of VPTOOL, for now on CVA6 verification plans:
* [generic] Print all elements of a verification item in human-readable form, including the lists of applicable cores;
* [generic] Improve the selection and handling of markdown output directory;
* [CV32A6] Generate MD output for all items applicable to CV32A6-stage1, including those applicable to other cores;
* [CV32A6] Improve robustness of `FRONTEND` verification plan editing script;
* [CV32A6] Regenerate FRONTEND verif plan using updated VPTOOL.
* cva6/docs/VerfiPlans/source/dvplan_FRONTEND.md: Regenerate.
* tools/vptool/vptool/vp_pack.py (Item.attrval2str): New.
(Item.\_\_str__): Convert enumerated and bitmapped fields to associated plain text strings using labels from Yaml file.
* tools/vptool/vptool/vp.py …

[VPTOOL] Improve Markdown output.  Regenerate CV32A6 frontend verif plan and improve usability

---

cva6/docs/VerifPlans/FRONTEND/VP_IP003.pck
cva6/docs/VerifPlans/FRONTEND/runme.sh
cva6/docs/VerifPlans/FRONTEND/vp_config.py
cva6/docs/VerifPlans/VPTOOL-VerifPlan-HOWTO.md
cva6/docs/VerifPlans/source/dvplan_FRONTEND.md
tools/vptool/vptool/vp.py
tools/vptool/vptool/vp_pack.py

This PR adds extra flexibility in structuring DV plan database directories by allowing arbitrary directory structures and free-form strings in subsystem ("project") names.
It also adds support for preserving line breaks in free-form text fields of each verification item and introduces MD layout adjustments for improved readability.
An introductory HOWTO document outlining the process of configuring verification plan databases and generating human-friendly output is located in file `cva6/docs/VerifPlans/VPTOOL-VerifPlan-HOWTO.md`.
Two new variables are needed in `runme.sh` scripts of individual DV plans:
* `PROJECT_IDENT` should contain an identifier-like string (no whitespace, no special characters) that will be used to construct the name of the output MD file
* `MARKDOWN_OUTPUT_DIR` …

[VPTOOL+Markdown] Improve configurability of DV plans.

---

cva6/sim/Makefile
cva6/sim/cva6.yaml

This PR streamlines the handling of ISA variants when post-processing RTL simulationt output.  In particular, it should now seamlessly handle HW configurations with non-standard names (broken since commit c13b99ac).
In order to correctly disassemble the instruction trace, the RISC-V disassembler `dasm` needs to know the exact ISA variant used during the simulation (the same encodings can have distinct interpretations depending on `XLEN`.)  However, the guessing approach implemented in commit c13b99ac did not handle arbitrary target configuration names such as those used for `HW config` tests.
Use the same information passing mechanism as for `spike` simulations: the ISA variant is available in DV parameter `<variant>` and its value should be passed to the simulation Makefile upon invoking …

Clean up handling of ISA variants when disassembling RTL sim output.

---

cv32e40s/tb/uvmt/uvmt_cv32e40s_tb.sv

@silabs-hfegran does this make sense?
This PR excludes everything `rvvi` from formal.
Lets formal run again.
Passes ci_check **except** for `debug_test` (which has been known to fail for a while), `interrupt_test` and `illegal` also fails (but these also fail in vanilla 40s/dev now).

ImpDV Formal Fix

---

docs/VerifStrat/source/cv32_env.rst

A very quick-and-dirty update to the Verification Strategy document to remove some content that was hideously out-of-date.

[Skip CI] Update CV32E4 Chapter of VerifStrat

---

cva6/sim/cva6.py

+ increase timeout for c tests

cva6.py: change isa for cv32a60x target to support custom BSP

---

cv32e40s/fv/dummy_pkg.sv
cv32e40s/tb/uvmt/uvmt_cv32e40s_debug_assert.sv
cv32e40s/tb/uvmt/uvmt_cv32e40s_tb.sv
cv32e40s/tb/uvmt/uvmt_cv32e40s_tb_ifs.sv
cv32e40s/tests/programs/custom/debug_test/debug_test.c
lib/uvm_agents/uvma_rvfi/uvma_rvfi_instr_if.sv

This work is by no means finished, but I suggest we merge this now for the following two reasons:
~~1. an assert added in this PR is required to reproduce cv32e40x issue [709](https://github.com/openhwgroup/cv32e40x/issues/709)~~ (bug was in the assert, not RTL)
2. New functions in rvfi_instr_if could be useful for other contributors to the 40s/dev
edit: A new bug has been found by asserts added to this PR: [cv32e40x 711](https://github.com/openhwgroup/cv32e40x/issues/711)

started the process of updating debug assertion set to latest spec

---

cv32e40s/env/uvme/cov/uvme_debug_covg.sv
cv32e40s/tb/uvmt/uvmt_cv32e40s_debug_assert.sv

PR #1515 had syntax errors that wasn't picked up in formal, but crashes sim. This PR fixes that.

fixes to debug_assert for simulation

---

cv32e40s/tb/uvmt/uvmt_cv32e40s_clic_interrupt_assert.sv
cv32e40s/tb/uvmt/uvmt_cv32e40s_pmp_assert.sv
cv32e40s/tb/uvmt/uvmt_cv32e40s_pmprvfi_assert.sv
cv32e40s/tb/uvmt/uvmt_cv32e40s_rvfi_assert.sv

This PR adds `uvm_error` to PMP assertions, so that the UVM error system can pick up failures in sim.
This change does not include functional changes so I only tested that formal still runs and that hello world still passes.
_(Also touching "clic_interrupt_assert" and "rvfi_assert" because there were a few missing uvm_error there too._)

PmpAssert - Add "uvm_error"

---

cv32e40s/sim/ExternalRepos.mk
cv32e40s/tb/uvmt/uvmt_cv32e40s_debug_assert.sv
cv32e40s/tb/uvmt/uvmt_cv32e40s_tb.sv
cv32e40s/tb/uvmt/uvmt_cv32e40s_tb_ifs.sv

Pulled in latest core and split debug_pending signal in sync and async to match the updated rtl.

Pull in latest 40s core rtl

---

cv32e40s/tb/uvmt/uvmt_cv32e40s_imperas_dv_wrap.sv

Updated dv wrapper to use the rvfi_gpr_* signals to inform the ISS about register writes. Necessary to support multiop instructions

fixed dv connection for gpr writes to support multiop instructions

---

cv32e40s/tb/uvmt/uvmt_cv32e40s_fencei_assert.sv
cv32e40s/tb/uvmt/uvmt_cv32e40s_tb.sv

This PR adds one assert to the fencei assertion set.
As mentioned by @silabs-oysteink, there is a problem that the RTL treats `fence` as `fencei`.
The original fencei asserts probed some internal signals and did not double check against RVFI!
@silabs-mateilga, @silabs-krdosvik, @MikeOpenHWGroup, I would appreciate a review and merge. (Very little code to review.)

FenceiAssert - Check Handshake vs RVFI

---

cv32e40s/tb/core/cv32e40s_tb_wrapper.sv
cv32e40s/tb/core/tb_top_verilator.sv
cv32e40s/tests/programs/custom/hpmcounter_basic_nostall_test/hpmcounter_basic_nostall_test.c
cv32e40s/tests/programs/custom/hpmcounter_basic_test/hpmcounter_basic_test.c
cv32e40s/tests/programs/custom/hpmcounter_hazard_test/hpmcounter_hazard_test.c

Removed hpmcounter testing from performance counter tests (currently named hpmcounter_*_test, will rename in separate PR).
Removed NUM_MHPMCOUNTER parameter which does not exist in RTL for 40s.

Remove remains of hpmcounters

---

cv32e40s/tb/uvmt/uvmt_cv32e40s_xsecure_assert.sv

RTL is updated, so must the assertions.
Change: take into account the reset value of a CSR register when shadowing the CSR.

CSR hardening update, because rtl is updated

---

cv32e40s/tb/uvmt/uvmt_cv32e40s_tb.sv
cv32e40s/tb/uvmt/uvmt_cv32e40s_tb_ifs.sv
cv32e40s/tb/uvmt/uvmt_cv32e40s_xsecure_assert.sv

The vmanager is down, but test passes hello-world simulation at least.
Changes:
1) Made one assertion for each CSR.
2) Changed signals used to check CSR values
3) Changed logic to check if csr and shadow are complements of eachother.

Csr hardening update 2

---

tools/vptool/vptool/vp.py
tools/vptool/vptool/vp_pack.py

This PR extends `VPTOOL` with GUI and database format support for:
* Precise *Requirement Location* references (down to section or page number);
* Direct viewing of requirement/design document at the specified location using either an HTML browser (for PDF file URLs) or a PDF viewer (for local files).
This is an initial implementation of the feature: all feedback and comments are welcome and encouraged.

[VPTOOL] Add support for precise requirement locations and requirement/design doc viewing.

---

cva6/docs/VerifPlans/source/conf.py
cva6/regress/install-cva6.sh
cva6/regress/install-verilator.sh
cva6/regress/install-vptool-deps.sh

Bootcamp: Update CVA6 baseline, reduce jobs, install VPTOOL deps.
* cva6/regress/install-cva6.sh (NUM_JOBS): Reduce from 24 to 3.
(CVA6_HASH): Update to 32abc1cc.
Invoke installer of VPTOOL deps.
* cva6/regress/install-vptool-deps.sh: New.
VerifPlan rendering: Gracefully handle not-equal Unicode char in LaTeX.
* cva6/docs/VerifPlans/source/conf.py: Translate U+2260 into \neq in LaTeX preamble.
[VerifPlan rendering] Enable collapsable nagivation menu in HTML5 output.
* cva6/docs/VerifPlans/source/conf.py: Explicitly import sphinx_rtd_theme.
Disable 'collapse_navigation' option.

Simplify installation of CVA6 environment.

---

cva6/sim/Makefile

The VCS path is currently hard coded. Use the `VCS_HOME` environment variable instead. `VCS_HOME` is required by VCS itself, so it should already be set in the environment calling this script.

cva6/sim/Makefile: Use VCS_HOME env variable

---

cv32e40s/sim/ExternalRepos.mk
cv32e40s/tb/uvmt/uvmt_cv32e40s_constants.sv
cv32e40s/tb/uvmt/uvmt_cv32e40s_dut_wrap.sv
cv32e40s/tb/uvmt/uvmt_cv32e40s_tb.sv

This PR adds missing parameters to `_constants.sv` and `dut_wrap`, as well as facilitating for defining these parameters in an external file not checked into this repo.
ci_check passes as much as it does for cv32e40s/dev.
Formal is still runnable.

Core Params - Add missing & Add external config

---

cv32e40s/tb/uvmt/uvmt_cv32e40s_debug_assert.sv
cv32e40s/tb/uvmt/uvmt_cv32e40s_tb.sv
lib/uvm_agents/uvma_rvfi/uvma_rvfi_instr_if.sv

Another stepping stone towards getting the debug asserts up to speed again. Updates the pc_dpc-assert, and several ebreak-related asserts to RVFI timing.
Status of the assertion set is still "under development", but I'd like to PR now to accommodate efforts from other engineers coming in, and sharing expansions of the helper functions in rvfi_instr_if. 
A no-merge decision on this PR is fine, but I think the pros outweigh the cons.

Continued work on debug asserts

---

cv32e40s/tb/uvmt/uvmt_cv32e40s_constants.sv

This PR lets a "param_set_1" to be externally defined, to test a complement of "param_set_0".
@silabs-hfegran 
--------
_(Side note: I am actually in favor of removing the "else" clauses of the constants file, because they are pitfalls for when one forgets to set something in a config. I think the elses might be a bigger danger/inconvenience than they are a convenience. But that is a different discussion.)_

Core Params - Allow additional external config

---

mk/uvmt/vcs.mk
vendor_lib/imperas/imperas_DV_COREV/sv/imperas_CV32.sv

In the vcs.mk file,
> 1. Delete some duplicate options in the VCS compilation option, VCS_UVM_ARGS variables appear twice
https://github.com/openhwgroup/core-v-verif/compare/cv32e40p/dev...guojiazhuxi:core-v-verif:ultichip_guojiazhuxi_20230207?diff=unified#diff-14ee28fc032c3c15e468d11a3547d65122b2c76198bfd629f3e38055633275eeL53-L55
https://github.com/openhwgroup/core-v-verif/compare/cv32e40p/dev...guojiazhuxi:core-v-verif:ultichip_guojiazhuxi_20230207?diff=unified#diff-14ee28fc032c3c15e468d11a3547d65122b2c76198bfd629f3e38055633275eeR182-R185
> 2. +UVM_VERBOSITY= $ (VCS_UVM_VERBOSITY) option is not the compilation option of VCS, but the option of ./simv.
https://github.com/openhwgroup/core-v-verif/compare/cv32e40p/dev...guojiazhuxi:core-v-verif:ultichip_guojiazhuxi_20230207?diff=unified#dif …

fix vcs.mk and imperas_CV32.sv problem

---

cv32e40p/sim/tools/vcs/vcs_wave.tcl
mk/uvmt/vcs.mk

@MikeOpenHWGroup Add a vcs compilation function
dump memory arrays to fsdb file. Using it, you can tracer two-dimensional arrays and memory signals in verdi.

dump memory arrays to fsdb

---

cva6/sim/cva6_spike_log_to_trace_csv.py

Spike output have been updated in latest releases
register index is now left align with space padding

Update spike log parsing

---

.gitlab-ci/setup-ci-example/core-v-verif-cv32.yml
.gitlab-ci/setup-ci-example/core-v-verif-cva6.yml

The scripts expect `TESTS_BRANCH` and `TESTS_HASH`:
https://github.com/openhwgroup/core-v-verif/blob/6113f4f179645eb05c4178b6ec25be316a9a1aa8/cva6/regress/install-riscv-tests.sh#L21-L22

setup-ci-example: Fix typo

---

lib/dpi_dasm/README.md

> > Maybe we could link to https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/decode.h in the lib/dpi_dasm/ readme?
> 
> Good idea! Can you take care of that in a separate PR @silabs-robin?
https://github.com/openhwgroup/core-v-verif/issues/1582#issuecomment-1416380145

Isacov - Link to "decoder.h" in Readme

---

cv32e40s/fv/qverify.tcl

This PR adds a few constraints to the Questa Formal setup. (Rationale below.)
I think I figured out why the counter-examples looked so nonsensical.
At first I thought it was a problem with the reset initialization sequence, but it was only partially that...
"Free nets" seems to be treated differently in Jasper and Questa. Jasper goes "it's a free net, it can do whatever, and Questa goes "this is not a valid control point, whoops there goes gravity".
Free nets needs to be turned into valid "control points", and one can do that by explicitly setting a cutpoint.
Before this change you could get e.g. rvfi_valid on cycle 0 and all kinds of weird behavior that seems to completely ignore what is written in the rtl.

Questa Formal - "Design Checks" Fix

---

lib/uvm_agents/uvma_obi_memory/src/uvma_obi_memory_assert.sv

This PR swaps out a dynamic array in the obi memory asserts with a packed array and rewrites the accompanying logic, so that these asserts can be used in formal.
Note: This is in "lib/" so it will affect other cores.
Note: The asserts are already bound in the tb but were not used in fv.
Passes ci_check (except for known debug test).
Runs in formal, and the assert in question passes.

OBI Asserts - Make Formal-Friendly

---

cv32e40s/tb/uvmt/uvmt_cv32e40s_rvfi_assert.sv
cv32e40s/tb/uvmt/uvmt_cv32e40s_tb.sv
mk/uvmt/xrun.mk

This PR updates rvfi_assert to keep up with changes to the core and the environment.
Passes ci_check (except you know).
The asserts in question passes in formal.

RVFI Assert - Fix CEXes

---

cv32e40s/tb/uvmt/uvmt_cv32e40s_pmp_assert.sv
cv32e40s/tb/uvmt/uvmt_cv32e40s_pmp_model.sv
cv32e40s/tb/uvmt/uvmt_cv32e40s_pmprvfi_assert.sv
cv32e40s/tb/uvmt/uvmt_cv32e40s_tb.sv
cv32e40s/tb/uvmt/uvmt_cv32e40s_tdefs.sv

This PR fixes some CEXes in the PMP asserts, mostly related to the new DM_REGION_START/END.
Passes in formal.
Passes ci_check (except debug_test) BUT ONLY AFTER https://github.com/openhwgroup/core-v-verif/pull/1631 IS MERGED.

PMP Assert - Fix CEXes

---

lib/uvm_agents/uvma_core_cntrl/uvma_core_cntrl_cfg.sv

In order to keep the boot_addr values in green, the best way i think to add a constraint the core control agent config file.

Core cntrl Agent : Add a constraint related to boot_addr value

---

cv32e40p/tests/programs/custom/pulp_bit_manipulation/pulp_bit_manipulation.S
cv32e40p/tests/programs/custom/pulp_vectorial_shuffle_pack/pulp_vectorial_shuffle_pack.S
mk/Common.mk

All 19 tests are then correctly running on CV32E40Pv2 and 20230217 corev Embecosm toolchain.

2 PULP tests corrections

---

cva6/env/uvme/uvma_cva6_core_cntrl_agent.sv
cva6/env/uvme/uvma_cva6_core_cntrl_cntxt.sv
cva6/env/uvme/uvma_cva6_core_cntrl_drv.sv
cva6/env/uvme/uvme_cva6_cfg.sv
cva6/env/uvme/uvme_cva6_cntxt.sv
cva6/env/uvme/uvme_cva6_constants.sv
cva6/env/uvme/uvme_cva6_core_cntrl_if.sv
cva6/env/uvme/uvme_cva6_env.sv
cva6/env/uvme/uvme_cva6_pkg.sv
cva6/sim/Makefile
cva6/tb/uvmt/cva6_tb_wrapper.sv
cva6/tb/uvmt/uvmt_cva6.flist
cva6/tb/uvmt/uvmt_cva6_constants.sv
cva6/tb/uvmt/uvmt_cva6_dut_wrap.sv
cva6/tb/uvmt/uvmt_cva6_tb.sv

The following PR related to re-use of the existent core control agent.
Things to Know :
The CVA6 has only the **boot_addr** as an input of the signals in the core control agent, so the other signals have no effect.
The **fetch_toogle_seq** as @MikeOpenHWGroup mention was added to verify a requirement of the embedded cores.
We can change the **boot_addr** value from the **uvme_cva6_cfg**.sv file, or add a simulation option +boot_addr = (some value), with that you should give the same value to spike (add a [cva6.py](https://github.com/openhwgroup/core-v-verif/blob/cva6/dev/cva6/sim/cva6.py) option : **--isspostrun_opts**=some value ) and the [linker ](https://github.com/openhwgroup/core-v-verif/blob/cva6/dev/cva6/sim/link.ld) to guaranty that your test run very well, you should know also …

Re-use Core control Agent

---

cva6/regress/install-cva6.sh

This PR is a help for tracking configuration issues in automated CI.  When installing a CVA6 RTL tree, it prints on console the actual commit extracted from the cva6 repo clone.
Changed files:
* cva6/sim/install-cva6.sh: Print the commit which was checked out upon installing a fresh CVA6 RTL tree.

Track cva6 commit upon install

---

cva6/tests/testlist_riscv-compliance-cv32a60x.yaml
cva6/tests/testlist_riscv-compliance-cv32a6_imac_sv0.yaml
cva6/tests/testlist_riscv-compliance-cv64a6_imafdc_sv39.yaml
cva6/tests/testlist_riscv-compliance-rv32ima.yaml

as https://github.com/openhwgroup/cva6/issues/421 is fixed

CVA6 testlist_riscv-compliance-*.yaml: enable DIV and REM tests

---

bin/xlsx2csv.py
cv32e40s/docs/VerifPlans/Simulation/privileged_spec/CV32E40S_UserMode.csv

This PR adds a script to convert vplans from ".xlsx" to ".csv".
To be able to see a diff of vplan changes, it was proposed to save csv files next to the original spreadsheet files.
The reason for the script is that Excel has severe localization quirks that makes it practically impossible to do reliably from their gui.
For europeans defaulting to a ";" delimiter, a simple substitution of `s/,/;/g` is enough to make it workable.
There is also included an example on the UserMode Vplan.
Note: If you click "View file" on the csv, Github actually renders it correctly.
Example diff: https://github.com/silabs-robin/core-v-verif/compare/vplan_csv...silabs-robin:core-v-verif:vplan_csv_demo

CSV Vplans

---

bin/cv_regress
bin/lib/cv_regression.py
bin/templates/regress_rmdb.j2
cv32e40p/sim/tools/vsim/cov.tcl
mk/Common.mk
mk/uvmt/vsim.mk

Added the needed templates to allow the generation of a RMDB File. 
Due to limitations of Questa Vrun, make sure to generate the rmdb file with coverage enabled, as the regression tool is not able to easily detect a failing make command as a test fail. It needs indeed to have access to an .ucdb file with the test status recorded inside. 
Also, Siemens tools expects one unique "testname" when merging ucdb, so tests that are executed with multiple configurations and seeds provoked an issue when merging. I was forced to update some coverage commands and script to solve this. 
I also updated one small thing to cv_regress script, to allow the same test to be executed in multiple configurations inside the same regression. That will be useful for handling all F/Zfinx tests that will be …

cv_regress script to generate regressions for Siemens verification manager tool

---

cva6/regress/install-riscv-arch-test.sh
cva6/regress/riscv-compliance.patch
cva6/regress/riscv-tests-env.patch
cva6/regress/smoke-tests.sh
cva6/tests/custom/common/crt.S
cva6/tests/testlist_riscv-arch-test-cv32a60x.yaml
cva6/tests/testlist_riscv-arch-test-cv64a6_imafdc_sv39.yaml

This PR aims at streamlining the handling of termination sequences so that they systematically use the RISC-V HTIF convention of writing an odd value into variable `tohost`.
The termination sequence cannot reliably stop on a `wfi` instruction because in CVA6 its behavior depends on the current privilege level and even the presence of alarms.  Therefore, the write of the termination value into `tohost` is followed by a jump-to-self loop.  As a consequence, the testbench is resposible for detecting the writes into `tohost` and for eventually stopping the simulation when the bit 0 of `tohost` was set.
This PR addresses the code generation side of test termination.  It does so by modifying the patches (`riscv-tests`, `riscv-compliance`), the installation scripts (`riscv-isa-sim`), and by …

Test termination: Streamline the definitions of termination sequences.

---

cv32e40s/regress/cv32e40s_ci_check.yaml
cv32e40s/tests/programs/custom/interrupt_test/interrupt_test.c

In the past this test most likely passed without running advertised functionality, and a change of compiler exposed the (many) latent problems within. Fixed by adding volatiles to variables to prevent the compiler from optimizing away central parts of the test. As the full test takes approximately 1.5 hours it has been removed from the ci_check regression list.
Note: There will be unknown exception handler entered messages printed during the last part of the test - this is due to common BSP code that is not overridden in the test.

Fixed interrupt_test, removed from ci_check due to excessive run time

---

cv32e40s/tb/uvmt/uvmt_cv32e40s_imperas_dv_wrap.sv

The addition of trace2cov allows functional coverage using riscvISACOV to be used
Clone the repository github.com/Imperas/ImperasDV-OpenHW and view the file scripts/cv32e40s/README.run.txt for full information on how to enable
No additional System Verilog is included unless it is compiled with +define+INCLUDE_TRACE2COV
Some information is included here 
```
COVERAGE_ENABLE="\
+define+INCLUDE_TRACE2COV \
+incdir+${IMPERAS_HOME}/ImpProprietary/source/host/riscvISACOV/source \
+define+COVER_BASE_RV32I \
+define+COVER_LEVEL_DV_PR_EXT  \
+define+COVER_RV32ZCA \
+define+COVER_RV32ZCMP \
+define+COVER_RV32ZCMT \
"
export CV_SW_MARCH=rv32im_zicsr_zifencei_zcmp
make clean test TEST=zc_test \
USER_COMPILE_FLAGS="${COVERAGE_ENABLE}" \
USER_RUN_FLAGS="+TRACE2COV_ENABLE=1" \
USE_ISS=yes \
COV=yes \ …
```

Include Imperas DV Functional Coverage

---

cva6/regress/install-riscv-arch-test.sh
cva6/regress/install-riscv-compliance.sh
cva6/regress/install-riscv-dv.sh
cva6/regress/install-riscv-tests.sh

Update repository URL of the `riscv-compliance` suite and improve messages describing the actual configuration used to instantiate individual test suites.
* cva6/regress/install-riscv-arch-test.sh: Improve installation messages.
* cva6/regress/install-riscv-compliance.sh: Update repo URL.  Improve installation messages.
* cva6/regress/install-riscv-dv.sh: Improve installation messages.
* cva6/regress/install-riscv-tests.sh: Likewise.

Update installation flow of test infrastructure.

---

cva6/env/corev-dv/cva6_asm_program_gen.sv

Hello, I add in the [cva6_asm_program_gen.sv](https://github.com/openhwgroup/core-v-verif/blob/cva6/dev/cva6/env/corev-dv/cva6_asm_program_gen.sv) file, the gen_test_done function to implement the new end of test mechanism, so to use it you should add in the cmd line : **--sim_opts="+uvm_set_inst_override=riscv_asm_program_gen,cva6_asm_program_gen_c,'uvm_test_top.asm_gen'"** to override the original RISCV-DV class with the new one.

Add new mechanism of the end of test for generated tests

---

cv32e40s/env/uvme/vseq/uvme_cv32e40s_random_debug_bootset_vseq.sv

Stretched bootset debug request to ensure it is picked up by the core now that the request is no longer sticky.
This should at some point be updated to handshake the request with the debug_halted_o signal from the core (assert debug_req until debug_halted_o goes high) but increasing the pulse width will do for now, as it causes ~20 tests to fail in regressions.

Stretched bootset debug request

---

cv32e40s/tb/uvmt/support_logic/uvmt_cv32e40s_support_logic.sv
cv32e40s/tb/uvmt/uvmt_cv32e40s_debug_assert.sv
cv32e40s/tb/uvmt/uvmt_cv32e40s_pma_assert.sv
cv32e40s/tb/uvmt/uvmt_cv32e40s_tb.sv
cv32e40s/tb/uvmt/uvmt_cv32e40s_triggers_assert_cov.sv
lib/uvm_agents/uvma_rvfi/uvma_rvfi_instr_if.sv

To help with debugging and waveforms, we have decided that we want signal aliases of the "is_*()" functions of the the rvfi_instr_if. This PR adds those, changes the use in several assertion sets from function to signal, and renames the functions to keep them separate. The _array helper signals have also been fixed, as the previous implementation could cause problems.

Added signal aliases the rvfi helper functions

---

.metrics.json
bin/ci_check
cv32e40s/regress/cv32e40s_ci_check.yaml

ci_check only ran with the default configuration, and did not take yaml-specified builds into account. 
This should be working properly with this commit
- Caveat/TODO: This commit will build all the configurations specified in the metrics yaml, some of which will fail. Scripts should be updated to only build the necessary ones. The failing non-related builds have no functional impact on ci_check results.

Updated ci_check script to take yaml cfgs into account

---

cv32e40s/env/corev-dv/cv32e40s_zcmt_instr_lib.sv
cv32e40s/tests/cfg/clic_default.yaml
cv32e40s/tests/cfg/default.yaml
cv32e40s/tests/cfg/pma_test_cfg_1.yaml
cv32e40s/tests/cfg/pma_test_cfg_2.yaml
cv32e40s/tests/cfg/pma_test_cfg_3.yaml
cv32e40s/tests/cfg/pma_test_cfg_4.yaml
cv32e40s/tests/cfg/pma_test_cfg_5.yaml
cv32e40s/tests/programs/corev-dv/corev_rand_data_obi_err/corev-dv.yaml
cv32e40s/tests/programs/corev-dv/corev_rand_data_obi_err_debug/corev-dv.yaml
cv32e40s/tests/programs/corev-dv/corev_rand_illegal_instr_test/corev-dv.yaml
cv32e40s/tests/programs/corev-dv/corev_rand_instr_long_stall/corev-dv.yaml
cv32e40s/tests/programs/corev-dv/corev_rand_instr_obi_err/corev-dv.yaml
cv32e40s/tests/programs/corev-dv/corev_rand_instr_obi_err_debug/corev-dv.yaml
cv32e40s/tests/programs/corev-dv/corev_rand_instr_test/corev-dv.yaml
cv32e40s/tests/programs/corev-dv/corev_rand_interrupt/corev-dv.yaml
cv32e40s/tests/programs/corev-dv/corev_rand_jump_stress_test/corev-dv.yaml

This PR introduces zcmt to riscv-dv randomtesting and enables zcmt compiler flags for all? relevant configurations. 
Note: This _requires_ updated compiler support, tested with: corev-openhw-gcc-centos7-20230310

Enable Zcmt support in core-v-verif tests

---

cv32e40s/tb/uvmt/uvmt_cv32e40s_triggers_assert_cov.sv

Fixed bit-width of wb_exception_code in triggers_assert_cov, gets rid of compilation warning.

Fixed bit-width of wb_exception_code in triggers_assert_cov

---

cv32e40s/sim/tools/xrun/covfile.tcl

Enable coverage collection flags for
type parameterized modules and interfaces
coverage expressions with `inside` operator

Enable coverage collection flags

---

cv32e40s/sim/ExternalRepos.mk
cv32e40s/tb/uvmt/uvmt_cv32e40s_debug_assert.sv
lib/uvm_agents/uvma_rvfi/uvma_rvfi_instr_if.sv
lib/uvm_agents/uvma_rvfi/uvma_rvfi_tdefs.sv

RVFI will now report a trap when a clic pointer fetch fails synchronously, indicated by the new signal rvfi_trap.clicptr. This PR updates core-v-verif to deal with this.

Rvfi clicptr adaptions

---

cv32e40p/tests/programs/custom/coremark/core_list_join.c
cv32e40p/tests/programs/custom/coremark/core_main.c
cv32e40p/tests/programs/custom/coremark/core_matrix.c
cv32e40p/tests/programs/custom/coremark/core_state.c
cv32e40p/tests/programs/custom/coremark/core_util.c
cv32e40p/tests/programs/custom/coremark/coremark.h
cv32e40p/tests/programs/custom/coremark/test.yaml
cv32e40s/tests/programs/custom/coremark/core_list_join.c
cv32e40s/tests/programs/custom/coremark/core_main.c
cv32e40s/tests/programs/custom/coremark/core_matrix.c
cv32e40s/tests/programs/custom/coremark/core_state.c
cv32e40s/tests/programs/custom/coremark/core_util.c
cv32e40s/tests/programs/custom/coremark/coremark.h
cv32e40s/tests/programs/custom/coremark/test.yaml
cv32e40x/tests/programs/custom/coremark/core_list_join.c
cv32e40x/tests/programs/custom/coremark/core_main.c
cv32e40x/tests/programs/custom/coremark/core_matrix.c
cv32e40x/tests/programs/custom/coremark/core_state.c
cv32e40x/tests/programs/custom/coremark/core_util.c
cv32e40x/tests/programs/custom/coremark/coremark.h
cv32e40x/tests/programs/custom/coremark/test.yaml

This PR is the first step to resolve #1623.
It updates all of the Coremark license headers in `core-v-verif/<core>/tests/programs/custom/coremark` to remove the OpenHW/SiLabs copyright from unmodified files.
@christian-herber-nxp, if/when you sign off on this I will make the same changes to the `cv32e20` branch.

Remove OpenHW/SiLabs copyright headers from unmodified Coremark files

---

lib/uvm_agents/uvma_obi_memory/src/uvma_obi_memory_1p2_assert.sv

This PR adds parity asserts (reqpar, etc) to the OBI assertion set, according to [OBI v1.2](https://raw.githubusercontent.com/openhwgroup/obi/main/OBI-v1.2.pdf).
Test status:
* ci_check - Passes
* Internal formal - N/A, not used (passes when enabled)
* Cvverif formal - Works as expected (core-side pass, env-side fail)
I did not expect to write this today, but I wanted to see if one of the latest RVFI bug fixes were reproducable with the core-v-verif formal setup and this is the only piece missing that I'm aware of. _(OBI parity assumes were already in cvverif fv, but lazily used xsecure asserts.)_

OBI Assert - Parity

---

.gitlab-ci/cva6.yml
cva6/regress/install-cva6.sh
cva6/regress/install-spike.sh
cva6/regress/install-verilator.sh
cva6/regress/verilator-v5.patch
cva6/sim/Makefile

This PR introduces support for Verilator v5 (v5.008 at the time of PR creation).  The main modifications are:
*  A change in the use of shell variables to configure Verilator:
* In Verilator v5, `VERILATOR_ROOT` is required to point to the root of the _source_ tree of Verilator
* A separate variable (currently named `VERILATOR_INSTALL_DIR`) is needed to designate the installation directory of Verilator
* If not defined explicitly by the user, `VERILATOR_INSTALL_DIR` is set to the parent directory of `$VERILATOR_ROOT`.
* Path settings for Verilator-related executables and include files are expressed using `$VERILATOR_INSTALL_DIR`. 
* A change in the build flow of Verilator: instead of downloading and untarring a source package tarball, the source code is cloned from Verilator Github …

Switch Verilator testing to use v5.008 instead of v4.110

---

cva6/tests/custom/common/syscalls.c

The print happens after main() has finished if csrr was read via getStats() in main(), e.g. while running benchmarks.
The print is not possible at the moment and triggers a simulation fail.

fix: optionally remove bad print after csrr mcycle

---

cv32e40p/tb/uvmt/uvmt_cv32e40p.flist
cv32e40p/tb/uvmt/uvmt_cv32e40p_tb.sv
mk/uvmt/xrun.mk

This PR restores the functionality of the `USE_ISS` Makefile variable.  Setting this variable to "NO" on any `make test` invocation will compile the environment excluding the ImperasDV model.  For example:
```
$ make test TEST=hello-world USE_ISS=NO
```

Optional compile of ImperasDV

---

cv32e40x/sim/core/Makefile
cv32e40x/sim/core/README.md
cv32e40x/tb/core/cv32e40x_tb_wrapper.sv
cv32e40x/tb/core/mm_ram.sv

This PR is to set up the  "core" testbench for E40X core.  Related issues could be #1777, #1259. 
The major modifications include:
1. cv32e40x/sim/core/Makefile:  Some redefinition of variables. Remove  redundant variable that have the same function(e.g., `CUSTOM` with `TEST_PROGRAM_PATH`, `CUSTOM_PROG` with `TEST`).
2. cv32e40x/tb/core/cv32e40x_tb_wrapper.sv: Correct the instance of cv32e40x core.
3. cv32e40x/tb/core/mm_ram.sv: Remap the virtual peripheral registers according to [corev_uvmt.h](https://github.com/openhwgroup/core-v-verif/blob/master/cv32e40x/bsp/corev_uvmt.h). 
4. cv32e40x/sim/core/readme.md: Update the usage of makefile commands.
Only verilator 5.008 and vsim 2021 were tested.  For verilator,  try `make veri-test TEST=hello-world`  in `cv32e40x/sim/core/` path to …

Add support for E40X core simulation using Verilator/Questa Vsim

---

cv32e40s/tests/programs/custom/interrupt_bootstrap/interrupt_bootstrap.c

Fixed stack issues in interrupt bootstrap test caused by unsafe c/inline assembly mix.
Also made indentation consistent throughout the file (w/2 spaces).

Fixed stack issues in interrupt bootstrap test

---

mk/uvmt/dsim.mk
mk/uvmt/vcs.mk
mk/uvmt/vsim.mk
mk/uvmt/xrun.mk

This pull-request is a fix for an issue reported #1656.
The Makefile target `dpi_dasm` requires a path to the simulator tool-specific DPI libraries.  This is both tool (xrun, vcs, etc.) and installation dependent, so it needs to be placed in `mk/uvmt/<simulator>.mk`.  These simulator tool-specific Makefiles are required to set variable `DPI_INCLUDE`.  It was not set properly VCS.
This PR sets `DPI_INCLUDE` for VCS and DSIM and adds a comment to XRUN and VSIM simulator makefiles.

Fix include path to tool-specific DPI libs

---

lib/uvm_agents/uvma_rvfi/uvma_rvfi_constants.sv
lib/uvm_agents/uvma_rvfi/uvma_rvfi_instr_if.sv

The current `uvma_rvfi` is locked to only work with the 40s.
This PR removes that dependency.
Test status:
* Hello world passes

UVMA RVFI - Remove 40s-dependency

---

cv32e40s/tests/programs/custom/interrupt_priv_test/interrupt_priv_test.c

Fixed non-volatile variable getting corrupted by printf compiler optimization.

Fixed stack issues in interrupt_priv_test

---

lib/uvm_agents/uvma_rvfi/uvma_rvfi_constants.sv
lib/uvm_agents/uvma_rvfi/uvma_rvfi_instr_if.sv

Sorry for doing this again, but there came in another PR merge (my own) which reintroduced the 40s dependency.
Ref: https://github.com/openhwgroup/core-v-verif/pull/1823
Test status:
* Hello world passes

UVMA RVFI - Remove 40s-dependency (again)

---

cva6/env/uvme/uvme_cva6_cfg.sv
cva6/env/uvme/uvme_cva6_env.sv
cva6/sim/cva6.py
cva6/tb/core/tb_components/axi_master_connect.sv
cva6/tb/uvmt/cva6_tb_wrapper.sv
cva6/tb/uvmt/uvmt_axi_switch_intf.sv
cva6/tb/uvmt/uvmt_cva6_dut_wrap.sv
cva6/tb/uvmt/uvmt_cva6_pkg.sv
cva6/tb/uvmt/uvmt_cva6_tb.sv
cva6/tests/uvmt/base-tests/uvmt_cva6_base_test.sv

This commit allows to us switch the axi_agent mode without changing any part of code.
There is two way to change the agent mode: 
First way: From env_cfg we can change the variable axi_cfg.is_active to UVM_PASSIVE or UVM_ACTIVE.
Second:   From command line by using --axi_active option.

Adapt the environment and test-bench to execute the AXI agent in active/passive mode

---

.github/workflows/dashboard-done.yml
.gitlab-ci/scripts/github_integration.py
.gitlab-ci/scripts/merge_job_reports.py

Pull requests targeting branch [`cva6/dev`](https://github.com/openhwgroup/core-v-verif/tree/cva6/dev) trigger jobs on [an external infrastructure](https://riscv-ci.pages.thales-invia.fr/dashboard/dashboard_core-v-verif_0.html). However, results are not easily accessible from the GitHub PR.
To make it easier for PR authors and reviewers to access the results of these jobs, the external infrastructure will send a comment in the PR with a link to the job results when they are available. It is done in a two-step process:
So that the comment is created by a bot and not a specific individual, the comment should be created [by a workflow](https://github.com/openhwgroup/core-v-verif/pull/1810/files#diff-8dc0736c177c4c030c66c3fc1fc15282e2faf57a598fe80993f53648cacb6b7b). This new workflow is …

ci: notification from Dashboard

---

cva6/tb/uvmt/cva6_tb_wrapper.sv

DROMAJO has been removed from CVA6.
This is a hotfix to make thales ci work !

Remove DROMAJO

---

cv32e40s/env/uvme/uvme_cv32e40s_buserr_sb.sv

Bus error scoreboard: Added checking for whether a valid instruction fetch is in the pipeline when looking for error addresses in rvfi transactions.
This PR makes false errors less likely but does not fix the underlying issue which is that the scoreboard uses addresses to identify transactions between rvfi and obi. This is an issue because multiple transactions can have the same address.

Relaxed bus error scoreboard check

---

lib/uvm_agents/uvma_isacov/cov/uvma_isacov_cov_model.sv
lib/uvm_agents/uvma_isacov/uvma_isacov_instr.sv
lib/uvm_agents/uvma_isacov/uvma_isacov_mon.sv

Hello, 
So as we discus a log time about this issue, and we end up with the idea that we need a **core-v-decoder**, but isn't that easy for now, I made a fix related to the issue, Please have a look at it.
Also I did a second commit to remove the rd filed from the coverage model, for c.jr & c.jalr as we discuss in the issue 1444

ISACOV : Fix #1425

---

bin/README.md
bin/cv_regress
bin/templates/regress_rmdb.j2
mk/uvmt/dsim.mk
mk/uvmt/riviera.mk
mk/uvmt/vcs.mk
mk/uvmt/vsim.mk
mk/uvmt/xrun.mk

This pull request contains readme updates for people using Questa VRun Manager along with bug correction for the questa template file. (commits 312d7de07bf07fb2ec0f722eb4b91264c8739f1c & 143e563cce29bd3dfa29f3c73596ba2463ff3509)
When I first tried to add Questa regression few weeks ago, I saw that Questa Vrun do not catch simulation errors at all, I thought at first it was somehow an issue with how Questa Vrun works and I found a workaround to this by writing test status to an ucdb file for each test, but this implied that coverage should be enabled.
I set-up a way to do this with coverage disabled, see commit b710bc040814bf5a69da71713ac4ffa23e40512d for more comments on that (it's a bit long to be there...) 
I also discover by re-reading again cv_regress that the script also seeks for …

New features and updates to regressions

---

lib/uvm_agents/uvma_isacov/cov/uvma_isacov_cov_model.sv

Hello,
I add more filtering to the cover point, that collect coverage related to unaligned access (also amo access), as we know the CVA6 do not support this feature.

ISACOV : Add filtering for unaligned access

---

cv32e40s/tb/uvmt/uvmt_cv32e40s_debug_assert.sv

Recent updates to rvfi now includes exception trigger debug signaling when an exception trigger fires. Updated failing assert, and removed reliance of support signal. 
Note: I think the support signal `is_exception_trigger_hit` is now redundant, but we should keep it in case we see a need for this in the future.

Adapted asserts to new rvfi dbg signaling

---

lib/uvm_agents/uvma_isacov/uvma_isacov_instr.sv

Adding decode imm for CS_TYPE because the CL_TYPE & CS_TYPE has the same imm decode

ISACOV : Add decode imm for CS_TYPE

---

cva6/regress/install-cva6.sh
cva6/regress/install-riscv-dv.sh
cva6/regress/install-spike.sh
cva6/regress/install-verilator.sh
cva6/regress/smoke-tests.sh
cva6/sim/Makefile

Some improvements in the current infrastructure:
- Auto detect `CV_SW_PREFIX` if not set.
- Set `RISCV_GCC` and `RISCV_OBJCOPY` if not set.
- Avoid return statements when fatal errors.
- Detection of the `tohost` addr now has more compatibility across systems.
- Other improvements.

CVA6: Infrastructure improvements

---

cva6/regress/install-spike.sh

#1846 changed `install-cva6`  to source `verilator` and `spike`. 
`Spike` script was not prepared to be sourced, it  changes the working directory, which now has collateral effects `install-cva6` script.

CVA6: Adapt install-spike for bash source

---

cv32e40s/tb/uvmt/uvmt_cv32e40s_pmprvfi_assert.sv

This PR fixes an assert that started failing after rvfi started reporting exception triggers.

fixed a_csrs_mmode_only

---

lib/uvm_agents/uvma_rvfi/uvma_rvfi_instr_if.sv

This PR adds instr_mem_rmask_f and instr_mem_wmask_f. 
instr_mem_*mask_f returns an array of bits that is similar to rvfi_mem_*mask.
The difference is that when rvfi_mem_*mask is not set due to various reasons, the instr_mem_*mask is set according to what the instruction intended to do.

instr_mem_*mask_f and signals to rvfi interface

---

cv32e40s/tb/uvmt/uvmt_cv32e40s_dut_wrap.sv

New signals added to the core caused simulation warnings, hooked these up to respective signals in the testbench to avoid unconnected ports-warning

Fixed debug_pc outputs not connected warning in sim

---

lib/uvm_agents/uvma_isacov/cov/uvma_isacov_cov_model.sv
lib/uvm_agents/uvma_isacov/uvma_isacov_macros.sv

As we discuss, for the CVA6 env we have a vcs compilation error related to the vcs version, the 'with' isn't supported for now, the fix is programmed for July, so to integrate the ISACOV in the CVA6 env, I add ifdef (a final solution after a lot of discuss) as a temporary fix.

ISACOV : Add ifdef to avoid VCS compilation error due to unsupported 'with' key word

---

cv32e40p/sim/riscof/README.md
cv32e40p/sim/riscof/config.ini
cv32e40p/sim/riscof/config_cv32e40p_v2.ini
cv32e40p/sim/riscof/sail_cSim/riscof_sail_cSim.py

This PR is for changes to modify the default riscof sail model config to run without docker.
Earlier we had made the default config to run with docker. But going forward we wanted to reverse this and use the more general solution of running SAIL model from a local installation without the need of docker.
Also since we were not able to verify this flow previously, it had minor issues which required a small update to the sail python plugin.
README also updated to indicate this change in default config for Sail.
This is just default config change, internally now flow supports both mechanisms.

cv32e40p riscof default config change for sail model to run without docker

---

bin/cv_regress
bin/templates/regress_macros.j2
bin/templates/regress_rmdb.j2

Added an option for cv_regress script to enable check_sim_results for questa CI
I also noticed that the yesorno jinja macro was somehow weird, if the variable is set to False, the macro will convert it to "False" instead of "NO" as I *think* it should be. 
By default, a test is supposed to inherit its configuration from its build, but I added a way to override this behavior if someone wants to, only for questa CI tool first.

Small modifications to regression generation

---

.metrics.json
bin/ci_check
cv32e20/bsp/Makefile
cv32e20/regress/cv32e20_ci_check.yaml

This PR sets up a preliminary CI regression for CV32E20.  The command-line to run it:
```
$ cd bin
$ ./ci_check --core cv32e20 --simulator xrun --iss 0
```
If you have an ImperasDV license, omit the `--iss 0` switch.

Stand-up the ci_check regression for CV32E20

---

cv32e40p/env/corev-dv/cv32e40p_debug_rom_gen.sv
cv32e40p/env/corev-dv/cv32e40p_instr_test_pkg.sv
cv32e40p/env/corev-dv/target/cv32e40p/riscv_core_setting.sv
cv32e40p/env/uvme/cov/uvme_debug_covg.sv
cv32e40p/env/uvme/uvme_cv32e40p_constants.sv
cv32e40p/env/uvme/uvme_cv32e40p_env.sv
cv32e40p/tb/uvmt/uvmt_cv32e40p_tb.sv
cv32e40p/tb/uvmt/uvmt_cv32e40p_tb_ifs.sv

This PR is doing following things:
1.) reconnect debug_sequencer -> was preventing debug tests to run
2.) update debug rom for FPR push and pop for floating point random stream tests
3.) create all xpulp instruction encodings as params in uvme tb for use. At the moment use case is for coverage but can be used with assertions or scoreboards if needed.
4.) add new debug cover groups for floating point and xpulp instructions according to v2 test plans

[cv32e40p] tb update for debug and debug coverage with f and xpulp instructions

---

bin/templates/regress_vsif.j2
cv32e40s/env/corev-dv/cv32e40s_asm_program_gen.sv
cv32e40s/env/corev-dv/cv32e40s_instr_gen_config.sv
cv32e40s/regress/cv32e40s_full.yaml
cv32e40s/tests/cfg/dummy_instr.yaml

- Made dummy instruction generation available for riscv-dv
- Replaced no_bitmanip configuration with dummy_instr
- Increased per-test timeout to two hours (expect that dummy instr. tests may cause some tests that otherwise would not time out to fail)
- Removed dummy_instr cfg from running in regression with directed tests, as these needs modifications to enable dummy instructions.
ci_check OK

Enable dummy instruction testing, remove no_bitmanip configuration

---

bin/clonetb

This PR adds a script to clone the external 40x verif environment subtree repo.
It is clean, simple, and extensible to other cores.
I can rewrite this in Python or make if we think that would make things better. But I honestly think this is an uncomplicated problem and that this simple shell script is a fitting solution.
@silabs-hfegran, @MikeOpenHWGroup, this continues #1867

Clone Verif Environment - Script

---

bin/clonetb

This PR updates the clone script to use the brand new [openhwgroup/cv32e40x-dv](https://github.com/openhwgroup/cv32e40x-dv) repo's URL.

Clone Script - New Repo URL

---

cv32e40s/env/corev-dv/cv32e40s_asm_program_gen.sv
cv32e40s/tb/uvmt/uvmt_cv32e40s_tb.sv
cv32e40s/tb/uvmt/uvmt_cv32e40s_xsecure_assert/uvmt_cv32e40s_xsecure_dummy_and_hint_assert.sv
cv32e40s/tests/cfg/dummy_instr.yaml
cv32e40s/tests/uvmt/base-tests/uvmt_cv32e40s_base_test_constants.sv
lib/support/isa_support.sv

- Fixed: Default LFSR coefficients used as seed
- Added: Default LFSR configuration for the dummy instruction configuration
- Fixed: Dummy instruction frequency assertion

Fixed wrong secureseed configuration, updated dummy instr. assertion

---

vendor/patches/riscv/riscv-isa-sim/0004-enforce-max-steps-limit.patch
vendor/riscv/riscv-isa-sim/riscv/sim.cc
vendor/riscv/riscv-isa-sim/riscv/sim.h
vendor/riscv/riscv-isa-sim/spike_main/spike.cc

This PR re-introduces the Spike execution limit initially proposed in PR #1673, but this time based on the vendorized Spike tree.
The limit is set by adding the option `--steps=N` to the Spike command line.  The execution will be stopped as soon as the step count reaches or exceeds `N`.   If the option is not given or the value of `N` is 0, the execution will continue until termination (or until the exhaustion of system resources, whichever comes first.)
Proper execution termination was tested on a `while(1);` infinite loop program.
File change summary:
* vendor/patches/riscv/riscv-isa-sim/0004-enforce-max-steps-limit.patch: New.
* vendor/riscv/riscv-isa-sim/riscv/sim.cc (sim_t::sim_t): Pass max_steps to the sim_t constructor.  Initialize step counters. 
(sim_t::run): Update step counters …

[Spike] Add "stepout" execution limit (--steps=N) to prevent runaway execs.

---

.gitlab-ci/cva6.yml

As the 2 jobs are verfied by GitHub Actions, no need to dupllicate the work on gitlab-ci. This is an ecological PR !!!

Remove jobs which are already executed by GitHub Actions

---

cva6/sim/Makefile
cva6/sim/cva6.py

The first argument --gen_sv_seed run a test X times with a random seed and generates X logs. (0<X)
The second argument --sv_seed executes a test with a specific seed.
We cannot use both options at the same time.

Add two arguments in cva6.py to controlle systemverilog seed

---

cv32e40s/tb/uvmt/uvmt_cv32e40s_pma_cov.sv
cv32e40s/tb/uvmt/uvmt_cv32e40s_tb.sv

This PR adds a missing signal declaration that gave warnings.
Test status:
* Formal - Still works.
* Hello world - Passes.

PMA Coverage - Fix Missing Declaration

---

cv32e40s/sim/ExternalRepos.mk
cv32e40s/tb/uvmt/uvmt_cv32e40s_imperas_dv_wrap.sv
cv32e40s/tb/uvmt/uvmt_cv32e40s_triggers_assert_cov.sv
cv32e40s/tb/uvmt/uvmt_cv32e40s_xsecure_assert/uvmt_cv32e40s_xsecure_interface_integrity_assert.sv
cv32e40s/tests/programs/custom/debug_test2/debug_test2.c

- Commented out assertion/support logic that creates an unintentional loop (needs a rewrite)
- Removed tdata3 from debug_test2
- Updated core hash

40s fixes for 0.9.0

---

cv32e40s/tb/uvmt/uvmt_cv32e40s_xsecure_assert/uvmt_cv32e40s_xsecure_interface_integrity_assert.sv

1) Fixed todo, by inverting the alb_resp_q array (which is connected to the resp_q array in the alignment buffer), since the corresponding array is inverted in the rtl:

convert array, since the corresponding array is convertes in the rtl

---

cv32e40s/env/uvme/cov/uvme_debug_covg.sv
cv32e40s/env/uvme/uvma_cv32e40s_core_cntrl_agent.sv
cv32e40s/env/uvme/uvme_cv32e40s_core_cntrl_if.sv
cv32e40s/fv/dummy_pkg.sv
cv32e40s/tb/uvmt/support_logic/uvmt_cv32e40s_sl_req_attribute_fifo.sv
cv32e40s/tb/uvmt/support_logic/uvmt_cv32e40s_support_logic.sv
cv32e40s/tb/uvmt/uvmt_cv32e40s_clic_interrupt_assert.sv
cv32e40s/tb/uvmt/uvmt_cv32e40s_dut_wrap.sv
cv32e40s/tb/uvmt/uvmt_cv32e40s_pma_cov.sv
cv32e40s/tb/uvmt/uvmt_cv32e40s_pmprvfi_assert.sv
cv32e40s/tb/uvmt/uvmt_cv32e40s_rvfi_assert.sv
cv32e40s/tb/uvmt/uvmt_cv32e40s_tb.sv
cv32e40s/tb/uvmt/uvmt_cv32e40s_triggers_assert_cov.sv
cv32e40s/tb/uvmt/uvmt_cv32e40s_umode_cov.sv
cv32e40s/tb/uvmt/uvmt_cv32e40s_xsecure_assert/uvmt_cv32e40s_xsecure_hardened_csrs_pmp_assert.sv
cv32e40s/tb/uvmt/uvmt_cv32e40s_xsecure_assert/uvmt_cv32e40s_xsecure_register_file_ecc_assert.sv
cv32e40s/tests/programs/custom/debug_test_reset/debugger.S
cv32e40s/tests/programs/custom/debug_test_trigger/debug_test_trigger.c
cv32e40s/tests/programs/custom/misalign/misalign.c
cv32e40s/tests/programs/custom/requested_csr_por/requested_csr_por.c
cv32e40s/tests/uvmt/base-tests/uvmt_cv32e40s_base_test_pkg.sv
lib/uvm_agents/uvma_clic/uvma_clic_if.sv
lib/uvm_agents/uvma_debug/uvma_debug_if.sv
lib/uvm_agents/uvma_interrupt/uvma_interrupt_if.sv
lib/uvm_agents/uvma_obi_memory/src/uvma_obi_memory_assert.sv
lib/uvm_agents/uvma_rvfi/uvma_rvfi_instr_if.sv

- Fixed some warnings with Jasper FV
- Fixed debug_test_reset test
- Fixed non-sensitive function assignment in assertion support logic 
- Fixed requested_csr_por test
- Fixed misalign test
- Fixed "only one ack per clic irq" assertion
- Fixed coverage bins definitions
- Fixed debug_trigger_test (0.9.0 changes)
- Enabled mcontrol6.hit in the ISS configuration

Formal warning fixes/directed test fixes

---

cv32e40s/env/uvme/uvma_cv32e40s_core_cntrl_agent.sv

- Fixed: removed override. No longer needed, and also had a conflict with the 0-triggers configuration

Removed iss workaround

---

cv32e40s/tests/programs/custom/cv32e40s_readonly_csr_access_test/cv32e40s_readonly_csr_access_test.S

- Fixed: marchid 0x14->0x15 for cv32e40s in cv32e40s_readonly_csr_access_test

Fixed marchid in cv32e40s_readonly_csr_access_test

---

cva6/sim/Makefile
cva6/sim/cva6.yaml

In order to prevent runaway executions of Spike, this PR sets an execution limit of 2 million cycles on all Spike executions triggered by the CVA6 DV scripts.  The mechanism used is the new Spike cmdline option introduced in PR #1949.
Sullary of file changes:
* cva/sim/Makefile (spike_stepout): Set up Spike stepout option if caller supplied a step count limit.
(spike): Invoke Spike with a 'stepout' limit option (possibly empty).
* cva6/sim/cva6.yaml (iss: spike): Set step limit of Spike runs to 2M.  Add explanatory comments.

Set Spike execution limit to 2M steps across all verification runs.

---

cva6/env/corev-dv/custom/cvxif_custom_instr.sv
cva6/env/corev-dv/cva6_defines.svh
cva6/env/corev-dv/cva6_instr_pkg.sv

Hello,
So this update of the CVA6-DV is about the custom instruction use in cvxif, so we add the cutom instruction definition in the cva6_instr_pkg, instead of copy them to the riscv_instr_pkg then use it.
it's just an update to be more independent from the RISCV-DV

CVA6-DV : Update CVA6-DV

---

.gitlab-ci/scripts/report_synth.py

bcff0ec90bbccdfd11c4442b9cec3115c166211a in cva6 slightly reduces area.
However, the dashboard was run for this PR (#1263) before the synthesis
checks were added.

ci: update expected synthesis results

---

cv32e40s/sim/ExternalRepos.mk
cv32e40s/tb/uvmt/uvmt_cv32e40s_imperas_dv_wrap.sv
cv32e40s/tb/uvmt/uvmt_cv32e40s_tb.sv
mk/uvmt/xrun.mk

- Updated cv32e40s hash to latest
- Added $assertkill() to avoid liveness assertion errors upon test termination
- Added advanced debugging option flags to xrun makefile (SRC_DEBUG)
- Qualified CSR logic in imperas_dv_wrap with rvfi_valid

cv32e40s: Testbench updates

---

cv32e40s/tb/uvmt/uvmt_cv32e40s_tb.sv
cv32e40s/tb/uvmt/uvmt_cv32e40s_xsecure_assert/uvmt_cv32e40s_xsecure_hardened_csrs_interrupt_assert.sv

Make sure we fetch a valid obi req integrity signal.
(And place the mcause_shadow signal with the other shadow signals)

change where integrity signal is fetched from

---

cv32e40p/env/corev-dv/custom/isa/custom/riscv_custom_instr.sv
cv32e40p/env/corev-dv/cv32e40p_instr_sequence.sv
cv32e40p/env/corev-dv/cv32e40p_instr_test_pkg.sv
cv32e40p/env/corev-dv/cv32e40p_rand_instr_stream.sv
cv32e40p/env/corev-dv/instr_lib/cv32e40p_base_instr_lib.sv
cv32e40p/env/corev-dv/instr_lib/cv32e40p_pulp_instr_lib.sv
cv32e40p/env/uvme/vseq/uvme_cv32e40p_random_debug_vseq.sv
cv32e40p/tests/programs/corev-dv/corev_rand_debug_ebreak_xpulp/corev-dv.yaml
cv32e40p/tests/programs/corev-dv/corev_rand_debug_ebreak_xpulp/test.yaml
cv32e40p/tests/programs/corev-dv/corev_rand_debug_single_step_xpulp/corev-dv.yaml
cv32e40p/tests/programs/corev-dv/corev_rand_debug_single_step_xpulp/test.yaml
cv32e40p/tests/uvmt/compliance-tests/uvmt_cv32e40p_firmware_test.sv

This PR is for work for part of v2 debug random tests and xpulp streams needed for random tests including debug.
- Adding new debug vseq uvme_cv32e40p_reduced_rand_debug_req_c to target shorter random tests and mechanism to override controls from test yaml through pluargs
- Add way to include random xpulp instructions as part of random stream generated for debug_rom
- Create cv32e40p_xpulp_rand_stream for random xpulp instruction stream and updated related functions and other cv32e40_* extended classes from corev-dv to work with xpulp_rand_stream. 
No overwriting of riscv-dv files done here, all new updates are within cv32e40p/env/corev-dv files in extended classes for cv32e40p.
- added 2 new debug tests with xpulp using new xpulp stream.

[cv32e40p] adding new v2 debug tests with xpulp and random xpulp stream

---

lib/uvm_agents/uvma_isacov/cov/uvma_isacov_cov_model.sv

Hello @MikeOpenHWGroup @silabs-robin ,
This PR related to filter hazard cross (RAW : Read After Write -> instr_prev.rd == instr.rs1 || instr.rs2) so all instruction do not have rd or one of the register source should not appear (**UNKNOWN_GROUP, FENCE_GROUP, FENCE_I_GROUP, RET_GROUP, ENV_GROUP**) in, the cross also :  
for current group of instruction should not have : **JUMP_GROUP** -> jump instruction do not have source register (only have rd)
for Previous group of instruction should not have : **STORE_GROUP & BRANCH_GROUP** -> Store & branch instruction do not have destination register (only have rs)

ISACOV : Filter hazard cross

---

cv32e40p/env/corev-dv/custom/isa/custom/riscv_custom_instr.sv
cv32e40p/env/corev-dv/cv32e40p_instr_base_test.sv
cv32e40p/env/corev-dv/cv32e40p_instr_sequence.sv
cv32e40p/env/corev-dv/cv32e40p_instr_test_pkg.sv
cv32e40p/env/corev-dv/instr_lib/cv32e40p_pulp_hwloop_instr_lib.sv
cv32e40p/tb/uvmt/uvmt_cv32e40p_debug_assert.sv
cv32e40p/tests/programs/corev-dv/corev_rand_pulp_hwloop_debug/corev-dv.yaml
cv32e40p/tests/programs/corev-dv/corev_rand_pulp_hwloop_debug/test.yaml
cv32e40p/tests/programs/corev-dv/corev_rand_pulp_hwloop_test/corev-dv.yaml
cv32e40p/tests/programs/corev-dv/corev_rand_pulp_hwloop_test/test.yaml

This PR is for pulp hwloop related work for cv32e40p v2 verif plans:
- Create new corev-dv stream lib for hwloops for random tests
- update the corev-dv tb for relevant hwloop specific updates, in cv32e40p_instr_sequence, cv32e40p_instr_base_test.
- Add 2 new tests for hwloops as part of corev-dv test lib
- some minor TB fixes found during bring up related to hwloops.

[cv32e40p]pulp hwloop random tests and related corev-dv updates

---

cva6/sim/cva6.py

In the current cv32a60x configuration, the A extension is not enabled. As we decided to verify this extension during cv32a60x verification, I included it with this PR. 

Enable A extension ofr cv32a60x configuration

---

cv32e40s/tb/uvmt/uvmt_cv32e40s_dut_wrap.sv
cv32e40s/tb/uvmt/uvmt_cv32e40s_tb.sv
cv32e40s/tests/uvmt/base-tests/uvmt_cv32e40s_base_test_constants.sv

Same as this https://github.com/openhwgroup/cv32e40x-dv/pull/7, but for the s core: 
formal compiles, ci_check passes

remove CLIC_INTTHRESHBITS

---

bin/ci_check
cv32e40p/tests/programs/custom/debug_test/debug_test.c
lib/uvm_agents/uvma_obi_memory/src/comps/uvma_obi_memory_cov_model.sv
mk/uvmt/vcs.mk
mk/uvmt/vsim.mk

For longer than I can remember, no active member has been using VCS to run simulations of CV32E40P in CORE-V-VERIF.  This pull-request restores the ability to use VCS (and also fixes a latent bug in `ci_check` that I did not realise was there).
Note that this PR does (almost) the same thing as #2006 on the master branch.

Reinstate VCS support for CV32E40Pv2 on cv32e40p/dev branch

---

cv32e40p/regress/cv32e40pv2_ci_check.yaml

Here is a first proposal for a ci_check script. 
I added all configurations from `cv32e40p/tests/cfg`, and mixed them a bit depending on what it seems to be relevant for me. 
Don't hesitate to tell me if anything's missing/wrong
Some tests are commented because they are not already merged in our working branch (`cv32e40p/dev`) and it will cause the cv_regress to issue a critical error. 
The commands to generate & run the ci_check script will be, for running with vsim and Questa Verification Run Manager with 4 jobs in parallel : 
```shell
./cv_regress --rmdb --file=cv32e40pv2_ci_check.yaml --simulator=vsim --outfile=cv32e40pv2_ci_check.rmdb --lsf "bsub -K -q 'vanilla'" --check_sim_results
vrun -rmdb cv32e40pv2_ci_check.rmdb -run cv32e40p -j 4 -mintimeout 0:300 -nolocalrerun
```
To generate …

first proposal of CV32E40Pv2 ci_check script

---

bin/cv_regress
bin/templates/regress_sh.j2
bin/templates/regress_vsif.j2

Fixed: makefile builds env with ISS defined, but runs without if using the flag --iss 0, causing test failure

Updated regression scripts to fix issues with --iss 0

---

cv32e40s/regress/cv32e40s_full.yaml

With the addition of zbc-instructions, the b_ext_test is incompatible with the b_ext_abs-cfg, and this configuration has been deprecated from full regression runs

Removed b_ext_abs cfg from b-ext test in full regression 

---

.gitlab-ci/cva6.yml

Hot Fix: Spike currently builds before each job, which generates disk full. This is a fix to build one time by pipe.

gitlab-ci: fix spike artifact management

---

bin/clonetb

Clonetb uses a hash instead of main, as a hash will be more stable than main.
Formal comiles, ci_check has these results:

use hash=709bec4 instead of main in clonetb

---

cva6/env/uvme/cvxif_vseq/custom_instruction.rst

Fix in the cvxif custom instruction spec, because the definition of the imm custom instruction isn't aligned with the RISCV spec.

CVXIF : Modify the cus_exc instruction spec to RTYPE

---

cva6/env/corev-dv/target/rv32imac/riscv_core_setting.sv
cva6/regress/dv-generated-tests.sh

Hi,
As you all know the STEP1 configuration is **rv32imac**, this configuration does not exist in the RISCV-DV, so I add it in the core-dv (cva6); to use it when generating tests.

Add A extension to STEP1 configuration

---

.gitlab-ci/scripts/report_synth.py

It makes it possible to perform changes which have an impact on CVA6
area without having to open a second MR on core-v-verif.
It is still needed to "declare" the change of area in a diff which is
reviewed, but now the diff is in the same repository as the
modification.

ci: move expected results to cva6 repository

---

cva6/docs/coverage_status/isacov_status.rst

ISACOV verification does not obtain 100% functional coverage. This file explain the reason. 

ISACOV : Add file to justify missing coverage in the ISA verification task

---

cva6/tests/custom/cv_xif/cvxif_macros.h
vendor/riscv/riscv-isa-sim/customext/cvxif.cc
vendor/riscv/riscv-isa-sim/riscv/cvxif.h
vendor/riscv/riscv-isa-sim/riscv/processor.h
vendor/riscv/riscv-isa-sim/spike_main/spike.cc

* Updates bit templateswith the new spec.
* Adds enums to cvxif.h for switch/case in cvxif.cc when instructions are decoded.
* Adds the number of source registers accepted (2 or 3) as a parameter to the `processor_t` class (processor.h).
* Adds an option in spike.cc to specify the number of source registers.
Signed-off-by: Jules FAUCHON <jules.fauchon@thalesgroup.com>

Adapting spike to implement the cvxif agent spec

---

cv32e40s/tests/programs/custom/debug_test2/debug_test2.c
cv32e40s/tests/programs/custom/hello-world/hello-world.c

* Added support for 40x in debug_test2 (deliberately on 40S to ease merging efforts
* Fixed typo in hello_world comment

Added support for 40X in debug_test2, fixed typo

---

bin/templates/regress_rmdb.j2

This PR allows to generate .rmdb files with test_cfg option introduced by @dd-vaibhavjain in PR #2029, so it should be merged after this one. 
It also includes the useful parts of discarded PR #1972 
As usual, you can generate a .rmdb by issueing the command: 
`./cv_regress --rmdb --file=cv32e40pv2_pulp_fpu_all_lat_covg.yaml --simulator=vsim --outfile=cv32e40pv2_ci_check.rmdb --cov`

updated rmdb file to support test_cfg option AND improvment from cancelled PR 1972

---

cv32e40s/env/uvme/uvme_cv32e40s_cfg.sv
lib/uvm_agents/uvma_isacov/uvma_isacov_cfg.sv
lib/uvm_agents/uvma_isacov/uvma_isacov_mon.sv
lib/uvm_agents/uvma_isacov/uvma_isacov_pkg.sv
lib/uvm_agents/uvma_isacov/uvma_isacov_tdefs.sv

To verify the implementation, the test hello-world was ran to see if the coverage when using the SPIKE decoder is close to the coverage when using isa_support. 
The results showed that the two decoders had approximately the same coverage, indicating that the implementation works. 
Screenshot of coverage when using Spike:
Screenshot of coverage when using isa_support:

Made it possible to use the Risc-v disassembler with isacov

---

bin/cv_regress
cv32e40s/env/uvme/vseq/uvme_cv32e40s_vp_fencei_tamper_seq.sv
cv32e40s/tb/uvmt/imperas_dummy_pkg.flist
cv32e40s/tb/uvmt/imperas_dv_deps.flist
cv32e40s/tb/uvmt/uvmt_cv32e40s.flist
cv32e40s/tb/uvmt/uvmt_cv32e40s_imperas_dummy_pkg.sv
cv32e40s/tb/uvmt/uvmt_cv32e40s_imperas_dv_wrap.sv
cv32e40s/tb/uvmt/uvmt_cv32e40s_tb.sv
cv32e40s/tests/uvmt/base-tests/uvmt_cv32e40s_base_test.sv
mk/Common.mk
mk/uvmt/xrun.mk

* Moved iss-initalization to uvm_reset phase
* Moved ref_init to an interface instead of inside imperas_dv wrapper module to easily access function with uvm
* Fixed issue with ISS in regressions
* Added iss dummy package to support building with and without iss installed and remove all compile time `ifdef USE_ISS` 
* Split imperas manifest file in two, to resolve dependencies with initialization in uvm-code
Future work: change $test$plusarg("USE_ISS") to depend on uvm configuration setting.

Refactored testbench code

---

cva6/tb/uvmt/cva6_tb_wrapper.sv
cva6/tb/uvmt/uvmt_cva6_dut_wrap.sv
cva6/tb/uvmt/uvmt_cva6_tb.sv
cva6/tb/uvmt/uvmt_cva6_tb_ifs.sv

CVA6Cfg is now a input parameter of CVA6 to gather all the different configuration variables in the same structure.

Use CVA6Cfg as cva6 parameter

---

cv32e40p/regress/cv32e40pv2_full_covg.yaml
cv32e40p/regress/cv32e40pv2_pulp_covg.yaml
cv32e40p/regress/cv32e40pv2_pulp_fpu_all_lat_covg.yaml
cv32e40p/regress/cv32e40pv2_pulp_fpu_no_lat_covg.yaml
cv32e40p/regress/cv32e40pv2_pulp_fpu_zfinx_all_lat_covg.yaml
cv32e40p/regress/cv32e40pv2_pulp_fpu_zfinx_no_lat_covg.yaml

This PR adds the first draft for CV32E40P v2 regressions.
These are preliminary and not complete yet, and are commited to allow first regressions to be run.
More will be added / they will be updated later when needed
To be merged after PR #2053

Added first draft for v2 regressions, with support of test_cfg option

---

lib/uvm_agents/uvma_cvxif/src/comps/uvma_cvxif_cov_model.sv

Hello, So that fix for the cvxif agent coverage model specifically in a cross (removing a rd), it's like a copy-past bug on coverage model of the cvxif agent

HOTFIX : Fix a cross in cvxif agent coverage model

---

cva6/tb/core/Flist.cva6_tb
cva6/tb/uvmt/cva6_tb_wrapper.sv
cva6/tb/uvmt/uvmt_cva6_dut_wrap.sv
cva6/tb/uvmt/uvmt_cva6_tb.sv

Previously a part of AXI was defined in packages, now it is defined as cva6 input parameters

Define AXI as cva6 input parameters

---

cva6/tests/custom/isacov/branch_to_zero.S

I switch register for beq instruction , because beq a1, zero, branch4 -> it's a compressed instruction c.bnez a1, branch4, that means I'll get coverage on c.bnez and not beq instruction

ISACOV : switch beq instruction register

---

lib/uvm_agents/uvma_rvfi/uvma_rvfi_instr_if.sv

Signals may be have dependencies on each other, thus to
avoid having to micromanage order of execution, they are split
into separate always_comb blocks. Assign will not work due to
sensitivity list issues with functions, and a single always_comb
block will cause issues due to clause b in section 9.2.2.2.1 in
ieee 1800-2017

Fixed issue with always_comb block using signals written within

---

cv32e40s/tb/uvmt/uvmt_cv32e40s_imperas_dv_wrap.sv

Temporary fix: Set comparison of the mnxti/mscratchcsw/mscratchcswl registers as volatile until we  have a proper iss fix - this will make the reference model mirror the state of these registers from the RTL, and their value are thus not properly checked.

Temporary fix to get ISS regression runs going

---

cva6/sim/cva6.py

Hello,
This a HOTFIX  to fix the **config_pkg_generator.py** path in **cva6.py**, the problem appears with the last [cva6 commit](https://github.com/openhwgroup/cva6/commit/dc103cd49fa1a1d9cf353e2c29e64a1f94398d85)

cva6.py : Fix config_pkg_generator.py path

---

.gitlab-ci.yml
.gitlab-ci/README.md
.gitlab-ci/core-v-verif-cva6.yml
.gitlab-ci/cva6.yml
cva6/sim/cva6.py

1. Rely on stages more than needs relationships: "needs" relationships are tricky as they bypass stage ordering. For instance, "initjob" was useless, which was a bug.
2. Refactor job descriptions: each job needs less code in cva6.yml. It also fixes an issue in CVV pipelines, where the CVA6 hash in the dashboard was not the one used in some jobs of the pipeline.
3. Document the CI structure

ci: rework and document

---

cv32e20/sim/ExternalRepos.mk
mk/uvmt/vsim.mk

This PR does two things:
1. Updates the hash for the RTL.
2. Updates `vsim.mk` to allow the CV32E20 environment to compile/run under Questasim (vsim).
The updates to `vsim.mk` add a set of warning suppressions - these need to be investigated further, but for now this gets simulations running with Questa.

Add (too many) warning suppressions for VSIM

---

vendor/patches/riscv/riscv-isa-sim/0005-yield-load-reservation.patch
vendor/riscv/riscv-isa-sim/riscv/sim.cc

to have same behaviour on spike and on RTL with one core,
do not yield load reservation at the end of each block of
INTERLEAVE steps

[SPIKE] sim.cc: do not yield load reservation on single core

---

lib/uvm_agents/uvma_cvxif/src/comps/uvma_cvxif_cov_model.sv

Hello,
This PR related to cvxif coverage model, I filter cross for commit interface , as the protocol say, all commit signals are valid when commit valid is assert, so no need to create bins when commit valid is low.

CVXIF : Filter cross coverage for commit interface

---

vendor/patches/riscv/riscv-isa-sim/0006-implement-unknown-cvxif-exception.patch
vendor/riscv/riscv-isa-sim/customext/cvxif.cc
vendor/riscv/riscv-isa-sim/riscv/trap.h

This branch contains a fix and a feature for the cvxif agent in spike:
* In the spec the custom instruction `CUS_ADD` has `func7` equal to 0.
In spike, their was no test to check that and so it decoded illegal instruction as `CUS_ADD`.
Now it will raise illegal instruction.
* A new type of exception was created for all exceptions unknown by the cva6.
This exception writes 0 in `mtval`, the cause in `mcause` and ends the test.
Signed-off-by: Jules FAUCHON <jfauchon@thalesgroup.com>

[Spike] cvxif agent features

---

.gitlab-ci/cva6.yml
.gitlab-ci/scripts/report_envfail.py

Infrastructure issues sometimes occur, preventing some jobs requiring specific things from starting. So these jobs do not produce reports at all. As a result, jobs in the dashboard are "successful", which is misleading.
To fix that, this PR adds a job which is run only if one of the previous jobs failed in GitLab words (including the case when the job did not start). There are no specific requirements for this new job so there is no reason it doesn’t start.

ci: report environment failures in dashboard

---

bin/merge.sh

This PR changes how the merge script checks whether `cv32e40x/` is an `x-dv` clone or not. (Plus some other consistency tweaks.)
Rationale: None of my remotes were called `origin`, so the script tried to continue even if its prerequisites were not fulfilled.

Merge Script - "x-dv" Detection

---

cv32e40s/tb/uvmt/uvmt_cv32e40s_dut_wrap.sv
cv32e40s/tb/uvmt/uvmt_cv32e40s_tb.sv

This PR reduces the responsibilities of `dut_wrap` so it is easier to redefine this module outside of core-v-verif.
Test status:
* ci_check - All green.
* Formal - Still runable.

"dut_wrap" - Make Overridable

---

cv32e40s/sim/ExternalRepos.mk

* Fixed: Testbench and core out of sync

Updated cv32e40s core hash to 41cbecf7690efd0ccd75b32bc31aab09c5dede56

---

cv32e40s/fv/Makefile

This PR lets the formal setup use `ExternalRepos.mk` to use the designated hash of the RTL.
Rationale: Formal used to use `master` of the RTL repo, and this can give misleading results from `ci_check`.

Formal - "ExternalRepos.mk"

---

cv32e40s/tb/uvmt/support_logic/uvmt_cv32e40s_support_logic.sv
cv32e40s/tb/uvmt/uvmt_cv32e40s_tb.sv
cv32e40s/tb/uvmt/uvmt_cv32e40s_tb_ifs.sv
cv32e40s/tb/uvmt/uvmt_cv32e40s_triggers_assert_cov.sv
cv32e40s/tb/uvmt/uvmt_cv32e40s_xsecure_assert/uvmt_cv32e40s_xsecure_dummy_and_hint_assert.sv
cv32e40s/tests/uvmt/base-tests/uvmt_cv32e40s_base_test_constants.sv

Only run trigger exception integrity assert if integrity faults are enabled.
Change support logic usage in xsecure dummy as mentioned here: https://github.com/openhwgroup/core-v-verif/pull/2124. 
ci_check: all green
formal integrity cutpoint run: the glitch_dt_* assertions is all green
formal no cutpoint run: the glitch_dt_*_noprecondition-s are on bound 32, and still running.

glitch prefix, better decode logic usage

---

cv32e40s/tests/programs/custom/zc_test/zc_test.c

Timing fixed to help with a failure of the test on the 40x core. The issue is not seen here, but the fix seems to work on 40s as well, so I PR the fix here as the S -> X flow is clear.

Fixed timing for zc_test and placed printouts behind a debug define

---

cva6/regress/dv-generated-xif-tests.sh
cva6/sim/Makefile

Hello, this PR related to enable/disable when we desire, using an environment variable.
Cvxif extension is enabled when **cvxif ** variable is set, and disable otherwise

Enable cvxif extension for Spike when cvxif variable is set

---

cv32e40p/sim/tools/xrun/README.md
cv32e40p/tests/programs/custom/debug_test_boot_set/debug_test_reset.c
cv32e40p/tests/programs/custom/debug_test_reset/debug_test_reset.c
cv32e40p/tests/programs/custom/debug_test_trigger/debug_test.c
cv32e40p/tests/uvmt/base-tests/uvmt_cv32e40p_base_test.sv

The test-programs in `cv32e40p/tests/programs/custom/debug_test_*` were no longer compiling due to:
1. Missing `#include <stdint.h>`
2. Null handle for `uvmt_cv32e40p_test_randvars_c::test_randvars`
This PR resolves both issues, and adds a minor cleanup of `cv32e40p/sim/tools/xrun/README.md`.

Minor update to the dev_fix_debug_* test-programs to fix bit-rot issues.

---

cva6/env/uvme/uvme_cva6_cfg.sv

As we discuss, I disable reg cross for all functional coverage (ISACOV & CVXIF)

Disable register crossing in Functional coverage

---

cv32e40s/tb/uvmt/uvmt_cv32e40s_clic_interrupt_assert.sv

Fixme was in place to account for an rtl error that has since been resolved, the invalid csr instructions for mscratchcsw and mscratchcswl should now trap as expected, and the assertions have been updated accordingly

Resolved clic assert fixmes for mscratchcsw and mscratchcswl

---

bin/cv_regress
cv32e20/tb/uvmt/uvmt_cv32e20_dut_wrap.sv
cv32e20/tb/uvmt/uvmt_cv32e20_imperas_dv_wrap.sv
cv32e20/tb/uvmt/uvmt_cv32e20_step_compare.sv
cv32e20/tb/uvmt/uvmt_cv32e20_tb.sv
cv32e20/tests/cfg/default.yaml

added cv32e20 to cv_regress script to further that effort.
added MPHMCounterNum =10 to dut_wrap file
Turned on CSR checking in the Impersas model. Added several CSRs that are needed before asynch. signals can be integrated.
7 of the 10 ci_check tests pass with USE_ISS=YES.

adding initial support for imperas ref model CSR checking.

---

cva6/sim/Makefile

The one runner building spike may not be the same as the ones running
spike.  Because of RUNPATH in spike binary, the `.so` files were looked
for in the runner which has built spike.  This may be a good default for
users but not for CI as this runner is not guaranteed to keep the same
`.so` files, hence the random crashes.
Even without crashing, the found `.so` file was not guaranteed to be the
correct version.
This fix makes sure that the `.so` files are first looked for in the
runner which has downloaded spike as an artifact.
Co-authored-by: Jules Fauchon <jules.fauchon@thalesgroup.com>

fix random spike crash in CI

---

cv32e40s/tb/uvmt/uvmt_cv32e40s_integration_assert.sv
cv32e40s/tb/uvmt/uvmt_cv32e40s_tb.sv

These asserts verify that CV32E40S upholds M_NONE, MUL and DIV instructions should never retire without trapping.

added asserts verifying m_none

---

cv32e40s/tb/uvmt/uvmt_cv32e40s_integration_assert.sv
cv32e40s/tb/uvmt/uvmt_cv32e40s_tb.sv

This PR adds a simple check for maximum outstanding OBI transactions.
Reason:
https://github.com/openhwgroup/core-v-verif/pull/2177#discussion_r1315723317
I was at a crossroads, faced with a dilemma, the choice of trusting the words of men or the words of a machine.
I chose the machine.
Test status:
* ci_check - All good.
* Formal - The new checks pass, the new covers are reached.

Asserts - OBI Max Outstanding

---

bin/clonetb

ci_check ok
Pulls in update that resolves debug_test_trigger test errors in regressions

Updated cv32e40x-dv hash to latest

---

lib/uvm_agents/uvma_rvfi/uvma_rvfi_instr_if.sv

Add rvfi memory signals to rvfi interface. The usermanual is not up to date, but the added rvfi memory signals are official signals in the same manner as rvfi_mem_prot. This PR is connected to other PRs that is not yet made, that is why it looks so "empty". It should not cause any problem to merge it though.
instr/data_prop is not as the other signals, that is because I am lazy and has not changed it. I could do it if that is preferred though.

Add rvfi memory signals to rvfi interface

---

cv32e40s/sim/ExternalRepos.mk
cv32e40s/tb/uvmt/uvmt_cv32e40s_tb.sv

RTL has added an if statement that needs to be included in the path.
Formal compiles
Ci check is all red
But after this bug is fixed: https://github.com/openhwgroup/cv32e40s/issues/499
It is all green except clic config tests (clic and debug_test2) (which I think is a clic problem and not something caused by this change, as that would be weird)

use correct csr privlevel path

---

cv32e40s/tests/uvmt/base-tests/uvmt_cv32e40s_base_test_constants.sv

... to ensure that these are not configured as zero.
To comply with user manual requirement that states that the coefficients must be non-zero

Updated default LFSR-coeffs/seed 

---

cv32e40s/tests/programs/custom/clic/clic.c

Only C-test change, passes without ISS (known ISS mismatch)

Explicitly clear minhv at the end of mret_after_minhv test

---

cv32e40s/tests/cfg/param_set_0.yaml

This PR adds a new test config to compile with the external "param_set_0".

CFG - External Parameter Sets

---

bin/gen_csr_access_test.py

This PR makes `gen_csr_access_test` executable (file permissions and shebang).
It is a minor change that was done while fixing https://github.com/openhwgroup/cv32e40x-dv/pull/37 and https://github.com/openhwgroup/cv32e40x/pull/940.

'gen_csr_access_test' - Make Executable

---

bin/ci_check
cv32e20/regress/cv32e20_ci_check.yaml
cv32e20/sim/uvmt/.gitignore
cv32e20/tb/uvmt/uvmt_cv32e20.flist
lib/uvm_agents/uvma_obi_memory/src/comps/uvma_obi_memory_cov_model.sv
mk/Common.mk
mk/uvmt/vcs.mk

This pull-request is in support of [CVE2 Task #37](https://github.com/openhwgroup/cve2/issues/37).  Specifically, this PR updates various files in CORE-V-VERIF to support simulation of the CV32E20 with VCS.  I also took the liberty of updating the CI regression list to include only those test-programs that are known to pass at this time.

Update CVE2 Makefiles, etc. to support VCS

---

bin/gen_csr_access_test.py

This PR updates the "csr_access_test" generation script.
A new flag had been introduced in the RTL Yaml (VERIF_HEADER).
I also added a license header, description comment, and refactored a long piece of code into its own function.
Relates to https://github.com/openhwgroup/cv32e40x-dv/pull/37

Update Script - `gen_csr_access_test`

---

cv32e40s/regress/cv32e40s_full.yaml
cv32e40s/tests/cfg/clic_default.yaml

Added missing hpmcounter-flag to ISS settings
ci_check ok,
full regression w/o ref. model shows no direct test breakage
fv no impact

Enabled wfe_test and xsecure_* tests in full regression

---

cv32e40s/tb/uvmt/uvmt_cv32e40s_triggers_assert_cov.sv
lib/uvm_agents/uvma_isacov/uvma_isacov_mon.sv

* isacov fix for zb* instructions (isa decoder only, not for spike dasm)
* removed tdata3 cover properties as tdata3 is no longer present in the core

coverage fixes

---

cv32e40s/fv/README.md
cv32e40s/fv/defines.sv
cv32e40s/tb/uvmt/uvmt_cv32e40s_tb.sv

This PR makes compilation of assertions optional.
For blazing fast re-compilation and next level productivity iteration times,  simply use `+define+COREV_ASSERT_OFF` _(and optionally comment away the ifndef for a specific assertion set you want to work on)_.
Compilation times (mm:ss):
* 00:20 - No assertion sets
* 00:23 - One assertion set  (umode_assert)
* 01:30 - All assertion sets
* 02:10 - Internal formal
Test results:
* `ci_check` - All pass (except "clic").
* Cvverif formal - Compiles and runs decently.
* Internal formal - No reds after a few minutes.
--------
I got tired of formal taking so long to recompile just for simple changes, so that is why I implemented this.
An additional bonus, is that the warnings log is much smaller, so you specifically see all warnings related to your …

ASSERT_OFF

---

cv32e40s/tb/uvmt/uvmt_cv32e40s_triggers_assert_cov.sv
cv32e40s/tb/uvmt/uvmt_cv32e40s_xsecure_assert/uvmt_cv32e40s_xsecure_interface_integrity_assert.sv

Remove comment about already removed code (see https://github.com/openhwgroup/core-v-verif/pull/2232)
Fix xsecure prefix.
Formal compiles
Hello-world passes
Didnt see the need for a ci check.

Fix comment, and xsecure prefix.

---

cv32e40s/bsp/handlers.S
cv32e40s/tests/programs/custom/clic/clic.c
cv32e40s/tests/programs/custom/debug_test2/debug_test2.c
cv32e40s/tests/programs/custom/wfe_test/wfe_test.c

- Added U-mode to wfe test
- Added mstatus.tw to wfe test
- Added test: Illegal instruction when executing wfi with mstatus.tw = in umode
- Added default weak u-mode ecall handler to bsp
- Made default m-mode ecall handler symbol weak
- Updated union members in clic/debug2/wfe-test to use uint32_t as other types have exhibited issues
ci_check ok, no non-sw files modified, so fpv should be unaffected, test itself passes OK (not included in ci_check)

Added u-mode and mstatus.tw to wfe test, cleanup

---

cv32e40s/tests/programs/custom/clic/clic.c

only changes to clic test, test passes ok

Update clic test to cover verification holes wrt. illegal mnxti accesses

---

cv32e40s/bsp/bsp.h
cv32e40s/bsp/corev_uvmt.h
cv32e40s/regress/cv32e40s_full.yaml
cv32e40s/tests/programs/custom/cov_holes_generic/cov_holes_generic.c
cv32e40s/tests/programs/custom/debug_test_trigger/test.yaml
cv32e40s/tests/programs/custom/pushpop_debug_triggers/pushpop_debug_triggers.c
cv32e40s/tests/programs/custom/pushpop_debug_triggers/test.yaml

This PR adds a directed sanity test for Zc push/pop triggering debug entry.
Test status:
* The new test - Passes.
* ci_check - N/A.
* "full" - Launches and passes the new test.

Directed Test - Pushpop Debug Triggers

---

mk/uvmt/xrun.mk

… unless explicitly specified
- Prevents slow elaboration when library files are not available

Added flag to prevent xcelium from searching for cds.lib/hdl.var

---

cv32e40s/docs/VerifPlans/Simulation/debug-trace/CV32E40XS_debug.json

This PR updates the debug vplan's json.
PR https://github.com/openhwgroup/core-v-verif/pull/2158 updated the debug vplan, before the younger json files PR https://github.com/openhwgroup/core-v-verif/pull/2193 was merged.
So I updated the debug vplan json with `csv2json`.
_(I actually ran `xlsx2csv` on all vplans, then `csv2json` on all rerults, but debug was the only one who produced any changes.)_
NB! No need to review thoroughly! The original PRs have already been reviewed.

Debug Vplan - Refresh JSON

---

cv32e40s/env/uvme/cov/uvme_clic_covg.sv
cv32e40s/env/uvme/cov/uvme_cv32e40s_cov_model.sv
cv32e40s/env/uvme/cov/uvme_interrupt_covg.sv
cv32e40s/env/uvme/uvme_cv32e40s_cfg.sv
cv32e40s/env/uvme/uvme_cv32e40s_env.sv
cv32e40s/env/uvme/uvme_cv32e40s_pkg.sv

* Added covergroups for clic
* Fixed rvfi to interrupt coverage model connections
* Updated naming in interrupt model for consistency with exception coverage model
Coverage was not sampled for both clic and clint interrupts, works after these fixes are applied

Fixed irq->rvfi-connections, added clic model, naming cleanup

---

cv32e40s/bsp/bsp.h
cv32e40s/regress/cv32e40s_full.yaml
cv32e40s/tests/programs/custom/pmp_csr_access_test/pmp_csr_access_test.c
cv32e40s/tests/programs/custom/wfe_test/wfe_test.c
cv32e40s/tests/programs/custom/zcmt_test/test.yaml
cv32e40s/tests/programs/custom/zcmt_test/zcmt_test.c

* Initial commit to close some obvious mstateen0/umode/zcmt coverage holes (not relevant for 40X)
* Moved commonly used structs to bsp.h
* Cleanup in wfe and pmp_csr_access tests

Added zcmt directed test (40S only), moved structs to bsp

---

cv32e40s/tests/programs/custom/pushpop_debug_triggers/pushpop_debug_triggers.c

Fixed: Debug request was short pulse, could in some instances be missed. Changed to sticky debug req, where the request is disabled from debug handler

Updated pushpop_debug_triggers with sticky debug request

---

cv32e20/regress/cv32e20_ci_check.yaml

The (partial) debug_test is now passing, so it can be added back to the CI regression.

Add debug_test to CI regression

---

cv32e40s/tb/uvmt/uvmt_cv32e40s_clic_interrupt_assert.sv

Spec no longer has this requirement. 
vplan update in later commit

Removed dret to umode clears mintthresh assertion (no longer req)

---

cv32e40s/tb/uvmt/uvmt_cv32e40s_tb.sv
cv32e40s/tb/uvmt/uvmt_cv32e40s_triggers_assert_cov.sv

- Add possibility for external binds
- Comment out failing assertions
removing assertions should not impact ci check, so not testes, but hello-world runs.
Formal compiles.

Add possibility for external binds, comment out failing assertions

---

cv32e40s/tb/uvmt/uvmt_cv32e40s_clic_interrupt_assert.sv

This fixes some unreachable CLIC asserts.
(See inline comments for more details.)
Test status:
* Formal: Compiles, runs, no CEXes after running for a while.
* ci_check: All good.

CLIC Asserts - Fix Unreachable

---

cv32e40s/tb/uvmt/support_logic/uvmt_cv32e40s_rchk_shim.sv
cv32e40s/tb/uvmt/uvmt_cv32e40s_dut_wrap.sv
cv32e40s/tb/uvmt/uvmt_cv32e40s_tb.sv
cv32e40s/tb/uvmt/uvmt_cv32e40s_tb_files.flist
cv32e40s/tb/uvmt/uvmt_cv32e40s_xsecure_assert/uvmt_cv32e40s_xsecure_interface_integrity_assert.sv

Added extra requirement for assert, considering PR: https://github.com/openhwgroup/core-v-verif/pull/2267
Formal compiles
Ci check: all green
I see this is a duplication PR with additional needed stuff, maybe we should just close https://github.com/openhwgroup/core-v-verif/pull/2267, and merge this one instead.

Fix xsecure property

---

cv32e40s/tb/uvmt/support_logic/uvmt_cv32e40s_rchk_shim.sv
cv32e40s/tb/uvmt/uvmt_cv32e40s_dut_wrap.sv
cv32e40s/tb/uvmt/uvmt_cv32e40s_tb.sv
cv32e40s/tb/uvmt/uvmt_cv32e40s_tb_files.flist

Slightly modified version of the PR here: https://github.com/openhwgroup/cv32e40s/pull/511
Adds inverted rchk for non-PMA-integrity regions
- This cannot be merged until assertions are updated to support this functionality

Integrated rchk shim

---

cv32e20/tb/uvmt/uvmt_cv32e20_imperas_dv_wrap.sv
cv32e20/tests/cfg/default.yaml
cv32e20/tests/programs/custom/interrupt_test/interrupt_test.c

Interim changes to interrupt_test to remove non-supported interrupt features.
Update to Imperas nmi connection. and attempt to configure default.yaml file correctly.

Updating interrupt test and Imperas integration.

---

cv32e20/README.md

Update the CV32E20-specific README to point to the Common Makefile for the CORE-V-VERIF UVM Verification Environment.

Add pointer to "Common Makefile"

---

cv32e40s/bsp/bsp.h
cv32e40s/tests/programs/custom/clic/clic.c
cv32e40s/tests/programs/custom/zcmt_test/zcmt_test.c

- Added directed test to cover the case where software sets minhv, executes mret and the table access is blocked
- Added directed test to cover the case where software sets minhv, executes mret and the table pointer derefence is blocked

Updated clic test to cover mret+minvh+access fault trap

---

lib/uvm_agents/uvma_core_cntrl/uvma_core_cntrl_cfg.sv

CORE CNTRL: Add constraint to boot_addr if Compressed extension isn't enable

---

lib/uvm_agents/uvma_obi_memory/src/uvma_obi_memory_assert.sv

This PR adds simple cover-properties for gnt-delays.
Reachable in formal.
Compiles and runs without warning nor error in sim.

OBI - New Gnt-delay Covers

---

lib/uvm_agents/uvma_rvfi/uvma_rvfi_constants.sv
lib/uvm_agents/uvma_rvfi/uvma_rvfi_tdefs.sv
lib/uvm_agents/uvma_rvfi/uvma_rvfi_utils.sv
lib/uvm_components/uvmc_rvfi_reference_model/uvmc_rvfi_spike.sv
vendor/riscv/riscv-isa-sim/Makefile.in
vendor/riscv/riscv-isa-sim/riscv/Proc.cc
vendor/riscv/riscv-isa-sim/riscv/Proc.h
vendor/riscv/riscv-isa-sim/riscv/Simulation.cc
vendor/riscv/riscv-isa-sim/riscv/Simulation.h
vendor/riscv/riscv-isa-sim/riscv/Types.h
vendor/riscv/riscv-isa-sim/riscv/dts.cc
vendor/riscv/riscv-isa-sim/riscv/riscv_dpi.cc
vendor/riscv/riscv-isa-sim/spike_main/spike.cc

Main changes of the PR:
- Making all `st_rvfi` uint64_t
- Changing dpi to use `svOpenArrayHandle`
- Passing `st_rvfi` to Processor
- Verilator v5.018 support

[CVA6] Verilator Tandem Support

---

cv32e40s/regress/cv32e40s_full.yaml
cv32e40s/tb/uvmt/support_logic/uvmt_cv32e40s_sl_trigger_match.sv
cv32e40s/tb/uvmt/uvmt_cv32e40s_triggers_assert_cov.sv
cv32e40s/tb/uvmt/uvmt_cv32e40s_xsecure_assert/uvmt_cv32e40s_xsecure_data_independent_timing_assert.sv
cv32e40s/tb/uvmt/uvmt_cv32e40s_xsecure_assert/uvmt_cv32e40s_xsecure_dummy_and_hint_assert.sv
cv32e40s/tb/uvmt/uvmt_cv32e40s_xsecure_assert/uvmt_cv32e40s_xsecure_hardened_pc_assert.sv
cv32e40s/tb/uvmt/uvmt_cv32e40s_xsecure_assert/uvmt_cv32e40s_xsecure_interface_integrity_assert.sv
cv32e40s/tests/cfg/pma_test_cfg_2_clic.yaml
cv32e40s/tests/programs/custom/mhpmcounter_write_test/test.yaml

make pma 2 clic config
clock sequences for questa
remove todos, 
remove old comment
add comment to make assertions more understandable.
Addresses some of the comments in this PR https://github.com/openhwgroup/core-v-verif/pull/2314
Formal compiles
Ci check: pass

Small fixes

---

cv32e40s/tb/uvmt/uvmt_cv32e40s_pma_assert.sv
lib/uvm_agents/uvma_rvfi/uvma_rvfi_instr_if.sv

This PR fixes an erronous assert, and two TODOs within it.
Test status:
* ci_check - All good.
* Formal - These new asserts ran for about 10-20 minutes without CEXes. (Bound of 18.)

detect pma load/store fault, use in assert

---

cv32e40p/tb/uvmt/uvmt_cv32e40p_debug_assert.sv

Updated the "FIXME" comment header that incorrectly flagged `p_ebreak_exception` and `p_*c*ebreak_exception` as duplicates.

properties p_ebreak_exception and p_cebreak_exception are not duplicates

---

vendor/patches/riscv/riscv-isa-sim/0011-add-cv32a60x-custom-csrs-extn.patch
vendor/riscv/riscv-isa-sim/customext/customext.mk.in
vendor/riscv/riscv-isa-sim/customext/cv32a60x.cc
vendor/riscv/riscv-isa-sim/riscv/cva6.h
vendor/riscv/riscv-isa-sim/riscv/cva6_base.cc
vendor/riscv/riscv-isa-sim/riscv/riscv.mk.in
vendor/riscv/riscv-isa-sim/spike_main/spike.cc

Introduce a new extension 'cv32a6embedded' which once loaded, adds a new ICACHE CSR (address 0x7c0) to the Spike model. The register is of masked type with only bit 0 being writable and a reset value of 0x1.
The CSR is instantiated in the `reset()` method of the extension class. This method must be called after registering the extension with each core, cf. changes in `spike_main/spike.cc`.
Changed files:
* vendor/riscv/riscv-isa-sim/customext/customext.mk.in (customext_srcs): Add cv32a6embedded.cc.
* vendor/riscv/riscv-isa-sim/customext/cv32a6embedded.cc: New.
* vendor/riscv/riscv-isa-sim/riscv/cva6.h: Ditto.
* vendor/riscv/riscv-isa-sim/riscv/cva6_base.cc: Ditto.
* vendor/riscv/riscv-isa-sim/riscv/riscv.mk.in (riscv_install_hdrs): Add cva6.h.  (riscv_srcs): Add cva6_base.cc.
* …

Support additional CVA6 custom CSRs via Spike extension.

---

lib/uvm_agents/uvma_isacov/cov/uvma_isacov_cov_model.sv
lib/uvm_agents/uvma_isacov/uvma_isacov_instr.sv
lib/uvm_agents/uvma_isacov/uvma_isacov_macros.sv
lib/uvm_agents/uvma_isacov/uvma_isacov_mon.sv
lib/uvm_agents/uvma_isacov/uvma_isacov_tdefs.sv

As in the CVA6 we don't have this trap signal (with 12 bit) to identify ecall_ebreak exception code, to work-arroud this I add cause flied and assign it ti rvfi_cause to terminate witch exception code, now we can cover ECALL, EBREAK, C_EBREAK instructions.
The second change is about the DRET instruction, so I conditional it to be define in the coverage if only we're in debug mode, if not is an illegal instruction (and no need to cover it).
The last change related to ZCB instruction, I fix C.MUL instruction covergroup & remove ZCB_GROUP (isn't used)

ISACOV : Coverage Update and tuning

---

lib/uvm_agents/uvma_core_cntrl/uvma_core_cntrl_cfg.sv
lib/uvm_agents/uvma_core_cntrl/uvma_core_cntrl_tdefs.sv
lib/uvm_agents/uvma_rvfi/uvma_rvfi_agent.sv
lib/uvm_agents/uvma_rvfi/uvma_rvfi_cfg.sv
lib/uvm_agents/uvma_rvfi/uvma_rvfi_instr_mon.sv
lib/uvm_agents/uvma_rvfi/uvma_rvfi_utils.sv
lib/uvm_components/uvmc_rvfi_reference_model/uvmc_rvfi_reference_model.sv
lib/uvm_components/uvmc_rvfi_reference_model/uvmc_rvfi_reference_model_pkg.sv
lib/uvm_components/uvmc_rvfi_reference_model/uvmc_rvfi_spike.sv
vendor/patches/riscv/riscv-isa-sim/0014-hartid-param.patch
vendor/riscv/riscv-isa-sim/riscv/Params.cc
vendor/riscv/riscv-isa-sim/riscv/Params.h
vendor/riscv/riscv-isa-sim/riscv/Proc.cc
vendor/riscv/riscv-isa-sim/riscv/Proc.h
vendor/riscv/riscv-isa-sim/riscv/Simulation.cc
vendor/riscv/riscv-isa-sim/riscv/Simulation.h
vendor/riscv/riscv-isa-sim/riscv/processor.cc
vendor/riscv/riscv-isa-sim/riscv/riscv_dpi.cc
vendor/riscv/riscv-isa-sim/riscv/sim.cc
vendor/riscv/riscv-isa-sim/spike_main/spike.cc

QoL: Adding print function for the parameters
Parameters: Implementation pmpregions, misaligned
ZcntrExt: Implementation of isa extension in case of Zcb active rvfi agent: cva6cfg decouple
C++: Lint with clang-format LLVM

[RVFI_AGENT] Decouple RVFI from cva6cfg in tandem configuration

---

lib/uvm_agents/uvma_axi/src/uvma_axi_pkg.sv

Those minor fixes are suggested in the context of supporting Cadence Xcelium simulator for cva6 verification.
Xcelium does not allow the DPI function to be to return a void value.
This means in CVA6 repository, the reference to this function must be updated! If a positive feedback is given, I should created a PR should on cva6 repository and update the core-v-verif hash submodule.
This has been check with VCS 2021.09: the behavior is the same than previous on our side.

[Xcelium support] Remove void from DPI definition

---

lib/uvm_agents/uvma_axi/src/comps/uvma_axi_seq_item_logger.sv
lib/uvm_agents/uvma_cvxif/src/uvma_cvxif_assert.sv
lib/uvm_agents/uvma_rvfi/uvma_rvfi_agent.sv
lib/uvm_components/uvmc_rvfi_reference_model/uvmc_rvfi_reference_model.sv
lib/uvm_components/uvmc_rvfi_scoreboard/uvmc_rvfi_scoreboard.sv

Those minor fixes are suggested in the context of supporting Cadence Xcelium simulator for cva6 verification.
Those modifications allows Xcelium to compile and does not impact VCS usage.
This has been check with VCS 2021.09.

[Xcelium support] Bugfix uvm sysverilog compliant

---

mk/uvmt/xrun.mk

These changes are needed in order to make use of the core-v-verif makefiles outside of the core-v-verif repo.

Using CORE-V-VERIF relative paths instead of Makefile relative paths

---

bin/clonetb
mk/Common.mk
mk/riscof.mk
mk/uvmt/uvmt.mk
mk/uvmt/xrun.mk

Porting over the RISC-V architecture tests from E40P over to the cv32e40x. This makes it possible to run the full riscof complience test suite for the cv32e40x.

Adding make targets needed to run riscof arch-tests for cv32e40x

---

mk/riscof.mk

The riscof tool requires you to run the riscof tool from a certain path as the config file paths are relative to the location where you execute riscof from. So in this change we are more explicit on setting the current working directory before running any of the riscof commands.
Also removing much of the headers/banner from the makefile to make it more readable and compact.

Cleaning up the riscof makefile and fixing cwd issue

---

.gitignore
cv32e40p/env/uvme/cov/uvme_cv32e40p_cov_model_macros.sv
cv32e40p/env/uvme/cov/uvme_cv32e40p_fp_instr_covg.sv
lib/uvm_agents/uvma_isacov/uvma_isacov_macros.sv
mk/uvmt/vcs.mk

This pull-request resolves an issue with #2392 that impacts VCS.   It incorporates the so-called `UNSUPPORTED_WITH` work-around that is in use by multiple CORE-V-VERIF projects.  It is ugly, but works and needs to be in place until at least the next release of VCS.

Incorporate UNSUPPORTED_WITH kludge for VCS

---

lib/uvm_agents/uvma_cvxif/src/comps/uvma_cvxif_cov_model.sv
lib/uvm_agents/uvma_cvxif/src/obj/uvma_cvxif_cfg.sv

This MR, ignore req.mode bins if supervisor mode or user mode isn't supported

CVXIF Agent: Ignore Supervisor and User mode when it's not supported

---

lib/uvm_agents/uvma_cvxif/src/uvma_cvxif_assert.sv

This MR change a cvxif assertion to compile it in the latest version of VCS 2023, the assertion remain as before in term of logic

Remove strong operator in cvxif SVA to match VCS 2023 version

---

vendor/riscv/riscv-isa-sim/riscv/Params.cc
vendor/riscv/riscv-isa-sim/riscv/Params.h
vendor/riscv/riscv-isa-sim/riscv/Proc.cc
vendor/riscv/riscv-isa-sim/riscv/Simulation.cc
vendor/riscv/riscv-isa-sim/riscv/riscv_dpi.cc
vendor/riscv/riscv-isa-sim/riscv/sim.cc
vendor/riscv/riscv-isa-sim/spike_main/spike.cc

* vendor/riscv/riscv-isa-sim/riscv/Params.h (Param::setFromCmdline): New.
* vendor/riscv/riscv-isa-sim/spike_main/spike.cc (main): Declare 'params'<br>
variable ahead of cmdline options.  Add cmdline option '--param PATH=VALUE'.<br>
Add corresponding help string.

Control Spike parameters from cmdline.

---

vendor/riscv/riscv-isa-sim/customext/cvxif.cc

* vendor/riscv/riscv-isa-sim/customext/cvxif.cc (EXTENSION_NAME): New.
(c##n): Call 'get_extension' with name of current extension.
(cvxif_t::name): Use EXTENSION_NAME.

Fix cva6 issue 1972: Spike crash when using CV-X-IF with another extension.

---

cv32e40p/env/corev-dv/instr_lib/cv32e40p_float_instr_lib.sv
cv32e40p/env/uvme/cov/uvme_cv32e40p_cov_model.sv
cv32e40p/env/uvme/uvme_cv32e40p_env.sv
cv32e40p/env/uvme/vseq/uvme_cv32e40p_random_debug_vseq.sv
cv32e40p/sim/tools/dsim/ccov_scopes.txt
cv32e40p/tb/uvmt/uvmt_cv32e40p_macros.sv
cv32e40p/tests/uvmt/base-tests/uvmt_cv32e40p_base_test.sv
mk/uvmt/dsim.mk

This PR re-establishes [Metrics DSim](https://www.metrics.ca/) as one of the SV simulators supported by CORE-V-VERIF.  Changes fall into one of the following categories:
- Fixes to Makefiles and associated scripts.
- Workarounds for specific DSim parser issues.  These are clearly identified in comments (look for "Metrics DSim") and do not alter the function or the code.
- Increased the verbosity level for printing the testcase and environment configurations (from UVM_NONE to UVM_DEBUG).
Tested these changes with VCS, Questasim and DSim.

Restore DSim

---

cv32e40p/env/uvme/cov/uvme_cv32e40p_cov_model_macros.sv
cv32e40p/env/uvme/cov/uvme_cv32e40p_fp_instr_covg.sv
lib/uvm_agents/uvma_isacov/uvma_isacov_macros.sv
mk/uvmt/vcs.mk

This pull-request backs out the workaround added in #2393.  The implication is that VCS users must have an up-to-date version such as `U-2023.03-SP1` or `V-2023.12-1` (or newer).

Remove UNSUPPORTED_WITH workaround for VCS (resolved as of V-2023.12-1)

---

cv32e40s/fv/Makefile
cv32e40s/fv/onespin.tcl
cv32e40s/tb/uvmt/uvmt_cv32e40s_tb.sv

This PR adds support for loading the cv32e40s core into onespin.
While there's remaining work to properly integrate the assertions from cv32e40s_wrapper.sv, I'm still submitting the PR as discussed with @silabs-robin

Add script for basic onespin support for cv32e40s

---

vendor/patches/riscv/riscv-isa-sim/0020-fix-dashdashparam-handling.patch
vendor/riscv/riscv-isa-sim/riscv/Params.h
vendor/riscv/riscv-isa-sim/spike_main/spike.cc

- (Params.h) Support any C/C++ radix when setting uint64_t params
from cmdline.
- (spike.cc) Update help string.  Move default initialization of param
values ahead of command line parsing.

[Spike params] Fix parameter handling: parsing, help, assignment order.

---

.gitmodules
lib/uvm_components/uvmc_rvfi_reference_model/rvfi_spike.sv
lib/uvm_components/uvmc_rvfi_scoreboard/uvmc_rvfi_scoreboard_utils.sv
vendor/riscv/riscv-isa-sim/Makefile.in
vendor/riscv/riscv-isa-sim/riscv/Simulation.cc
vendor/riscv/riscv-isa-sim/riscv/YamlParamSetter.cc
vendor/riscv/riscv-isa-sim/riscv/YamlParamSetter.h
vendor/riscv/riscv-isa-sim/riscv/riscv.mk.in
vendor/riscv/riscv-isa-sim/riscv/riscv_dpi.cc
vendor/riscv/riscv-isa-sim/spike_main/spike.cc

Add the ability to configure Spike via a YAML parameter file.
The YAML file can be used in both solo and tandem mode:
- solo mode: use "--yaml-param FILENAME" to standalone Spike
- tandem mode: pass "+configf_ile=FILENAME" to the RTL simulator.
The documentation is yet to come, and so is the Spike patch file.

Add YAML interface to control Spike parameters in solo and tandem mode.

---

cv32e40p/env/corev-dv/cv32e40p_illegal_instr.sv
cv32e40p/tb/uvmt/uvmt_cv32e40p_tb_ifs.sv

1) Update bhavioral logic on collecting clk_cycle_window for b2b addr phase scnearios
2) Fix incorrect constraint from parent after factory overidden by child class

Fix tb issues

---

cv32e40p/env/corev-dv/cv32e40p_instr_base_test.sv
cv32e40p/env/corev-dv/cv32e40p_instr_test_pkg.sv
cv32e40p/env/corev-dv/cv32e40p_load_store_instr_lib.sv

The following code generation command would fail (see attached file for error message);
```
make gen_corev-dv TEST=corev_rand_illegal_instr_test CV_CORE=cv32e40p CFG=pulp_fpu_zfinx_1cyclat TEST_CFG_FILE=floating_pt_zfinx_instr_en,disable_all_trn_logs SIMULATOR=vsim SEED=1248233755
```
This was due to memory stress streams randomly reserving all allowed registers for compressed instructions (S0 to A5) 
The fix consists in checking the number of S0:A5 registers that have been already reserved before randomization, and making sure that there are less registers taken in that range.  
[mem_stress_with_compress_failure.log](https://github.com/openhwgroup/core-v-verif/files/15335288/mem_stress_with_compress_failure.log)

CV32E40P fix for mem stress scenario with compressed instructions

---

vendor/patches/riscv/riscv-isa-sim/0022-fix-spike-version-reporting.patch
vendor/riscv/riscv-isa-sim/Makefile.in
vendor/riscv/riscv-isa-sim/spike_main/spike.cc

Fix the handling of short Git hash used in Spike version checking in CI scripts
(see https://github.com/openhwgroup/cva6/issues/2110):
- Avoid using 'git log' with paths containing '..';
- Handle the short hash as a string to preserve all characters including leading zeroes.

[Spike] Use correct value of Git short hash when printing Spike version.

---

vendor/patches/riscv/riscv-isa-sim/0021-add-support-to-ratified-B-standard-extension.patch
vendor/riscv/riscv-isa-sim/disasm/isa_parser.cc

Add support to [B Standard Extension for Bit Manipulation Instructions](https://drive.google.com/file/d/1SgLoasaBjs5WboQMaU3wpHkjUwV71UZn/view?usp=drive_link) listed in [Ratified Extensions](https://wiki.riscv.org/display/HOME/Ratified+Extensions).
> Chapter 1. B Standard Extension for Bit
> Manipulation Instructions
> The B standard extension comprises instructions provided by the Zba, Zbb, and Zbs extensions.
> 1.1. Privileged Architecture Implications
> Bit 1 of the misa register encodes the presence of the B standard extension. When misa.B is 1, the
> implementation supports the instructions provided by the Zba, Zbb, and Zbs extensions. When
> misa.B is 0, it indicates that the implementation may not support one or more of the Zba, Zbb, or Zbs
> extensions.

Add support to ratified B Standard Extension for Bit Manip. Instructions

---

lib/uvm_agents/uvma_rvfi/seq/uvma_rvfi_instr_seq_item.sv

This PR fixes Questasim compilation after the previous PR.
After https://github.com/openhwgroup/core-v-verif/pull/2427, compilation did not work for me using vsim because of this need for an explicit cast.
Test status:
* xrun ci_check - pass
* vsim hello world - pass

s/release Vsim Fixes

---

cv32e40p/env/corev-dv/cv32e40p_load_store_instr_lib.sv

In #2439, I introduced a fix to prevent all compressed-dedicated registers to be reserved for some streams, but I didn't pay attention that `.sum()` method for arrays is type-conservative, so it was always giving 0 or 1 in the constraints solver...
By luck, it solved the issue for the specific testcase I gave, but (of course...) the error came back for another testcase : 
```
make gen_corev-dv TEST=corev_rand_instr_test CV_CORE=cv32e40p COREV=1 CFG=pulp_fpu_zfinx_1cyclat TEST_CFG_FILE=floating_pt_zfinx_instr_en,disable_all_trn_logs SIMULATOR=vsim SEED=784606021
```
(I hope) I solved this for good.

Corrected a non-expected behavior due to PR2439

---

mk/uvmt/vsim.mk

This PR fixes `ADV_DEBUG=1` to work for vsim.
--------
Without `ADV_DEBUG=1` I get an ancient GUI (where I can't even find the "start" button).
Without this fix, I run
`make test TEST=hello-world SIMULATOR=vsim USE_ISS=0  GUI=1 ADV_DEBUG=1 WAVES=1`
and get:
```
Fatal Error :
Design File ../design.bin not found ...
```
Because the `../design.bin` path is slightly off.
--------
Test status:
* Hello world with GUI (ADV_DEBUG) - Pass
* `ci_check` - Pass, except...
* ... 4 runs say failed even though they print pass in the log, because Questa prints a message about not liking seeds with negative values.
* I think it is extremely unlikely that this PR has introduced this, as it touches something unrelated, so since all logs print "SIMULATION PASSED" I deem it as passed.

Questasim - Fix ADV_DEBUG

---

mk/core/core.mk
mk/uvmt/uvmt.mk

I did not find anywhere in any up-to-date `cv32e40s/dev`, `cv32e40x/dev` and `master` what you told me in #2123, so I added my own version, don't hesitate to discard the PR if I missed it or I didn't search in the right place.
The modification will simply check if USE_ISS have been given as an argument to the make command, and if not, it will decide to update USE_ISS to YES or NO depending on the definition or not of the IMPERAS_HOME variable.
As a bonus, an info message telling the user what's going on. 
I found USE_ISS definition in two files, I don't remember using core.mk during the last months, but I copy and paste the code from uvmt.mk anyway.

Added behavior discussed in Issue 2123 for USE_ISS

---

cv32e40p/env/uvme/vseq/uvme_cv32e40p_interrupt_noise_vseq.sv

Reduced a bit interrupt delay scenario as some wfi stress tests result in the core just waiting 90% of the simtime (70ms simtime...)

Reduced interrupt delay (long scenario)

---

lib/uvm_libs/uvml_mem/uvml_mem.sv

1. Register parameterized `uvml_mem_c` class with `uvm_object_param_utils` per chapter 6.2.2 of uvm user guide 1.2.
2. Update write()/read() method as virtual.
> 6.2.2 Factory Registration
> You must tell the factory how to generate objects of specific types. In UVM, there are a number of ways to
> do this allocation.
> — The recommended method is to use the `uvm_object_utils(T) or `uvm_compo-
> nent_utils(T) macro in a derivative uvm_object or uvm_component class declaration,
> respectively. These macros contain code that will register the given type with the factory. **If T is a
> parameterized type, use `uvm_object_param_utils` or 
> `uvm_component_param_utils`,** , e.g.,
> `uvm_object_utils(packet)
> ‘uvm_component_param_utils(my_driver)

Register parameterized uvml_mem_c with `uvm_object_param_utils and update write()/read() as virtual

---

lib/uvm_agents/uvma_axi5/src/uvma_axi_macros.sv
lib/uvm_agents/uvma_axi5/src/uvma_axi_pkg.sv
lib/uvm_libs/uvml_mem/uvml_mem_constants.sv
lib/uvm_libs/uvml_mem/uvml_mem_macros.sv

To make AXI and MEM agents be used as different address/data/... widths, this PR refers to Mentor's below page and update parameters as macros.
Mentor's link here,
https://verificationacademy.com/forums/t/override-parameters-in-sv-package/33682/4

Update parameters in package to be defined as macros

---

bin/illegal_instr_generator_cv32e40p_v2.pl

This is a modification I did to the script done by Greg Tumbush (see his script in commit d87679a)
Unfortunately, this script was not working as-is for us using latest embecosm toolchain, so we had to update it to make it work (mainly, options given to the binaries, and some grepping that were not working anymore due to this) 
As this file were not pushed on `cv32e40p/dev` branch and we were working on tit exclusively without merging back-and-forth with `master`, I named this file differently to avoid later merge conflicts. 
Also, I took the opportunity to improve the script with a more directive approach for Xpulp and F instructions while keeping the great idea from the base script: I generate an exhaustive list of possibly illegal instruction with fixed operand values, and I give it to …

Illegal instruction generator for CV32E40Pv2

---

vendor/patches/riscv/riscv-isa-sim/0027-fix-p-ext-kslraw-u.patch
vendor/riscv/riscv-isa-sim/riscv/insns/kslraw_u.h

Credit goes to my colleague **Han** for his contributions.
Per P ext 0.9.11, fix kslraw.u behavior.
```
if (Rs2[5:0] s< 0) {
  sa = -Rs2[5:0];
  sa = (sa == 32)? 31 : sa;
  res[31:-1] = SE33(Rs1[31:(sa-1)]) + 1;
  rst[31:0] = res[31:0];
} else {
  sa = Rs2[5:0];
  tmp[(31+sa):0] = Rs1.W[0] u<< sa;
  if (tmp s> (2^31)-1) {
    rst[31:0] = (2^31)-1;
    OV = 1;
  } else if (tmp s< -2^31) {
    rst[31:0] = -2^31;
    OV = 1
  } else {
    rst[31:0] = tmp[31:0];
  }
}
Rd = rst[31:0]; // RV32
Rd = SE64(rst[31:0]); // RV64
```

Fix kslraw.u instruction in P extension, version 0.9.11

---

lib/uvm_agents/uvma_isacov/cov/uvma_isacov_cov_model.sv

This MR is related to update csr_hazard cross in isacov coverage model, instead of cross csr_hazard with cp_instr (this give more then 20000 bin to cover), I replace it with cp_group this reduce a little bit the combination to be cover.
N.B : I don't konw if this cross is necessary for our verification goals

Only cross with cp_group in csr_hazard coverpoint

---

lib/uvm_components/uvmc_rvfi_reference_model/rvfi_spike.sv

Adding more parameters to align the reference model to the cve2 core

[cve2] Add params for GM configuration

---

vendor/riscv/riscv-isa-sim/Makefile.in

Do not link shared libraries of Spike against libyaml-cpp to avoid unnecessary library dependencies.

[Spike Yaml] Remove unnecessary dependencies between Spike and Yaml libs.

---

lib/uvm_components/uvmc_rvfi_reference_model/rvfi_spike.sv

This overwrite was preventing the yaml to configure this parameter

[RVFI] Fix unified_traps param overwrite 

---

lib/cv_dv_utils/uvm/Files.f

This pull-request removes all entries related to the _dram_monitor_ from `lib/cv_dv_utils/uvm/Files.f`.
Fix for #2544.

Remove dram_monitor from Flist

---

vendor/patches/riscv/riscv-isa-sim/0035-increase-pmp-granularity-to-8.patch
vendor/riscv/riscv-isa-sim/riscv/Proc.cc
vendor/riscv/riscv-isa-sim/riscv/processor.cc

Increase default PMP granularity from 4 to 8.  Add support for corresponding core-level parameter `pmp_granularity`.

[Spike] Set default PMP granularity to 8.  Add support for corresponding Yaml parameter.

---

vendor/patches/riscv/riscv-isa-sim/0036-add-missing-shamt-checks-in-rv32-extB-32b.patch
vendor/riscv/riscv-isa-sim/riscv/insns/bclri.h
vendor/riscv/riscv-isa-sim/riscv/insns/bexti.h
vendor/riscv/riscv-isa-sim/riscv/insns/binvi.h
vendor/riscv/riscv-isa-sim/riscv/insns/bseti.h

Add standard legality check for `shamt` value where missing (`bclr.i`, `bext.i`, `binv.i`, `bset.i`). Use the same clause as in `ror.i` which was correctly implemented in the first place.

[Spike] Fix #2576: Ensure bit 25 is clear for RV32 extB 32b insns (+ patch)

---

lib/uvm_agents/uvma_cvxif/src/comps/uvma_cvxif_drv.sv
lib/uvm_agents/uvma_cvxif/src/obj/uvma_cvxif_cfg.sv
lib/uvm_agents/uvma_cvxif/src/uvma_cvxif_assert.sv

This is some changes on cvxif uvm agent :
remove wrong assertion
add support to the agent to see that the cpu is retracting transaction

CVXIF UVM agent : remove wrong assertion

---

lib/uvm_agents/uvma_core_cntrl/uvma_core_cntrl_utils.sv
vendor/patches/riscv/riscv-isa-sim/0037-make-zifencei-optional.patch
vendor/riscv/riscv-isa-sim/disasm/isa_parser.cc
vendor/riscv/riscv-isa-sim/riscv/insns/fence_i.h
vendor/riscv/riscv-isa-sim/riscv/isa_parser.h

Spike part of fix to CVA6 issue https://github.com/openhwgroup/cva6/issues/2734.
Spike code explicitly assumed `Zifencei` as being present for backward compatibility, cf. the diff on `isa_parser.cc`.
This request changes the original Spike behavior to require the explicit inclusion of `Zifencei` in the ISA string to enable the `fence.i` instruction.

[Spike] Fix #2579: Require explicit Zifencei in ISA to enable fence.i instruction.

---

lib/uvm_agents/uvma_core_cntrl/uvma_core_cntrl_utils.sv

Remove the systematic activation of `Xcvxif` ISA extension when the RTL instantiates CV-X-IF. The activation of the extension shall now be done **exclusively** through the Spike ISA string.

[Core cntrl agent] Do not pass 'xcvxif' to Spike if CV-X-IF is present.

---

vendor/patches/riscv/riscv-isa-sim/0042-fix-extension-reset.patch
vendor/riscv/riscv-isa-sim/riscv/Proc.cc

Explicitly reset non-ISA Spike extensions such as `cv32a60x` in the `Proc` constructor.
Such extensions contain no instruction definitions, only CSR definitions and hence, were not reset correctly. As a result, the CSRs provided by the `cv32a60x`extension were instantiated.

[Spike] Reset non-ISA extensions when registering them (as per comment!)

---

lib/uvm_agents/uvma_isacov/cov/uvma_isacov_cov_model.sv

remove unsupported with workaround as it's been resolved in V-2023.12.1

ISACOV: remove unsupported_with workaround (fix #2404)

---

vendor/riscv/riscv-isa-sim/customext/cvxif.cc

Apply proper sign extension and clipping rules for arithmetic operations used in CV-X-IF verification instructions.

[Spike] Apply systematic XLEN sign extension and clipping policy in CV-X-IF insns.

---

lib/uvm_agents/uvma_obi_memory/src/uvma_obi_memory_assert.sv

This is a fix for an assertion that check requirement 8 in OBI v1.2

OBI ASSERT : Fix issue #2599

---

vendor/patches/riscv/riscv-isa-sim/0043-allow-unmapped-mem-access.patch
vendor/riscv/riscv-isa-sim/riscv/Proc.cc
vendor/riscv/riscv-isa-sim/riscv/mmu.cc
vendor/riscv/riscv-isa-sim/riscv/mmu.h
vendor/riscv/riscv-isa-sim/riscv/processor.cc
vendor/riscv/riscv-isa-sim/riscv/sim.cc

Extend Spike with infrastructure to conditionally allow fetching, reading and writing from/to unmapped memory addresses:
- Extend MMU state with a variable indicating if accesses to unmapped addresses should trigger an exception or execute successfully.
- Modify MMU constructor to handle initial unmapped access behavior.
- Modify MMU behavior: If accesses to unmapped locations are allowed, do not trap and return zeros on FETCH and LOAD, do nothing on STORE (see issue https://github.com/openhwgroup/cva6/issues/1625).
- Modify `processor_t` class to instantiate the core's MMU with unmapped access disabled.
- Modify `openhw::Processor` class to query the corresponding core-level Yaml parameter `allow_unmapped_mem_access` and modify MMU behavior accordingly.  In the absence of such parameter …

[Spike] Add control of behavior when accessing unmapped addresses.

---

lib/uvm_agents/uvma_obi_memory/src/uvma_obi_memory_1p2_assert.sv
lib/uvm_agents/uvma_obi_memory/src/uvma_obi_memory_assert.sv

This is a modification in obi assertion module, to add cover property for all properties.
This help use to be sure that we really passed by the scenario in the property.

OBI Verif : add coverage for all properties

---

cv32e40p/sim/core/Makefile
cv32e40p/tb/core/cv32e40p_core_tb_wrapper.sv
cv32e40p/tb/core/cv32e40p_tb_wrapper.sv
cv32e40p/tb/core/tb_top.sv
cv32e40p/tb/core/tb_top_verilator.cpp
cv32e40p/tb/core/tb_top_verilator.sv

Resolves #2584, and cleans up DSim compiles as well.

Restore Verilator compile/simulation

---

lib/uvm_agents/uvma_obi_memory/src/uvma_obi_memory_assert.sv

Byte enable should be check during address phase, not only for write transaction

OBI assertion : be signal shouldn't be zero during address phase

---

vendor/patches/riscv/riscv-isa-sim/0044-cvxif-no-more-implicit-x10-dest-reg.patch
vendor/riscv/riscv-isa-sim/customext/cvxif.cc

Change the semantics of CV-X-IF verification instructions CUS_ADD_RS3_RTYPE and CUS_CADD:
- Drop the implicit x10 destination.
- Use the per-format **explicit** destination register instead.
This streamlines the internal operation of the CVA6 core (insn decoder and forwarding): the decoded destination reg address can be used directly for RD write and in forwarding without requiring any lookups.

[Spike][CV-X-IF] Do not use implicit x10 RD for CUS_ADD_RS3_RTYPE/CUS_CADD.

---

vendor/patches/riscv/riscv-isa-sim/0044-don-t-optimize-decode-for-addi.patch
vendor/riscv/riscv-isa-sim/disasm/disasm.cc

Fix in spike disam, to avoid pseudo code generation and can cover instructions

SPIKE DISAM: do not use pseudo instructions

---

vendor/patches/riscv/riscv-isa-sim/0045-spike-disasm-don-t-optimaze-jump-instructions.patch
vendor/riscv/riscv-isa-sim/disasm/disasm.cc

This fix disam to not generate pseudo code for jal & jalr

Spike disasm: don't optimize jump instructions

---

lib/uvm_agents/uvma_cvxif/src/uvma_cvxif_assert.sv

Original coding style reported the following error with xcelium and prevents compilation of the cva6 uvm environment :
xmvlog: *E,SFLNOS (cva6/verif/sim/../core-v-verif/lib/uvm_agents/uvma_cvxif/src/uvma_cvxif_assert.sv,110|150): Automatic variables in assertion action block are not supported.

Rework the loop around the rs_valid assert

---

lib/cv_dv_utils/python/sim_cmd/get_cmd.py
lib/cv_dv_utils/python/sim_cmd/run_reg.py
lib/cv_dv_utils/python/sim_cmd/run_test.py
lib/cv_dv_utils/uvm/generic_agent/README.md
lib/cv_dv_utils/uvm/generic_agent/generic_agent.svh
lib/cv_dv_utils/uvm/generic_agent/generic_driver.svh
lib/cv_dv_utils/uvm/generic_agent/generic_sequencer.svh
lib/cv_dv_utils/uvm/generic_agent/generic_sequences.svh

Hello,
In a generic agent, protocol is not known before hand. So it is not possible to correctly define the functionning of response handler. 
Hence I have removed this. 
Regards
Tanuj Khandelwal

removed use_response_handler: not possible in a generic agent

---

vendor/patches/riscv/riscv-isa-sim/0046-no-pmp-config-via-device-trees.patch
vendor/riscv/riscv-isa-sim/riscv/sim.cc

This modification prevents last-instance reconfiguration of the PMPs during the elaboration phase of the simulation.
In the original implementation, PMP granularity and PMP region counts of individual cores were set based on the content of the built-in device tree _after_ applying all per-core parameters supplied in Yaml config file and/or on the Spike command line.  The PMP granularity value encoded in the default device tree is 4 and it was overriding the expected granularity of 8 bytes supplied via configuration parameter `/top/core/<id>/pmp_granularity`.

[Spike] Do not re-configure PMPs based on device tree information.
